"""EW-domain Round-1 elicitation questions."""

from domains._schema import Question

EW_QUESTIONS: list[Question] = [
    # Tier 1: Mandatory
    Question(id="ew.t1.freq_range", domain="ew", tier=1, category="RF Performance",
             text="Frequency range of interest (MHz to MHz)? e.g. 1.5-30, 20-1000, 2-3000",
             expected_format="MHz"),
    Question(id="ew.t1.ew_type", domain="ew", tier=1, category="Application",
             text="System type? (search / monitoring / jammer / SIGINT / ESM / DF / ELINT / COMINT)",
             expected_format="enum"),
    Question(id="ew.t1.platform", domain="ew", tier=1, category="Application",
             text="Platform? (airborne / ground-mobile / ground-fixed / naval / truck-mounted)",
             expected_format="enum"),
    Question(id="ew.t1.channels", domain="ew", tier=1, category="Architecture",
             text="Number of simultaneous channels? (single / 3 / 4 / 8 / 16+)",
             expected_format="int"),
    Question(id="ew.t1.inst_bw", domain="ew", tier=1, category="RF Performance",
             text="Instantaneous bandwidth per channel (MHz)?",
             expected_format="MHz"),
    Question(id="ew.t1.dynamic_range", domain="ew", tier=1, category="RF Performance",
             text="SFDR requirement (dB)?",
             expected_format="dB"),
    Question(id="ew.t1.sensitivity", domain="ew", tier=1, category="RF Performance",
             text="Target sensitivity / noise figure (dBm or dB)?",
             expected_format="dBm or dB"),
    Question(id="ew.t1.probability_intercept", domain="ew", tier=1, category="Performance",
             text="Probability of intercept (POI) requirement? % or free-text",
             expected_format="%"),
    # Tier 2: Signal-type specific
    Question(id="ew.t2.signal_type", domain="ew", tier=2, category="Signal Environment",
             text="Signal types to handle? (CW / pulsed / frequency-hopped / spread-spectrum / LPI)",
             expected_format="list"),
    Question(id="ew.t2.pulse_handling", domain="ew", tier=2, category="Signal Environment",
             text="Pulse handling: min PW, max PW, PRI range, time-of-arrival accuracy?",
             expected_format="multi",
             triggers=["pulsed"]),
    Question(id="ew.t2.df_accuracy", domain="ew", tier=2, category="DF",
             text="Direction-finding accuracy (degrees RMS)? DF technique? (amp-monopulse / interferometric / Watson-Watt)",
             expected_format="degrees",
             triggers=["DF", "ESM", "ELINT"]),
    Question(id="ew.t2.co_site", domain="ew", tier=2, category="Environment",
             text="Co-site interference environment? (same platform jammer levels in dBm, isolation req)",
             expected_format="dBm/dB"),
    Question(id="ew.t2.tempest", domain="ew", tier=2, category="Compliance",
             text="TEMPEST / emissions security required? NACSIM 5100A equivalent?",
             expected_format="yes/no"),
    Question(id="ew.t2.warmup", domain="ew", tier=2, category="Operational",
             text="Warm-up / lock-in time requirement (seconds)?",
             expected_format="seconds"),
    # Tier 1: Environment / Compliance
    Question(id="ew.t1.temp_range", domain="ew", tier=1, category="Environmental",
             text="Operating temperature range? (commercial / industrial / military -55 to +125)",
             expected_format="enum"),
    Question(id="ew.t1.standards", domain="ew", tier=1, category="Compliance",
             text="Required compliance standards? (MIL-STD-461 with CE/RE focus, 810, 704, STANAG, TEMPEST)",
             expected_format="list"),
]
