"""Satcom-domain Round-1 elicitation questions."""

from domains._schema import Question

SATCOM_QUESTIONS: list[Question] = [
    # Tier 1: Mandatory
    Question(id="satcom.t1.band", domain="satcom", tier=1, category="RF Performance",
             text="Satcom band? (L / S / C / X / Ku / Ka / Q / V) — specify exact Tx/Rx frequencies if known",
             expected_format="enum+MHz"),
    Question(id="satcom.t1.terminal_type", domain="satcom", tier=1, category="Application",
             text="Terminal type? (fixed VSAT / SOTM / manpack / airborne / maritime / earth station)",
             expected_format="enum"),
    Question(id="satcom.t1.orbit", domain="satcom", tier=1, category="Application",
             text="Target constellation orbit? (GEO / MEO / LEO / HEO / multi-orbit)",
             expected_format="enum"),
    Question(id="satcom.t1.gt", domain="satcom", tier=1, category="Link Budget",
             text="G/T (figure of merit) requirement in dB/K? Include antenna diameter if specified.",
             expected_format="dB/K"),
    Question(id="satcom.t1.eirp", domain="satcom", tier=1, category="Link Budget",
             text="EIRP requirement (dBW)? (uplink — include HPA output power and antenna gain)",
             expected_format="dBW"),
    Question(id="satcom.t1.data_rate", domain="satcom", tier=1, category="Link Budget",
             text="Data rate (Mbps) and modcod? (DVB-S2X, custom waveform, MIL-STD-188-165B, etc.)",
             expected_format="Mbps+modcod"),
    Question(id="satcom.t1.polarization", domain="satcom", tier=1, category="Antenna",
             text="Polarization? (linear H/V / circular RHCP/LHCP / dual-pol / switchable)",
             expected_format="enum"),
    Question(id="satcom.t1.antenna", domain="satcom", tier=1, category="Antenna",
             text="Antenna diameter / aperture (m or cm) and type? (parabolic / flat-panel ESA / phased array)",
             expected_format="m+type"),
    # Tier 2: Tracking / dynamic terminals
    Question(id="satcom.t2.tracking", domain="satcom", tier=2, category="Antenna Control",
             text="Tracking technique? (step-track / monopulse / conical-scan / ESA beam-steering / manual)",
             expected_format="enum",
             triggers=["SOTM", "airborne", "maritime"]),
    Question(id="satcom.t2.pointing", domain="satcom", tier=2, category="Antenna Control",
             text="Pointing accuracy (degrees RMS)? Acquisition time budget (seconds)?",
             expected_format="deg+sec",
             triggers=["SOTM", "airborne", "maritime", "manpack"]),
    Question(id="satcom.t2.bwd_isolation", domain="satcom", tier=2, category="RF Performance",
             text="Tx-to-Rx isolation required (dB)? Diplexer or separate antennas?",
             expected_format="dB"),
    Question(id="satcom.t2.anti_jam", domain="satcom", tier=2, category="Security",
             text="Anti-jam / LPI / AJ features required? FHSS / nulling / beam-forming?",
             expected_format="enum+detail"),
    # Tier 1: Environment / Compliance
    Question(id="satcom.t1.temp_range", domain="satcom", tier=1, category="Environmental",
             text="Operating temperature range? (commercial / industrial / military / space-qualified)",
             expected_format="enum"),
    Question(id="satcom.t1.standards", domain="satcom", tier=1, category="Compliance",
             text="Required compliance? (MIL-STD-188-164/165, DO-160G, MIL-STD-461/810, ITU-R, ETSI)",
             expected_format="list"),
    Question(id="satcom.t1.export", domain="satcom", tier=1, category="Compliance",
             text="Export control concerns? (ITAR / EAR / dual-use / domestic-only)",
             expected_format="enum"),
]
