// Top-level schematic viewer used as the "Schematic" sub-tab under P4 Documents.
// Handles:
//   • fetching schematic.json from the project output directory
//   • multi-sheet navigation
//   • pan/zoom (native SVG viewBox + wheel / drag)
//   • PDF export (jsPDF + svg2pdf.js, vector output)
//   • hovered-net highlight + net side panel

import { useEffect, useRef, useState, useMemo } from 'react';
import { jsPDF } from 'jspdf';
import { svg2pdf } from 'svg2pdf.js';
import { api } from '../../api';
import SheetSchematic from './SheetSchematic';
import type { SchematicData, SheetData, NetData, ComponentData } from './symbols/types';
import { NET_COLORS } from './symbols/types';

interface Props {
  projectId: number;
  color: string;  // phase color for buttons
}

export default function SchematicView({ projectId, color }: Props) {
  const [data, setData] = useState<SchematicData | null>(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);
  const [sheetIdx, setSheetIdx] = useState(0);
  const [hoveredNet, setHoveredNet] = useState<string | null>(null);
  const [downloading, setDownloading] = useState(false);
  const [dlError, setDlError] = useState<string | null>(null);
  const svgRef = useRef<SVGSVGElement | null>(null);

  // Fetch schematic.json from the output dir — falls back nicely if missing
  useEffect(() => {
    let aborted = false;
    (async () => {
      try {
        setLoading(true);
        setErr(null);
        const raw = await api.getDocumentText(projectId, 'schematic.json');
        if (aborted) return;
        const parsed = JSON.parse(raw) as SchematicData;
        if (!parsed.sheets || parsed.sheets.length === 0) {
          setErr('Schematic JSON has no sheets.');
          return;
        }
        setData(parsed);
      } catch (e: unknown) {
        if (!aborted) setErr(e instanceof Error ? e.message : String(e));
      } finally {
        if (!aborted) setLoading(false);
      }
    })();
    return () => { aborted = true; };
  }, [projectId]);

  const sheet: SheetData | null = useMemo(
    () => (data && data.sheets[sheetIdx]) || null,
    [data, sheetIdx],
  );

  const downloadPdf = async () => {
    if (!svgRef.current || !sheet) return;
    setDownloading(true);
    setDlError(null);
    try {
      // Measure the rendered SVG's viewBox so the PDF page size matches
      const vb = svgRef.current.viewBox.baseVal;
      const wPx = vb.width || svgRef.current.clientWidth || 1200;
      const hPx = vb.height || svgRef.current.clientHeight || 800;
      // Convert px → mm at 96 DPI ≈ 0.264583 mm/px
      const mm = (px: number) => Math.round(px * 0.2646);
      const pdf = new jsPDF({
        orientation: wPx >= hPx ? 'landscape' : 'portrait',
        unit: 'mm',
        format: [mm(wPx) + 20, mm(hPx) + 30],
      });

      // Title + footer before the SVG
      pdf.setFontSize(14);
      pdf.setTextColor(0, 0, 0);
      pdf.text(sheet.title, 10, 12);
      pdf.setFontSize(9);
      pdf.setTextColor(100, 100, 100);
      pdf.text(
        `Silicon to Software (S2S) — Schematic · ${sheet.components.length} components · ${sheet.nets.length} nets`,
        10, 18
      );

      await svg2pdf(svgRef.current, pdf, {
        x: 10, y: 22,
        width: mm(wPx), height: mm(hPx),
      });

      pdf.setFontSize(8);
      pdf.setTextColor(120, 120, 120);
      pdf.text('Generated by Silicon to Software (S2S) · DATA PATTERNS · CODE KNIGHTS', 10, mm(hPx) + 28);

      const safeTitle = (sheet.title || 'schematic').replace(/[^\w\-]+/g, '_').slice(0, 40);
      pdf.save(`${safeTitle}_${sheet.id}.pdf`);
    } catch (e: unknown) {
      setDlError(e instanceof Error ? e.message : String(e));
    } finally {
      setDownloading(false);
    }
  };

  // Loading / error states
  if (loading) {
    return (
      <div style={{ padding: 40, textAlign: 'center', color: 'var(--text3)' }}>
        <div style={{ width: 24, height: 24, margin: '0 auto 12px', borderRadius: '50%',
                      border: `3px solid ${color}`, borderTopColor: 'transparent',
                      animation: 'spin 0.8s linear infinite' }} />
        Loading schematic…
      </div>
    );
  }
  if (err) {
    return (
      <div style={{ padding: 40, textAlign: 'center', color: 'var(--text3)' }}>
        <div style={{ color: '#dc2626', fontSize: 13, marginBottom: 10 }}>Schematic unavailable</div>
        <div style={{ fontSize: 12, color: 'var(--text4)' }}>{err}</div>
        <div style={{ fontSize: 11, color: 'var(--text4)', marginTop: 16 }}>
          Run Phase 4 (Netlist Generation) first — the schematic is emitted alongside the netlist.
        </div>
      </div>
    );
  }
  if (!data || !sheet) return null;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', minHeight: 600 }}>
      {/* Toolbar: sheet tabs + download button */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '10px 14px', borderBottom: '1px solid var(--border2)',
        background: 'var(--panel2)', gap: 10,
      }}>
        {/* Sheet tabs */}
        <div style={{ display: 'flex', gap: 6, overflowX: 'auto' }}>
          {data.sheets.map((s, i) => (
            <button key={s.id} onClick={() => setSheetIdx(i)}
                    style={{
                      padding: '6px 12px',
                      fontSize: 11,
                      fontFamily: "'DM Mono', monospace",
                      letterSpacing: 0.5,
                      border: `1px solid ${i === sheetIdx ? color + '80' : 'var(--panel3)'}`,
                      background: i === sheetIdx ? `${color}20` : 'var(--panel)',
                      color: i === sheetIdx ? color : 'var(--text3)',
                      borderRadius: 5,
                      cursor: 'pointer',
                      whiteSpace: 'nowrap',
                      transition: 'all 0.15s',
                    }}>
              {s.title || s.id}
            </button>
          ))}
          {data.auto_synthesized && (
            <span style={{
              fontSize: 10, color: '#f59e0b',
              background: 'rgba(245,158,11,0.1)',
              border: '1px solid rgba(245,158,11,0.3)',
              borderRadius: 4,
              padding: '3px 8px',
              fontFamily: "'DM Mono', monospace",
              letterSpacing: 0.5,
              alignSelf: 'center',
            }}>AUTO-SYNTHESIZED</span>
          )}
        </div>

        {/* Right side: stats + PDF download */}
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <span style={{ fontSize: 10, color: 'var(--text4)', fontFamily: "'DM Mono', monospace" }}>
            {sheet.components.length} SYMBOLS · {sheet.nets.length} NETS
          </span>
          <button
            onClick={downloadPdf}
            disabled={downloading}
            style={{
              fontSize: 11,
              fontFamily: "'DM Mono', monospace",
              padding: '6px 14px',
              background: downloading ? 'rgba(245,158,11,0.2)' : 'rgba(245,158,11,0.1)',
              color: '#f59e0b',
              border: '1px solid rgba(245,158,11,0.4)',
              borderRadius: 5,
              cursor: downloading ? 'wait' : 'pointer',
              whiteSpace: 'nowrap',
              display: 'flex', alignItems: 'center', gap: 6,
              transition: 'all 0.15s',
            }}>
            {downloading ? (
              <><span style={{ width: 10, height: 10, borderRadius: '50%', border: '2px solid #f59e0b',
                               borderTopColor: 'transparent', animation: 'spin 0.7s linear infinite' }} />
                Exporting PDF…</>
            ) : '↓ Download PDF'}
          </button>
        </div>
      </div>
      {dlError && (
        <div style={{ padding: '6px 14px', background: 'rgba(220,38,38,0.08)',
                      color: '#dc2626', fontSize: 11, fontFamily: "'DM Mono', monospace" }}>
          ⚠ PDF export failed: {dlError}
        </div>
      )}

      {/* Main drawing area + net sidebar */}
      <div style={{ display: 'flex', flex: 1, minHeight: 0 }}>
        <div style={{ flex: 1, overflow: 'auto', background: '#070b14', minHeight: 600 }}>
          <div style={{ minWidth: '100%', minHeight: '100%' }}>
            <SheetSchematic
              ref={svgRef}
              sheet={sheet}
              hoveredNet={hoveredNet}
              onNetHover={setHoveredNet}
            />
          </div>
        </div>
        <NetSidebar sheet={sheet} hoveredNet={hoveredNet} onHover={setHoveredNet} />
      </div>
    </div>
  );
}

// ──────────────────────────────────────────────────────────────────────────────
// Sheet Index sidebar — shows all sheets in a compact left panel

function SheetIndex({ sheets, activeIdx, onSelect, color }: {
  sheets: SheetData[]; activeIdx: number;
  onSelect: (i: number) => void; color: string;
}) {
  // Count rules-engine components (bypass caps, pull-ups, ESD diodes)
  const rulesCount = (s: SheetData) =>
    s.components.filter(c =>
      c.ref.startsWith('C_BYP') || c.ref.startsWith('R_PU') || c.ref.startsWith('D_ESD')
    ).length;

  return (
    <aside style={{
      width: 190, borderRight: '1px solid var(--border2)',
      background: 'var(--panel)', overflowY: 'auto',
      padding: '10px 0',
      flexShrink: 0,
    }}>
      <div style={{
        fontSize: 9, color: 'var(--text4)', fontFamily: "'DM Mono', monospace",
        letterSpacing: 0.8, padding: '2px 12px 8px', borderBottom: '1px solid var(--border2)',
      }}>
        SHEETS ({sheets.length})
      </div>
      {sheets.map((s, i) => {
        const active = i === activeIdx;
        const rc = rulesCount(s);
        return (
          <button
            key={s.id}
            onClick={() => onSelect(i)}
            style={{
              display: 'block', width: '100%', textAlign: 'left',
              padding: '8px 12px', border: 'none',
              borderLeft: `3px solid ${active ? color : 'transparent'}`,
              background: active ? `${color}12` : 'transparent',
              cursor: 'pointer', transition: 'all 0.12s',
            }}
          >
            <div style={{
              fontSize: 11, fontFamily: "'DM Mono', monospace", fontWeight: active ? 600 : 400,
              color: active ? color : 'var(--text2)', marginBottom: 2,
              whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
            }}>
              {s.title || s.id}
            </div>
            <div style={{
              fontSize: 9, color: 'var(--text4)', fontFamily: "'JetBrains Mono', monospace",
            }}>
              {s.components.length} sym · {s.nets.length} nets
              {rc > 0 && (
                <span style={{ color: '#00c6a7', marginLeft: 4 }}>+{rc} auto</span>
              )}
            </div>
          </button>
        );
      })}
    </aside>
  );
}

// ──────────────────────────────────────────────────────────────────────────────

function NetSidebar({ sheet, hoveredNet, onHover }: {
  sheet: SheetData; hoveredNet: string | null; onHover: (n: string | null) => void;
}) {
  // Group nets by type, sort by name within group
  const grouped = useMemo(() => {
    const g: Record<string, NetData[]> = {};
    for (const n of sheet.nets) (g[n.type || 'signal'] ||= []).push(n);
    for (const k of Object.keys(g)) g[k].sort((a, b) => a.name.localeCompare(b.name));
    return g;
  }, [sheet.nets]);

  // Orphan pins — every pin on every component that doesn't appear in any net's endpoints
  const orphanPins = useMemo(() => {
    const connected = new Set<string>();
    for (const net of sheet.nets) for (const ep of net.endpoints) connected.add(`${ep.ref}.${ep.pin}`);
    const orphans: string[] = [];
    for (const c of sheet.components) {
      const pins = expectedPins(c);
      for (const p of pins) {
        if (!connected.has(`${c.ref}.${p}`)) orphans.push(`${c.ref}.${p}`);
      }
    }
    return orphans;
  }, [sheet.components, sheet.nets]);

  return (
    <aside style={{
      width: 280, borderLeft: '1px solid var(--border2)',
      background: 'var(--panel)', overflowY: 'auto',
      padding: '12px 14px',
    }}>
      <div style={{ fontSize: 10, color: 'var(--text4)', fontFamily: "'DM Mono', monospace",
                    letterSpacing: 0.8, marginBottom: 10 }}>
        NETS ({sheet.nets.length})
      </div>
      {Object.entries(grouped).map(([type, list]) => (
        <div key={type} style={{ marginBottom: 14 }}>
          <div style={{
            fontSize: 9, color: NET_COLORS[type] || NET_COLORS.default,
            fontFamily: "'DM Mono', monospace", letterSpacing: 0.6,
            textTransform: 'uppercase', marginBottom: 4,
          }}>
            {type} · {list.length}
          </div>
          {list.map(n => (
            <div
              key={n.name}
              onMouseEnter={() => onHover(n.name)}
              onMouseLeave={() => onHover(null)}
              style={{
                fontSize: 11, fontFamily: "'JetBrains Mono', monospace",
                padding: '4px 8px', marginLeft: 4,
                borderRadius: 3, cursor: 'pointer',
                background: hoveredNet === n.name ? `${NET_COLORS[type] || NET_COLORS.default}22` : 'transparent',
                color: hoveredNet === n.name ? '#e2e8f0' : 'var(--text3)',
                borderLeft: `2px solid ${hoveredNet === n.name ? (NET_COLORS[type] || NET_COLORS.default) : 'transparent'}`,
                transition: 'all 0.12s',
              }}>
              {n.name} <span style={{ color: 'var(--text4)' }}>· {n.endpoints.length} pins</span>
            </div>
          ))}
        </div>
      ))}

      {orphanPins.length > 0 && (
        <div style={{ marginTop: 20, padding: 10, borderRadius: 4,
                      background: 'rgba(220,38,38,0.08)', border: '1px solid rgba(220,38,38,0.25)' }}>
          <div style={{ fontSize: 10, color: '#dc2626', fontFamily: "'DM Mono', monospace",
                        letterSpacing: 0.6, marginBottom: 5 }}>
            ⚠ FLOATING PINS ({orphanPins.length})
          </div>
          <div style={{ fontSize: 10, color: 'var(--text4)', lineHeight: 1.4,
                        fontFamily: "'JetBrains Mono', monospace", maxHeight: 100, overflowY: 'auto' }}>
            {orphanPins.slice(0, 20).join(', ')}
            {orphanPins.length > 20 && ` … +${orphanPins.length - 20} more`}
          </div>
        </div>
      )}
    </aside>
  );
}

function expectedPins(c: ComponentData): string[] {
  if (c.type === 'ic' && c.pins) return c.pins.map(p => p.name);
  if (c.type === 'connector') {
    const n = parseInt((c.value || 'CON_2').replace(/\D+/g, ''), 10) || 2;
    return Array.from({ length: n }, (_, i) => String(i + 1));
  }
  if (['resistor', 'capacitor', 'capacitor_polar', 'inductor',
       'diode', 'diode_zener', 'diode_tvs', 'diode_led'].includes(c.type)) {
    return ['1', '2'];
  }
  if (c.type === 'ground' || c.type === 'vcc') return ['1'];
  return [];
}
