"""Communication-domain Round-1 elicitation questions."""

from domains._schema import Question

COMMUNICATION_QUESTIONS: list[Question] = [
    # Tier 1: Mandatory
    Question(id="comm.t1.freq_band", domain="communication", tier=1, category="RF Performance",
             text="Frequency band? (HF 1.5-30 MHz / VHF 30-300 / UHF 225-512 / L-band / S-band / custom)",
             expected_format="enum+MHz"),
    Question(id="comm.t1.radio_type", domain="communication", tier=1, category="Application",
             text="Radio type? (tactical handheld / manpack / vehicular / airborne / base station / SDR)",
             expected_format="enum"),
    Question(id="comm.t1.modulation", domain="communication", tier=1, category="Waveform",
             text="Modulation / waveform? (AM / FM / SSB / QAM / OFDM / SINCGARS / HAVEQUICK / Link-16 / SRW / WNW / custom)",
             expected_format="enum+list"),
    Question(id="comm.t1.channel_bw", domain="communication", tier=1, category="RF Performance",
             text="Channel bandwidth and channel spacing (kHz)?",
             expected_format="kHz"),
    Question(id="comm.t1.channels", domain="communication", tier=1, category="Architecture",
             text="Channel count? (single-channel / 2 / 4 / N simultaneous)",
             expected_format="int"),
    Question(id="comm.t1.sensitivity", domain="communication", tier=1, category="RF Performance",
             text="Receiver sensitivity / MDS (dBm) at specified BER or SINAD?",
             expected_format="dBm"),
    Question(id="comm.t1.tx_power", domain="communication", tier=1, category="RF Performance",
             text="Transmit output power (W or dBm)? PEP vs average if applicable.",
             expected_format="W or dBm"),
    Question(id="comm.t1.duplex", domain="communication", tier=1, category="Architecture",
             text="Duplex mode? (simplex / half-duplex / full-duplex FDD / TDD)",
             expected_format="enum"),
    # Tier 2: Frequency-hopping / crypto / SDR
    Question(id="comm.t2.freq_hopping", domain="communication", tier=2, category="Waveform",
             text="Frequency hopping required? Hop rate (hops/sec) and hopset size?",
             expected_format="hops/sec+count",
             triggers=["SINCGARS", "HAVEQUICK", "tactical"]),
    Question(id="comm.t2.crypto", domain="communication", tier=2, category="Security",
             text="Crypto integration? (Type-1 / Type-2 / Type-3 / commercial AES / NSA-certified module)",
             expected_format="enum",
             triggers=["tactical", "SINCGARS", "Link-16"]),
    Question(id="comm.t2.ref_accuracy", domain="communication", tier=2, category="Oscillator",
             text="Frequency reference accuracy (ppm) and type? (TCXO / OCXO / GPSDO / rubidium)",
             expected_format="ppm+type"),
    Question(id="comm.t2.phase_noise", domain="communication", tier=2, category="Oscillator",
             text="LO phase noise requirement? (dBc/Hz at offset) — important for narrow-channel or high-order modulation",
             expected_format="dBc/Hz @ offset"),
    Question(id="comm.t2.tuning_speed", domain="communication", tier=2, category="Synthesizer",
             text="Frequency tuning / switching speed requirement (microseconds)?",
             expected_format="us"),
    # Tier 1: Environment / Compliance
    Question(id="comm.t1.temp_range", domain="communication", tier=1, category="Environmental",
             text="Operating temperature range? (commercial / industrial / military -55 to +85)",
             expected_format="enum"),
    Question(id="comm.t1.standards", domain="communication", tier=1, category="Compliance",
             text="Required compliance? (MIL-STD-188-141 HF, 188-181/182 waveform, MIL-STD-461/810, FCC, ETSI, TIA)",
             expected_format="list"),
    Question(id="comm.t1.interop", domain="communication", tier=1, category="Interoperability",
             text="Waveform interop requirements? (JTRS / SCA 2.2.2 / ESSOR / coalition NATO STANAG)",
             expected_format="list"),
]
