"""Driver Generator - C/C++ code generation for hardware drivers.

Generates register-aware HAL code from the components and register map
extracted from GLR specification + RDT (Register Description Table).
"""

import logging
import re
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class DriverGenerator:
    """Generate C driver code from hardware specifications."""

    def generate(
        self,
        project_name: str,
        components: List[Dict],
        registers: List[Dict],
        metadata: Optional[Dict] = None,
        peripherals: Optional[List[Dict]] = None,
    ) -> Dict[str, str]:
        """
        Generate C HAL driver files.

        Args:
            project_name: Human-readable project name.
            components:   List of component dicts from _extract_components.
            registers:    List of register dicts from _extract_registers.
            metadata:     Optional dict with 'srs', 'sdd', 'rdt', 'psq' strings.
            peripherals:  Optional list of peripheral dicts from ProjectBrief
                          (each has `bus`, `name`, `address`). When provided,
                          the generator emits a per-peripheral HAL header
                          (hal_peripherals.h) with bus-specific stubs so the
                          generated code differs across projects with
                          different peripheral mixes.

        Returns:
            Dict mapping filename -> file content.
        """
        metadata = metadata or {}
        peripherals = peripherals or []
        rdt_text = metadata.get("rdt", "")
        psq_text = metadata.get("psq", "")

        # If register list is empty but RDT text is available, extract from text
        if not registers and rdt_text:
            registers = self._parse_registers_from_rdt(rdt_text)

        files = {
            "hal.h":      self._generate_header(project_name, registers, components),
            "hal.c":      self._generate_source(project_name, registers, components),
            "hal_regs.h": self._generate_regs_header(project_name, registers),
            "Makefile":   self._generate_makefile(project_name),
        }
        # Anti-genericity (2026-05-01): when ProjectBrief gave us a real
        # peripheral list, emit a header that names each one. Different
        # projects -> different files. Without this, every project gets
        # the same hal.h regardless of whether the design uses SPI, I2C,
        # GPIO, PWM, etc.
        if peripherals:
            files["hal_peripherals.h"] = self._generate_peripherals_header(
                project_name, peripherals,
            )
        return files

    # ------------------------------------------------------------------ #
    # hal_regs.h - register address / bit-field definitions
    # ------------------------------------------------------------------ #

    def _generate_regs_header(self, project_name: str, registers: List[Dict]) -> str:
        safe_name = project_name.replace(" ", "_").upper()
        guard = f"{safe_name}_HAL_REGS_H"

        lines = [
            f"/**",
            f" * @file hal_regs.h",
            f" * @brief Register address map for {project_name}",
            f" * @note  Auto-generated by Silicon to Software (S2S) v2 - do not edit manually.",
            f" */",
            "",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "",
            "/* ================================================================",
            f" * Register Address Map - {project_name}",
            " * 16-bit UART address: bit15=R/W#, bits[11:8]=BASE, bits[7:0]=OFFSET",
            " * ================================================================ */",
            "",
        ]

        if registers:
            for reg in registers:
                name    = reg.get("name", "REG").upper()
                address = reg.get("address", "0x0000")
                desc    = reg.get("description", "")
                access  = reg.get("access", "RW")
                width   = reg.get("width", 16)
                lines += [
                    f"/** @brief {desc} (access: {access}, {width}-bit) */",
                    f"#define REG_{name:<30s} ({address}U)",
                    "",
                ]
        else:
            # Fallback defaults when no registers were found
            defaults = [
                ("CTRL",        "0x0000", "Control register",      "RW"),
                ("STATUS",      "0x0001", "Status register",        "RO"),
                ("VERSION",     "0x0002", "Firmware version",       "RO"),
                ("SCRATCHPAD",  "0x0003", "Read-write test register","RW"),
                ("IRQ_MASK",    "0x0F00", "Interrupt mask",         "RW"),
                ("IRQ_STATUS",  "0x0F01", "Interrupt status (W1C)", "RC"),
            ]
            for name, addr, desc, access in defaults:
                lines += [
                    f"/** @brief {desc} (access: {access}) */",
                    f"#define REG_{name:<30s} ({addr}U)",
                    "",
                ]

        lines += [
            "/* Common bit-field masks */",
            "#define BIT(n)          (1U << (n))",
            "#define REG_RW_FLAG     BIT(15)   /**< Set in address for Read operations */",
            "",
            f"#endif /* {guard} */",
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # hal.h - public API
    # ------------------------------------------------------------------ #

    def _generate_header(
        self,
        project_name: str,
        registers: List[Dict],
        components: List[Dict],
    ) -> str:
        safe_name  = project_name.replace(" ", "_").lower()
        guard      = f"{safe_name}_HAL_H"
        comp_names = ", ".join(c.get("name", "") for c in components[:5]) if components else "N/A"

        lines = [
            f"/**",
            f" * @file hal.h",
            f" * @brief Hardware Abstraction Layer for {project_name}",
            f" * @details Components: {comp_names}",
            f" * @note  Auto-generated by Silicon to Software (S2S) v2",
            f" */",
            "",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            f'#include "hal_regs.h"',
            "",
            "/* ================================================================",
            " * Error codes",
            " * ================================================================ */",
            "typedef enum {",
            "    HAL_OK            =  0,   /**< Success */",
            "    HAL_ERROR         = -1,   /**< Generic error */",
            "    HAL_BUSY          = -2,   /**< Resource busy */",
            "    HAL_TIMEOUT       = -3,   /**< Operation timed out */",
            "    HAL_INVALID_PARAM = -4,   /**< Invalid parameter */",
            "    HAL_NOT_INIT      = -5,   /**< HAL not initialised */",
            "    HAL_NOT_IMPL      = -6,   /**< BSP stub not implemented for this target */",
            "} hal_status_t;",
            "",
            "/* ================================================================",
            " * Configuration",
            " * ================================================================ */",
            "typedef struct {",
            "    uint32_t clock_hz;        /**< System clock frequency in Hz */",
            "    uint32_t baud_rate;       /**< UART baud rate */",
            "    uint32_t timeout_ms;      /**< Default operation timeout (ms) */",
            "} hal_config_t;",
            "",
            "/* ================================================================",
            " * Register I/O primitives",
            " * ================================================================ */",
            "",
            "/**",
            " * @brief  Write a 16-bit value to a device register via UART.",
            " * @param  addr   Register address (16-bit, bit15=0 for write).",
            " * @param  value  Value to write.",
            " * @return HAL_OK on success.",
            " */",
            "hal_status_t hal_reg_write(uint16_t addr, uint16_t value);",
            "",
            "/**",
            " * @brief  Read a 16-bit value from a device register via UART.",
            " * @param  addr   Register address (16-bit, bit15=1 for read).",
            " * @param  value  Pointer to store the read value.",
            " * @return HAL_OK on success.",
            " */",
            "hal_status_t hal_reg_read(uint16_t addr, uint16_t *value);",
            "",
            "/* ================================================================",
            " * Lifecycle",
            " * ================================================================ */",
            "hal_status_t hal_init(const hal_config_t *cfg);",
            "hal_status_t hal_deinit(void);",
            "bool         hal_is_ready(void);",
            "",
            "/* ================================================================",
            " * High-level helpers",
            " * ================================================================ */",
            "",
        ]

        # Generate a typed accessor per named register
        if registers:
            for reg in registers:
                name   = reg.get("name", "REG").lower()
                access = reg.get("access", "RW")
                desc   = reg.get("description", "")
                if "R" in access.upper():
                    lines += [
                        f"/** @brief Read {desc} */",
                        f"hal_status_t hal_read_{name}(uint16_t *out);",
                        "",
                    ]
                if "W" in access.upper() or "RW" in access.upper():
                    lines += [
                        f"/** @brief Write {desc} */",
                        f"hal_status_t hal_write_{name}(uint16_t value);",
                        "",
                    ]

        lines += [f"#endif /* {guard} */"]
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # hal.c - implementation
    # ------------------------------------------------------------------ #

    def _generate_source(
        self,
        project_name: str,
        registers: List[Dict],
        components: List[Dict],
    ) -> str:
        safe_name = project_name.replace(" ", "_").lower()

        lines = [
            f"/**",
            f" * @file hal.c",
            f" * @brief Hardware Abstraction Layer implementation for {project_name}",
            f" * @note  Auto-generated by Silicon to Software (S2S) v2",
            f" */",
            "",
            '#include "hal.h"',
            "#include <string.h>",
            "",
            "/* ================================================================",
            " * Private state",
            " * ================================================================ */",
            "static hal_config_t s_cfg    = {0U};",
            "static bool         s_ready  = false;",
            "",
            "/* ================================================================",
            " * Forward declarations (platform-specific - implement per BSP)",
            " * ================================================================ */",
            "static hal_status_t _uart_write_bytes(const uint8_t *buf, uint16_t len);",
            "static hal_status_t _uart_read_bytes (uint8_t *buf, uint16_t len, uint32_t timeout_ms);",
            "",
            "/* ================================================================",
            " * Register I/O",
            " * ================================================================ */",
            "",
            "hal_status_t hal_reg_write(uint16_t addr, uint16_t value)",
            "{",
            "    if (!s_ready) { return HAL_NOT_INIT; }",
            "    /* UART write frame: [0x57 'W'] [ADDR_MSB] [ADDR_LSB] [DATA_MSB] [DATA_LSB] */",
            "    uint8_t frame[5];",
            "    frame[0] = 0x57U;                          /* 'W' command byte   */",
            "    frame[1] = (uint8_t)((addr  >> 8U) & 0x7FU); /* MSB, bit15=0 write */",
            "    frame[2] = (uint8_t)(addr  & 0xFFU);",
            "    frame[3] = (uint8_t)((value >> 8U) & 0xFFU);",
            "    frame[4] = (uint8_t)(value & 0xFFU);",
            "    return _uart_write_bytes(frame, 5U);",
            "}",
            "",
            "hal_status_t hal_reg_read(uint16_t addr, uint16_t *value)",
            "{",
            "    hal_status_t status;",
            "    uint8_t rx[2];",
            "    uint8_t frame[3];",
            "    if (!s_ready)  { return HAL_NOT_INIT; }",
            "    if (value == NULL) { return HAL_INVALID_PARAM; }",
            "    /* UART read frame: [0x52 'R'] [ADDR_MSB|0x80] [ADDR_LSB] */",
            "    frame[0] = 0x52U;                          /* 'R' command byte   */",
            "    frame[1] = (uint8_t)((addr >> 8U) | 0x80U); /* MSB, bit15=1 read  */",
            "    frame[2] = (uint8_t)(addr & 0xFFU);",
            "    status = _uart_write_bytes(frame, 3U);",
            "    if (status != HAL_OK) { return status; }",
            "    status = _uart_read_bytes(rx, 2U, s_cfg.timeout_ms);",
            "    if (status != HAL_OK) { return status; }",
            "    *value = (uint16_t)(((uint16_t)rx[0] << 8U) | (uint16_t)rx[1]);",
            "    return HAL_OK;",
            "}",
            "",
            "/* ================================================================",
            " * Lifecycle",
            " * ================================================================ */",
            "",
            "hal_status_t hal_init(const hal_config_t *cfg)",
            "{",
            "    hal_status_t status;",
            "    uint16_t     scratch_rb;",
            "    if (cfg == NULL) { return HAL_INVALID_PARAM; }",
            "    if (s_ready)     { return HAL_OK; }            /* Idempotent */",
            "    (void)memcpy(&s_cfg, cfg, sizeof(hal_config_t));",
            "    s_ready = true;",
            "    /* Verify register bus: write SCRATCHPAD, read back */",
            "    status = hal_reg_write(REG_SCRATCHPAD, 0xA55AU);",
            "    if (status != HAL_OK) { s_ready = false; return status; }",
            "    status = hal_reg_read((uint16_t)(REG_SCRATCHPAD | 0x8000U), &scratch_rb);",
            "    if (status != HAL_OK) { s_ready = false; return status; }",
            "    if (scratch_rb != 0xA55AU) { s_ready = false; return HAL_ERROR; }",
            "    return HAL_OK;",
            "}",
            "",
            "hal_status_t hal_deinit(void)",
            "{",
            "    s_ready = false;",
            "    (void)memset(&s_cfg, 0, sizeof(hal_config_t));",
            "    return HAL_OK;",
            "}",
            "",
            "bool hal_is_ready(void)",
            "{",
            "    return s_ready;",
            "}",
            "",
            "/* ================================================================",
            " * High-level register accessors (auto-generated from RDT)",
            " * ================================================================ */",
            "",
        ]

        # Generate typed accessor implementations per register
        if registers:
            for reg in registers:
                name   = reg.get("name", "REG").lower()
                addr   = reg.get("address", "0x0000")
                access = reg.get("access", "RW")

                if "R" in access.upper():
                    lines += [
                        f"hal_status_t hal_read_{name}(uint16_t *out)",
                        "{",
                        f"    return hal_reg_read((uint16_t)({addr}U | 0x8000U), out);",
                        "}",
                        "",
                    ]
                if "W" in access.upper() or "RW" in access.upper():
                    lines += [
                        f"hal_status_t hal_write_{name}(uint16_t value)",
                        "{",
                        f"    return hal_reg_write((uint16_t)({addr}U & 0x7FFFU), value);",
                        "}",
                        "",
                    ]

        # BSP stubs
        lines += [
            "/* ================================================================",
            " * BSP stubs - implement these for your target platform",
            " * ================================================================ */",
            "",
            "/**",
            " * BSP CONTRACT - YOU MUST IMPLEMENT THESE FUNCTIONS",
            " *",
            " * The HAL drives the device through a 16-bit UART register",
            " * protocol; see hal_regs.h for the byte framing. These two",
            " * stubs are the only places where the HAL talks to your",
            " * specific MCU UART peripheral.",
            " *",
            " * Required behaviour:",
            " *   _uart_write_bytes:",
            " *     Transmit `len` bytes from `buf`. Block until the bytes",
            " *     are queued (or sent, if your driver is synchronous).",
            " *     Return HAL_OK on success, HAL_TIMEOUT on TX-FIFO full,",
            " *     HAL_ERROR on any other peripheral error.",
            " *",
            " *   _uart_read_bytes:",
            " *     Read exactly `len` bytes into `buf`, or return",
            " *     HAL_TIMEOUT after `timeout_ms` milliseconds. Return",
            " *     HAL_INVALID_PARAM if buf == NULL or len == 0.",
            " *",
            " * Until you replace HAL_NOT_IMPL with a real implementation,",
            " * every hal_init() / hal_read_*/hal_write_* call will fail,",
            " * which is the safe default - silent HAL_OK would let",
            " * production firmware ship without a working UART driver.",
            " */",
            "static hal_status_t _uart_write_bytes(const uint8_t *buf, uint16_t len)",
            "{",
            "    (void)buf; (void)len;",
            "    return HAL_NOT_IMPL;",
            "}",
            "",
            "static hal_status_t _uart_read_bytes(uint8_t *buf, uint16_t len, uint32_t timeout_ms)",
            "{",
            "    (void)buf; (void)len; (void)timeout_ms;",
            "    return HAL_NOT_IMPL;",
            "}",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # Makefile
    # ------------------------------------------------------------------ #

    def _generate_makefile(self, project_name: str) -> str:
        target = project_name.replace(" ", "_").lower()
        return f"""# Makefile for {project_name}
# Generated by Silicon to Software (S2S) v2

CC      = gcc
CFLAGS  = -Wall -Wextra -Wpedantic -O2 -std=c11 -Isrc
LDFLAGS =

SRCDIR  = src
OBJDIR  = obj
SOURCES = $(wildcard $(SRCDIR)/*.c)
OBJECTS = $(SOURCES:$(SRCDIR)/%.c=$(OBJDIR)/%.o)
TARGET  = {target}_driver

.PHONY: all clean cppcheck

all: $(TARGET)

$(TARGET): $(OBJECTS)
\t$(CC) $(LDFLAGS) -o $@ $^

$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)
\t$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR):
\tmkdir -p $(OBJDIR)

cppcheck:
\tcppcheck --enable=all --std=c11 --suppress=missingIncludeSystem \\
\t         --error-exitcode=1 $(SRCDIR)/

clean:
\trm -rf $(OBJDIR) $(TARGET)
"""

    # ------------------------------------------------------------------ #
    # Save
    # ------------------------------------------------------------------ #

    # ------------------------------------------------------------------ #
    # hal_peripherals.h - per-peripheral HAL stubs (anti-genericity)
    # ------------------------------------------------------------------ #
    def _generate_peripherals_header(
        self, project_name: str, peripherals: List[Dict],
    ) -> str:
        """Emit a header declaring one HAL block per peripheral the project
        actually uses. The function names embed both the bus and the
        peripheral name so two projects with different mixes produce
        textually different headers.

        Each `peripherals[i]` is expected to have keys `bus`, `name`,
        `address` (matching schemas/project_brief.Peripheral). Unknown
        buses still get a generic stub so a partially-extracted brief
        doesn't silently drop peripherals.
        """
        import re as _re
        _ident = _re.sub(r"[^A-Za-z0-9_]+", "_", project_name.upper()).strip("_") or "PROJECT"
        guard = f"HAL_PERIPHERALS_{_ident}_H_"
        lines = [
            "/* SPDX-License-Identifier: MIT",
            f" * Auto-generated peripheral HAL header for {project_name}.",
            " * One declaration block per peripheral discovered in the",
            " * ProjectBrief. Implementations live in hal_peripherals.c",
            " * (BSP-specific) - replace HAL_NOT_IMPL there with your",
            " * MCU's peripheral driver calls.",
            " */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include \"hal.h\"",
            "",
        ]
        # Per-bus emitter table - keep generators tiny + composable.
        def _spi(p):
            slug = self._slug(p.get("name", "spi"))
            return [
                f"/* SPI: {p.get('name','?')} (slave-select #{p.get('address','0')}) */",
                f"hal_status_t hal_{slug}_init(void);",
                f"hal_status_t hal_{slug}_xfer(const uint8_t *tx, uint8_t *rx, uint16_t n);",
                "",
            ]
        def _i2c(p):
            slug = self._slug(p.get("name", "i2c"))
            return [
                f"/* I2C: {p.get('name','?')} (addr {p.get('address','0x00')}) */",
                f"hal_status_t hal_{slug}_init(void);",
                f"hal_status_t hal_{slug}_write(const uint8_t *buf, uint16_t n);",
                f"hal_status_t hal_{slug}_read(uint8_t *buf, uint16_t n);",
                "",
            ]
        def _uart(p):
            slug = self._slug(p.get("name", "uart"))
            return [
                f"/* UART: {p.get('name','?')} */",
                f"hal_status_t hal_{slug}_init(uint32_t baud);",
                f"hal_status_t hal_{slug}_send(const uint8_t *buf, uint16_t n);",
                f"hal_status_t hal_{slug}_recv(uint8_t *buf, uint16_t n, uint32_t timeout_ms);",
                "",
            ]
        def _gpio(p):
            slug = self._slug(p.get("name", "gpio"))
            return [
                f"/* GPIO: {p.get('name','?')} */",
                f"hal_status_t hal_{slug}_set(uint8_t pin, uint8_t level);",
                f"hal_status_t hal_{slug}_get(uint8_t pin, uint8_t *level);",
                "",
            ]
        def _pwm(p):
            slug = self._slug(p.get("name", "pwm"))
            return [
                f"/* PWM: {p.get('name','?')} */",
                f"hal_status_t hal_{slug}_init(uint32_t freq_hz);",
                f"hal_status_t hal_{slug}_set_duty(uint16_t duty_q15);",
                "",
            ]
        def _adc(p):
            slug = self._slug(p.get("name", "adc"))
            return [
                f"/* ADC: {p.get('name','?')} */",
                f"hal_status_t hal_{slug}_start(void);",
                f"hal_status_t hal_{slug}_read(uint16_t *sample);",
                "",
            ]
        def _dac(p):
            slug = self._slug(p.get("name", "dac"))
            return [
                f"/* DAC: {p.get('name','?')} */",
                f"hal_status_t hal_{slug}_write(uint16_t code);",
                "",
            ]
        def _generic(p):
            slug = self._slug(p.get("name","peripheral"))
            return [
                f"/* {p.get('bus','?').upper()}: {p.get('name','?')} */",
                f"hal_status_t hal_{slug}_init(void);",
                "",
            ]
        emitters = {
            "spi":  _spi, "i2c": _i2c, "uart": _uart, "gpio": _gpio,
            "pwm":  _pwm, "adc": _adc, "dac": _dac,
        }
        # HAL_PERIPHERALS_X_LIST macro lists every peripheral the project
        # exposes - users can iterate it for diagnostics / boot-time init.
        list_macro = (
            "/* Bus, slug, name. Iterate for boot init / diagnostics. */\n"
            "#define HAL_PERIPHERALS_LIST(X) \\\n"
        )
        macro_rows = []
        for p in peripherals:
            bus = (p.get("bus") or "generic").lower()
            slug = self._slug(p.get("name", bus))
            macro_rows.append(
                f"    X({bus.upper()}, {slug}, \"{p.get('name','?')}\")"
            )
        list_macro += " \\\n".join(macro_rows) if macro_rows else "    /* no peripherals */"
        lines.append(list_macro)
        lines.append("")
        # Per-peripheral declarations.
        for p in peripherals:
            bus = (p.get("bus") or "generic").lower()
            lines.extend(emitters.get(bus, _generic)(p))
        lines.append(f"#endif /* {guard} */")
        return chr(10).join(lines)

    @staticmethod
    def _slug(s: str) -> str:
        import re as _re
        out = _re.sub(r"[^A-Za-z0-9]+", "_", str(s or "x")).strip("_").lower()
        return out or "x"

    def save(self, files: Dict[str, str], output_dir: Path) -> List[Path]:
        output_dir = Path(output_dir)
        src_dir    = output_dir / "src"
        src_dir.mkdir(parents=True, exist_ok=True)

        saved = []
        for filename, content in files.items():
            filepath = output_dir / filename if filename == "Makefile" else src_dir / filename
            filepath.write_text(content, encoding="utf-8")
            saved.append(filepath)
        return saved

    # ------------------------------------------------------------------ #
    # Internal helpers
    # ------------------------------------------------------------------ #

    def _parse_registers_from_rdt(self, rdt_text: str) -> List[Dict]:
        """Parse a basic register list from RDT markdown text."""
        registers = []
        # Match table rows: | `NAME` | `0x0000` | ...
        pattern = re.compile(
            r"\|\s*`([A-Z_][A-Z0-9_]*)`\s*\|\s*`(0x[0-9A-Fa-f]+)`\s*\|"
            r"[^|]*\|[^|]*\|\s*([^|]+?)\s*\|"
        )
        seen = set()
        for m in pattern.finditer(rdt_text):
            name, addr, desc = m.group(1), m.group(2), m.group(3).strip()
            if name not in seen:
                seen.add(name)
                # Infer access type from description
                access = "RO" if "read-only" in desc.lower() or " ro" in desc.lower() else \
                         "RC" if "read-clear" in desc.lower() or " rc" in desc.lower() else "RW"
                registers.append({
                    "name":        name,
                    "address":     addr,
                    "access":      access,
                    "width":       16,
                    "description": desc[:80],
                })
        return registers

    def _default_components(self) -> List[Dict]:
        return [
            {"name": "MCU",  "type": "Microcontroller", "description": "Main processor"},
            {"name": "FPGA", "type": "Programmable logic", "description": "Glue logic device"},
        ]

    def _default_registers(self) -> List[Dict]:
        return [
            {"name": "CTRL",       "address": "0x0000", "access": "RW", "width": 16, "description": "Control register"},
            {"name": "STATUS",     "address": "0x0001", "access": "RO", "width": 16, "description": "Status register"},
            {"name": "VERSION",    "address": "0x0002", "access": "RO", "width": 16, "description": "Firmware version"},
            {"name": "SCRATCHPAD", "address": "0x0003", "access": "RW", "width": 16, "description": "R/W test register"},
            {"name": "IRQ_MASK",   "address": "0x0F00", "access": "RW", "width": 16, "description": "Interrupt mask"},
            {"name": "IRQ_STATUS", "address": "0x0F01", "access": "RC", "width": 16, "description": "Interrupt status (W1C)"},
        ]
