"""
Phase 7: FPGA Design Agent

AI-powered RTL code generation from GLR specification + Register Map.
Generates synthesisable Verilog HDL, testbench, and Vivado timing constraints.

Outputs:
  - fpga_top.v              — Top-level Verilog module (glue logic + state machines)
  - fpga_testbench.v        — Self-checking SystemVerilog testbench
  - constraints.xdc         — Vivado XDC timing & I/O constraints
  - fpga_design_report.md   — Design summary (resource estimate, FSM diagram, timing)

P26 #8 (2026-04-25): refactored to PARALLEL sub-calls.
Previously a single LLM call returned ALL 4 outputs in one ~16K-token
response, taking 5-12 minutes (LLM generates ~50 tokens/s). Now we
split into 1 fast metadata call + 4 parallel content calls (one per
output file). Wall-time drops from ~10 min to ~1.5 min while keeping
the outputs consistent (all 4 content calls see the SAME metadata —
module name, port list, clock freq — so the testbench instantiates
the right module, the XDC pins match the Verilog ports, etc.).
"""

import asyncio
import logging
import re
from pathlib import Path
from typing import Dict

from agents.base_agent import BaseAgent
from agents import rtl_tailored
from config import settings
from services.project_brief_builder import build_project_brief

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# P7 polish helpers (2026-05-01) - SPDX/Doxygen headers + cross-validation.
# ---------------------------------------------------------------------------

def _make_doxygen_header(
    *, filename: str, brief: str, project_name: str, module_name: str,
    clock_mhz, comment_token: str = "//",
) -> str:
    """Build a 7-line SPDX + Doxygen banner for generated HDL/XDC files."""
    c = comment_token
    lines = [
        f"{c} SPDX-License-Identifier: MIT",
        f"{c} SPDX-FileCopyrightText: Auto-generated by Silicon to Software (S2S) v2",
        f"{c} @file        {filename}",
        f"{c} @brief       {brief}",
        f"{c} @project     {project_name}",
        f"{c} @module      {module_name}",
        f"{c} @clock       {clock_mhz} MHz",
        "",
    ]
    return chr(10).join(lines) + chr(10)


def _validate_port_consistency(
    verilog_top: str, testbench: str, xdc: str,
) -> list[str]:
    """Return a list of human-readable warnings if port names diverge
    between the three RTL artifacts. Empty list = consistent.

    The check is pragmatic: we extract identifier-shaped tokens from the
    Verilog `module ... ( ... );` port block, then verify each one
    appears in both the testbench (used as a wire/reg) and the XDC
    (referenced via `get_ports`). Surface-only - a missing match could
    legitimately be due to renamed buses, but it always deserves a glance.
    """
    import re as _re
    warnings: list[str] = []
    m = _re.search(r"module\s+\w+\s*\(([^)]+)\);", verilog_top, _re.DOTALL)
    if not m:
        return warnings
    port_block = m.group(1)
    # Pull bare identifiers that look like port names (after direction kw).
    port_names = set()
    for line in port_block.splitlines():
        line = line.split("//", 1)[0].strip().strip(",")
        if not line:
            continue
        toks = _re.findall(r"[a-zA-Z_]\w*", line)
        # Skip leading direction / type words.
        for kw in ("input", "output", "inout", "wire", "reg", "logic"):
            while toks and toks[0] == kw:
                toks.pop(0)
        # The last identifier on the line is the port name (after width).
        if toks:
            port_names.add(toks[-1])

    for p in port_names:
        if testbench and p not in testbench:
            warnings.append(
                f"port `{p}` declared in fpga_top.v but not referenced in testbench"
            )
        if xdc and p not in xdc:
            # Only a subset of ports get pin constraints; flag only when XDC
            # has any get_ports references at all (avoids spurious warnings
            # on a XDC that's pure timing without pin assignments).
            if "get_ports" in xdc:
                warnings.append(
                    f"port `{p}` not referenced in constraints.xdc (get_ports)"
                )
    return warnings


# ---------------------------------------------------------------------------
# Tool definition
# ---------------------------------------------------------------------------

GENERATE_FPGA_TOOL = {
    "name": "generate_fpga_design",
    "description": (
        "Generate a complete FPGA RTL design: Verilog top module, testbench, "
        "XDC constraints, and design report."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "module_name": {
                "type": "string",
                "description": "Top-level Verilog module name (e.g. bldc_glue_logic)",
            },
            "clock_frequency_mhz": {
                "type": "number",
                "description": "Target clock frequency in MHz (e.g. 100.0)",
            },
            "fpga_part": {
                "type": "string",
                "description": "Xilinx part number (e.g. xc7a35tcpg236-1)",
            },
            "ports": {
                "type": "array",
                "description": "Top-level I/O ports",
                "items": {
                    "type": "object",
                    "properties": {
                        "name":        {"type": "string"},
                        "direction":   {"type": "string", "description": "input / output / inout"},
                        "width":       {"type": "integer", "description": "Bus width (1 for scalar)"},
                        "description": {"type": "string"},
                    },
                    "required": ["name", "direction", "width"],
                },
            },
            "state_machines": {
                "type": "array",
                "description": "FSMs to implement",
                "items": {
                    "type": "object",
                    "properties": {
                        "name":   {"type": "string"},
                        "states": {"type": "array", "items": {"type": "string"}},
                        "description": {"type": "string"},
                    },
                    "required": ["name", "states"],
                },
            },
            "verilog_top": {
                "type": "string",
                "description": "Complete synthesisable Verilog source for fpga_top.v",
            },
            "testbench": {
                "type": "string",
                "description": "Complete SystemVerilog testbench for fpga_testbench.v",
            },
            "xdc_constraints": {
                "type": "string",
                "description": "Complete Vivado XDC file content",
            },
            "design_summary": {
                "type": "string",
                "description": "Human-readable design summary (resource estimate, key decisions)",
            },
            "lut_estimate": {"type": "integer", "description": "Estimated LUT count"},
            "ff_estimate":  {"type": "integer", "description": "Estimated flip-flop count"},
        },
        "required": [
            "module_name", "clock_frequency_mhz", "fpga_part",
            "ports", "verilog_top", "testbench", "xdc_constraints", "design_summary",
        ],
    },
}

# ---------------------------------------------------------------------------
# P26 #8 (2026-04-25) — split tools for parallel sub-call generation.
# Each tool produces ONE output file. They all share the same metadata
# (module name, ports, clock freq) which is generated upfront in a small
# fast call so the parallel content generators stay consistent.
# ---------------------------------------------------------------------------

GENERATE_FPGA_METADATA_TOOL = {
    "name": "generate_fpga_metadata",
    "description": (
        "Step 1 of FPGA generation: emit ONLY the design metadata "
        "(module name, clock, FPGA part, port list, FSMs, resource "
        "estimate). Subsequent parallel calls will generate the "
        "Verilog/testbench/XDC/summary files using THIS metadata as "
        "the consistency contract — keep names and bit-widths short "
        "and final, no inventing them later."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "module_name":           {"type": "string"},
            "clock_frequency_mhz":   {"type": "number"},
            "fpga_part":             {"type": "string"},
            "ports": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name":        {"type": "string"},
                        "direction":   {"type": "string"},
                        "width":       {"type": "integer"},
                        "description": {"type": "string"},
                    },
                    "required": ["name", "direction", "width"],
                },
            },
            "state_machines": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name":        {"type": "string"},
                        "states":      {"type": "array", "items": {"type": "string"}},
                        "description": {"type": "string"},
                    },
                    "required": ["name", "states"],
                },
            },
            "lut_estimate": {"type": "integer"},
            "ff_estimate":  {"type": "integer"},
        },
        "required": [
            "module_name", "clock_frequency_mhz", "fpga_part", "ports",
        ],
    },
}

GENERATE_VERILOG_TOOL = {
    "name": "generate_verilog_top",
    "description": (
        "Step 2a: emit the COMPLETE synthesisable Verilog top module "
        "(`fpga_top.v`) using the metadata established in Step 1. "
        "Module name, port list, clock freq MUST match the metadata "
        "exactly — testbench / XDC files are being generated in "
        "parallel with the same metadata and any divergence breaks "
        "the design."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "verilog_top": {
                "type": "string",
                "description": "Complete synthesisable Verilog source.",
            },
        },
        "required": ["verilog_top"],
    },
}

GENERATE_TESTBENCH_TOOL = {
    "name": "generate_testbench",
    "description": (
        "Step 2b: emit the COMPLETE SystemVerilog testbench "
        "(`fpga_testbench.v`) for the module described in the "
        "metadata. The DUT instantiation MUST use the metadata's "
        "module name and port list."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "testbench": {
                "type": "string",
                "description": "Complete SystemVerilog testbench source.",
            },
        },
        "required": ["testbench"],
    },
}

GENERATE_XDC_TOOL = {
    "name": "generate_xdc_constraints",
    "description": (
        "Step 2c: emit the COMPLETE Vivado XDC file content. Pin "
        "assignments MUST reference the metadata's port names "
        "exactly. Clock constraints MUST use the metadata's clock "
        "frequency."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "xdc_constraints": {
                "type": "string",
                "description": "Complete Vivado XDC file content.",
            },
        },
        "required": ["xdc_constraints"],
    },
}

GENERATE_SUMMARY_TOOL = {
    "name": "generate_design_summary",
    "description": (
        "Step 2d: emit a human-readable design summary covering the "
        "Verilog/testbench/XDC files generated in Steps 2a/2b/2c. "
        "Include resource estimate, key design decisions, FSM "
        "encoding choices, timing closure notes."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "design_summary": {
                "type": "string",
                "description": "Human-readable design summary (markdown OK).",
            },
        },
        "required": ["design_summary"],
    },
}

# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are a senior FPGA/RTL design engineer with 20+ years experience in
synthesisable Verilog/VHDL for Xilinx devices (Artix-7, Kintex-7, UltraScale).

## YOUR TASK
Given a GLR (Glue Logic Requirements) specification and optional register map, generate:

### 1. Top-Level Verilog Module (`fpga_top.v`)
Requirements:
- Synthesisable Verilog-2001 / SystemVerilog for Xilinx Vivado
- Clock domain crossing handled with synchronisers (2-FF for control, FIFO for data)
- All FSMs: binary encoding with default state, one-hot optional with `(* fsm_encoding = "one_hot" *)`
- No latches — all `always` blocks must have complete sensitivity lists or be `always_ff`
- Reset: active-low synchronous reset (`rst_n`)
- Register access layer: 16-bit UART address/data bus matching the RDT address map (if provided)
- MISRA-equivalent rules: no implicit casts, explicit bit-widths, no unbounded loops
- Doxygen-style module header comment
- All outputs registered (no combinatorial outputs directly from `assign`)

### 2. Testbench (`fpga_testbench.v`)
- SystemVerilog testbench with `timescale 1ns/1ps`
- Clock generation task (50 MHz default — adjustable via parameter)
- Reset assertion + release sequence
- Cover all FSM transitions with `$display` pass/fail messages
- Register write/read verification over UART bus
- Final `$display("TESTBENCH: ALL TESTS PASSED")` on success

### 3. XDC Constraints (`constraints.xdc`)
- `create_clock` for the primary clock port
- `set_input_delay` / `set_output_delay` for all I/O (10 ns default)
- `set_false_path` for asynchronous resets and static config signals
- FPGA part: derive from GLR or use `xc7a35tcpg236-1` (Artix-7 35T) as default
- Pin assignments: use `set_property PACKAGE_PIN` for clk and rst_n at minimum

### 4. Design Report
- Table of ports with direction, width, and purpose
- FSM state diagram in Mermaid syntax
- Resource estimate: LUT count, FF count, BRAM, DSP
- Key design decisions and trade-offs

## CODING STANDARDS
- Indent: 4 spaces (no tabs)
- Line length: max 100 chars
- Parameter names: ALL_CAPS_WITH_UNDERSCORES
- Port names: snake_case
- Registers: `_r` suffix (e.g. `state_r`, `data_out_r`)
- Constants: `localparam` (not `define`)
- No `initial` blocks in synthesisable code (only in testbenches)
- Every `always` block must cover all states / conditions to avoid latches
- Minimum 25 ports, 2 FSMs, full register bus interface

## REGISTER BUS (if RDT available)
Implement a 16-bit UART register interface:
- `reg_addr[15:0]` — address (bit15=R/W#, bits11:8=base, bits7:0=offset)
- `reg_wdata[15:0]` — write data
- `reg_rdata[15:0]` — read data
- `reg_wr`, `reg_rd` — strobes
- Registers: at minimum CTRL, STATUS, VERSION, SCRATCH, IRQ_MASK, IRQ_STATUS

Use the `generate_fpga_design` tool to return all output files.
"""


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

class FpgaAgent(BaseAgent):
    """Phase 7: AI-powered FPGA RTL design generation."""

    def __init__(self):
        super().__init__(
            phase_number="P7",
            phase_name="FPGA Design",
            model=settings.primary_model,
            # P26 #8 — tools list now includes ALL split tools so the LLM
            # can call them. The legacy `generate_fpga_design` is kept as
            # a fallback path (used when the metadata sub-call returns
            # `degraded` from the LLM chain — see `execute()`).
            tools=[
                GENERATE_FPGA_METADATA_TOOL,
                GENERATE_VERILOG_TOOL,
                GENERATE_TESTBENCH_TOOL,
                GENERATE_XDC_TOOL,
                GENERATE_SUMMARY_TOOL,
                GENERATE_FPGA_TOOL,
            ],
            max_tokens=16384,
        )

    def get_system_prompt(self, project_context: dict) -> str:
        # Prepend the ProjectBrief preamble (built at the top of execute()).
        # This is the single point where every LLM call - metadata pass and
        # the four parallel content passes - gets primed with project
        # specifics. If the brief failed to build we degrade silently to
        # the unconditioned SYSTEM_PROMPT.
        preamble = getattr(self, "_brief_preamble", "") or ""
        if preamble:
            return preamble + "\n\n" + SYSTEM_PROMPT
        return SYSTEM_PROMPT

    async def execute(self, project_context: dict, user_input: str) -> dict:
        output_dir = Path(project_context.get("output_dir", "output"))
        output_dir.mkdir(parents=True, exist_ok=True)
        project_name = project_context.get("name", "Project")
        safe_name = project_name.replace(" ", "_")

        # P7 anti-genericity (2026-05-01): build a ProjectBrief and stash
        # its preamble so the metadata + every parallel sub-call sees the
        # project's frequency / peripherals / register map / FSMs / HDL
        # language. Without this, the LLM truncates upstream markdown and
        # falls back on its priors -> identical CTRL/STATUS/VERSION skeleton
        # across every project.
        try:
            self._brief = build_project_brief(
                project_id=int(project_context.get("project_id") or 0),
                project_name=project_name,
                output_dir=str(output_dir),
                project_type=str(project_context.get("project_type") or "receiver"),
                design_scope=str(project_context.get("design_scope") or "full"),
                application_class=str(
                    (project_context.get("design_parameters") or {}).get("application_class")
                    or (project_context.get("design_parameters") or {}).get("application")
                    or "general"
                ),
                hdl_language=str(
                    (project_context.get("design_parameters") or {}).get("hdl_language")
                    or "verilog"
                ),
            )
            self._brief_preamble = self._brief.to_prompt_preamble()
        except Exception as _brief_err:
            logger.warning("project_brief.build_failed: %s", _brief_err)
            self._brief = None
            self._brief_preamble = ""

        # Load prior phase outputs
        glr_spec = self._load_file(output_dir / f"GLR_{safe_name}.md")
        glr_generic = self._load_file(output_dir / "glr_specification.md")
        rdt = self._load_file(output_dir / "register_description_table.md")
        psq = self._load_file(output_dir / "programming_sequence.md")
        netlist = self._load_file(output_dir / "netlist_visual.md")
        hrs = self._load_file(output_dir / f"HRS_{safe_name}.md")

        glr = glr_spec or glr_generic
        if not glr:
            logger.warning("P7: GLR spec not found — proceeding with netlist + requirements only")

        user_message = f"""Generate a complete FPGA RTL design for:

**Project:** {project_name}

---

### GLR Specification (P6 output):
{(glr or '(not available)')[:6000]}

---

### Register Description Table (P7a output):
{(rdt or '(not available)')[:3000]}

---

### Programming Sequence (P7a output):
{(psq or '(not available)')[:1500]}

---

### Netlist Summary (P4 output):
{(netlist or '(not available)')[:2000]}

---

### HRS Reference (P2 output):
{(hrs or '(not available)')[:1500]}

---

Use the `generate_fpga_design` tool to return:
1. Complete synthesisable Verilog top module (`fpga_top.v`)
2. SystemVerilog testbench (`fpga_testbench.v`)
3. Vivado XDC constraints file (`constraints.xdc`)
4. Design summary report

Map all registers from the RDT to the register bus. Implement all FSMs identified in the GLR.
"""

        # P26 #8 (2026-04-25) — PARALLEL split.
        #
        # Step 1: tiny metadata call (~30s) returns module name, port
        # list, clock freq, FPGA part, FSMs, resource estimates. The
        # LLM agrees to a small set of design parameters that the
        # parallel content calls below all share — this is what keeps
        # the testbench's DUT instantiation, the XDC's pin assignments,
        # and the design summary all consistent with the Verilog top.
        #
        # Step 2: 4 parallel content calls (~60s each, but run
        # concurrently → ~60s total wall time) generate one file each.
        # Total wall time: ~90s vs. the previous ~10 min single-call.
        meta_messages = [{"role": "user", "content": (
            f"{user_message}\n\n"
            "Step 1 of 2: call ONLY `generate_fpga_metadata` to lock "
            "the module name, port list, clock frequency, target FPGA "
            "part, FSM names, and rough LUT/FF estimate. Step 2 will "
            "fill in the actual Verilog/testbench/XDC/summary content "
            "in parallel using your metadata as the contract — KEEP "
            "names short, final, and consistent so they don't drift."
        )}]
        meta_response = await self.call_llm(
            messages=meta_messages,
            system=self.get_system_prompt(project_context),
            tool_choice={"type": "tool", "name": "generate_fpga_metadata"},
        )
        metadata = None
        if meta_response.get("tool_calls"):
            for tc in meta_response["tool_calls"]:
                if tc["name"] == "generate_fpga_metadata":
                    metadata = tc["input"]
                    break

        fpga_data = None
        response = meta_response
        if metadata and not meta_response.get("degraded"):
            import json as _json
            meta_summary = (
                "## Locked-in design metadata (Step 1 output)\n"
                "Use these EXACTLY — do NOT invent new module names "
                "or port names; the other 3 sub-calls running in "
                "parallel use the same metadata so divergence will "
                "break the design.\n\n"
                f"```json\n{_json.dumps(metadata, indent=2)[:4000]}\n```\n"
            )
            content_messages = [{"role": "user", "content": (
                f"{user_message}\n\n{meta_summary}\n\n"
                "Step 2 of 2: emit ONLY this one content tool's output."
            )}]
            sys_prompt = self.get_system_prompt(project_context)

            async def _gen_section(tool_name: str) -> dict | None:
                """Fire one content tool call. On any failure (chain
                exhausted, rate-limit timeout, tool not called) return
                None so the caller can fall back without aborting the
                whole phase."""
                try:
                    resp = await self.call_llm(
                        messages=content_messages,
                        system=sys_prompt,
                        tool_choice={"type": "tool", "name": tool_name},
                    )
                except Exception as exc:
                    logger.warning(
                        "P7 sub-call %s raised: %s",
                        tool_name, str(exc)[:200],
                    )
                    return None
                if resp.get("tool_calls"):
                    for tc in resp["tool_calls"]:
                        if tc["name"] == tool_name:
                            return tc["input"]
                return None

            self.log("P7: dispatching 4 parallel content sub-calls "
                     "(verilog_top + testbench + xdc + summary)")
            verilog_res, tb_res, xdc_res, summary_res = await asyncio.gather(
                _gen_section("generate_verilog_top"),
                _gen_section("generate_testbench"),
                _gen_section("generate_xdc_constraints"),
                _gen_section("generate_design_summary"),
                return_exceptions=False,
            )
            fpga_data = dict(metadata)
            fpga_data["verilog_top"]     = (verilog_res or {}).get("verilog_top", "")
            fpga_data["testbench"]       = (tb_res      or {}).get("testbench", "")
            fpga_data["xdc_constraints"] = (xdc_res     or {}).get("xdc_constraints", "")
            fpga_data["design_summary"]  = (summary_res or {}).get("design_summary", "")
            # If ALL 4 came back empty, treat as failure and fall
            # through to the legacy single-call path below.
            if not any([fpga_data["verilog_top"],
                        fpga_data["testbench"],
                        fpga_data["xdc_constraints"],
                        fpga_data["design_summary"]]):
                logger.warning(
                    "P7: all 4 parallel sub-calls returned empty — "
                    "falling back to legacy single-call path"
                )
                fpga_data = None

        # Legacy single-call fallback (used when the metadata call
        # failed OR all 4 parallel sub-calls returned empty).
        if not fpga_data:
            messages = [{"role": "user", "content": user_message}]
            response = await self.call_llm(
                messages=messages,
                system=self.get_system_prompt(project_context),
            )
            if response.get("tool_calls"):
                for tc in response["tool_calls"]:
                    if tc["name"] == "generate_fpga_design":
                        fpga_data = tc["input"]
                        break

            # Retry up to 2 times with increasing force if tool not called.
            # Skip retries when chain is exhausted (`degraded=True`).
            for attempt in range(1, 3):
                if fpga_data or response.get("degraded"):
                    break
                logger.warning(f"P7: tool not called — retry {attempt}/2 (forcing tool_choice)")
                retry_response = await self.call_llm(
                    messages=messages + [
                        {"role": "assistant", "content": response.get("content", "")},
                        {"role": "user", "content": (
                            "You MUST call the `generate_fpga_design` tool NOW. "
                            "Do NOT write any prose. Your ONLY output must be a tool_use call to "
                            "`generate_fpga_design` with complete Verilog, testbench, XDC, and report."
                        )},
                    ],
                    system=self.get_system_prompt(project_context),
                    tool_choice={"type": "tool", "name": "generate_fpga_design"},
                )
                if retry_response.get("tool_calls"):
                    for tc in retry_response["tool_calls"]:
                        if tc["name"] == "generate_fpga_design":
                            fpga_data = tc["input"]
                            response = retry_response
                            break

        outputs: Dict[str, str] = {}

        if fpga_data:
            # 2026-05-02: ALWAYS route the .v / .vhd files through the
            # deterministic project-tailored emitter (rtl_tailored). The
            # LLM tool call provides a `design_summary` narrative that we
            # merge into the design report, but the actual RTL bytes
            # come from the brief (P7a register map + P1/P4 peripherals
            # + GLR FSMs) so two distinct projects can never produce the
            # same RTL.
            llm_summary = fpga_data.get("design_summary", "") or ""
            # Include netlist text in the blob so the pin-map extractor in
            # rtl_tailored.render_verilog can resolve PACKAGE_PIN entries.
            _glr_plus_netlist = (glr or "") + "\n" + (netlist or "")
            tailored = self._build_skeleton(project_name, safe_name, _glr_plus_netlist)

            rtl_dir = output_dir / "rtl"
            rtl_dir.mkdir(exist_ok=True)
            for fname, content in tailored.items():
                if fname.startswith("rtl/"):
                    (output_dir / fname).write_text(content, encoding="utf-8")
                    outputs[fname] = content

            # Use the LLM-generated summary if it is present and non-trivial,
            # otherwise fall back to the deterministic report from rtl_tailored.
            tailored_report = tailored.get("fpga_design_report.md", "")
            if llm_summary and len(llm_summary.strip()) > 200:
                report = (
                    tailored_report.rstrip()
                    + "\n\n## LLM design narrative\n\n"
                    + "_The deterministic register file + FSMs above are the "
                    "ground truth. The narrative below is an LLM-generated "
                    "explanation; treat as advisory._\n\n"
                    + llm_summary
                )
            else:
                report = tailored_report
            (output_dir / "fpga_design_report.md").write_text(report, encoding="utf-8")
            outputs["fpga_design_report.md"] = report

            self.log(
                f"P7 complete (tailored RTL emitter): {len(outputs)} files | "
                f"module={fpga_data.get('module_name','?')} | "
                f"clock={fpga_data.get('clock_frequency_mhz','?')} MHz | "
                f"registers={len(getattr(self._brief, 'registers', []) or [])} | "
                f"peripherals={len(getattr(self._brief, 'peripherals', []) or [])} | "
                f"fsms={len(getattr(self._brief, 'fsms', []) or [])}"
            )

        # The legacy LLM-output write path (verilog_top from the tool call)
        # is dead - skip the rest of the original block.
        if False and fpga_data:
            verilog_top = fpga_data.get("verilog_top", "")
            testbench   = fpga_data.get("testbench", "")
            xdc         = fpga_data.get("xdc_constraints", "")
            summary     = fpga_data.get("design_summary", "")

            rtl_dir = output_dir / "rtl"
            rtl_dir.mkdir(exist_ok=True)

            # P7 polish (2026-05-01): SPDX/Doxygen banner + port consistency
            # check across the three artifacts. The banner only prepends if
            # the file does not already start with one (LLM sometimes puts
            # its own header).
            module_name = fpga_data.get("module_name", "fpga_top")
            clock_mhz   = fpga_data.get("clock_frequency_mhz", "?")

            def _maybe_prepend_header(content: str, *, filename: str, brief: str) -> str:
                if not content:
                    return content
                if "SPDX-License-Identifier" in content[:300]:
                    return content
                return _make_doxygen_header(
                    filename=filename, brief=brief,
                    project_name=project_name, module_name=module_name,
                    clock_mhz=clock_mhz,
                ) + content

            verilog_top = _maybe_prepend_header(
                verilog_top, filename="fpga_top.v",
                brief="Synthesisable top-level Verilog module",
            )
            testbench = _maybe_prepend_header(
                testbench, filename="fpga_testbench.v",
                brief="Self-checking SystemVerilog testbench for fpga_top",
            )
            xdc = _maybe_prepend_header(
                xdc, filename="constraints.xdc",
                brief="Vivado XDC timing & I/O constraints",
            )

            # Cross-validate port names across the three artifacts. We log
            # warnings rather than failing the phase so a partial divergence
            # does not stop the pipeline; the user sees them in the audit
            # trail and can re-run.
            for w in _validate_port_consistency(verilog_top, testbench, xdc):
                logger.warning("P7.port_consistency: %s", w)

            if verilog_top:
                (rtl_dir / "fpga_top.v").write_text(verilog_top, encoding="utf-8")
                outputs["rtl/fpga_top.v"] = verilog_top

            if testbench:
                (rtl_dir / "fpga_testbench.v").write_text(testbench, encoding="utf-8")
                outputs["rtl/fpga_testbench.v"] = testbench

            if xdc:
                (rtl_dir / "constraints.xdc").write_text(xdc, encoding="utf-8")
                outputs["rtl/constraints.xdc"] = xdc

            # Build design report
            report = self._build_design_report(fpga_data, project_name)
            report_path = output_dir / "fpga_design_report.md"
            report_path.write_text(report, encoding="utf-8")
            outputs["fpga_design_report.md"] = report

            self.log(
                f"P7 complete: {len(outputs)} files | "
                f"module={fpga_data.get('module_name','?')} | "
                f"clock={fpga_data.get('clock_frequency_mhz','?')} MHz | "
                f"~{fpga_data.get('lut_estimate','?')} LUTs"
            )
        else:
            # Skeleton fallback — pipeline must continue
            logger.warning("P7: generate_fpga_design tool not called after retry — using skeleton")
            _glr_plus_netlist = (glr or "") + "\n" + (netlist or "")
            skeleton = self._build_skeleton(project_name, safe_name, _glr_plus_netlist)

            # P7 polish (2026-05-01): same SPDX/Doxygen banner on the
            # skeleton output so deterministic-fallback runs match the
            # tool-call output's file structure.
            _SKELETON_BRIEFS = {
                "rtl/fpga_top.v": "Synthesisable top-level Verilog module",
                "rtl/fpga_testbench.v": "Self-checking SystemVerilog testbench for fpga_top",
                "rtl/constraints.xdc": "Vivado XDC timing & I/O constraints",
            }
            for fname, content in skeleton.items():
                if fname in _SKELETON_BRIEFS and "SPDX-License-Identifier" not in content[:300]:
                    content = _make_doxygen_header(
                        filename=fname.split("/")[-1],
                        brief=_SKELETON_BRIEFS[fname],
                        project_name=project_name,
                        module_name=re.sub(r"[^a-z0-9_]", "_", safe_name.lower()) + "_top",
                        clock_mhz="100",
                    ) + content
                fpath = output_dir / fname
                fpath.parent.mkdir(parents=True, exist_ok=True)
                fpath.write_text(content, encoding="utf-8")
                outputs[fname] = content

        return {
            "response": response.get("content", "FPGA design generated."),
            "phase_complete": True,
            "outputs": outputs,
        }

    # ------------------------------------------------------------------ #
    # Report builder
    # ------------------------------------------------------------------ #

    def _build_design_report(self, data: dict, project_name: str) -> str:
        module_name = data.get("module_name", "fpga_top")
        clk_mhz     = data.get("clock_frequency_mhz", "?")
        fpga_part   = data.get("fpga_part", "xc7a35tcpg236-1")
        lut_est     = data.get("lut_estimate", "?")
        ff_est      = data.get("ff_estimate", "?")
        summary     = data.get("design_summary", "")
        ports       = data.get("ports", [])
        fsms        = data.get("state_machines", [])

        lines = [
            "# FPGA Design Report",
            f"## {project_name}",
            "",
            f"> **Module:** `{module_name}`  |  "
            f"**Target:** `{fpga_part}`  |  "
            f"**Clock:** {clk_mhz} MHz",
            "",
        ]

        if summary:
            lines += ["## Design Summary", "", summary, ""]

        # Resource estimate
        lines += [
            "---",
            "## Resource Estimate",
            "",
            "| Resource | Estimate |",
            "|----------|----------|",
            f"| LUTs | ~{lut_est} |",
            f"| Flip-Flops | ~{ff_est} |",
            "| BRAM | 0 (pure logic) |",
            "| DSPs | 0 |",
            "",
        ]

        # Port table
        if ports:
            lines += [
                "---",
                "## Port List",
                "",
                "| Port | Direction | Width | Description |",
                "|------|-----------|-------|-------------|",
            ]
            for p in ports:
                lines.append(
                    f"| `{p.get('name','')}` "
                    f"| {p.get('direction','')} "
                    f"| {p.get('width',1)} "
                    f"| {p.get('description','')} |"
                )
            lines.append("")

        # FSM diagrams (Mermaid)
        if fsms:
            lines += ["---", "## State Machines", ""]
            for fsm in fsms:
                lines += [
                    f"### {fsm.get('name', 'FSM')}",
                    "",
                    f"{fsm.get('description', '')}",
                    "",
                    "```mermaid",
                    "stateDiagram-v2",
                ]
                states = fsm.get("states", [])
                if states:
                    lines.append(f"    [*] --> {states[0]}")
                    for i in range(len(states) - 1):
                        lines.append(f"    {states[i]} --> {states[i+1]}")
                    lines.append(f"    {states[-1]} --> {states[0]}")
                lines += ["```", ""]

        # Generated files
        lines += [
            "---",
            "## Generated Files",
            "",
            "| File | Description |",
            "|------|-------------|",
            "| `rtl/fpga_top.v` | Synthesisable top-level Verilog module |",
            "| `rtl/fpga_testbench.v` | Self-checking SystemVerilog testbench |",
            "| `rtl/constraints.xdc` | Vivado XDC timing & I/O constraints |",
            "",
            "---",
            "## How to Synthesise (Vivado)",
            "",
            "```tcl",
            "# In Vivado Tcl console:",
            f"create_project {module_name} . -part {fpga_part}",
            "add_files rtl/fpga_top.v",
            "add_files -fileset constrs_1 rtl/constraints.xdc",
            "launch_runs synth_1",
            "wait_on_run synth_1",
            "launch_runs impl_1 -to_step write_bitstream",
            "wait_on_run impl_1",
            "```",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # Skeleton fallback
    # ------------------------------------------------------------------ #

    def _build_skeleton(self, project_name: str, safe_name: str, glr: str) -> Dict[str, str]:
        """Project-tailored RTL emitter (2026-05-01).

        Dispatches by HDL language. Both branches now consume the
        ProjectBrief (peripherals, registers, FSMs from P1-P7a) and emit
        content keyed off it. If the brief is empty / not built (e.g. a
        unit test invoking the skeleton directly), the renderers fall
        back to a minimal generic baseline.
        """
        brief = getattr(self, "_brief", None)
        if brief is None:
            from schemas.project_brief import ProjectBrief
            brief = ProjectBrief(project_name=project_name)
        lang = (getattr(brief, "hdl_language", "verilog") or "verilog").lower()
        if lang == "vhdl":
            return rtl_tailored.render_vhdl(brief, project_name, safe_name, glr)
        return rtl_tailored.render_verilog(brief, project_name, safe_name, glr)

    def _build_skeleton_verilog_legacy_unused(self, project_name: str, safe_name: str, glr: str) -> Dict[str, str]:
        """Deterministic RTL generator from GLR spec — no LLM needed.

        Parses the GLR markdown for interfaces, registers, and FSM hints,
        then generates production-quality Verilog with:
        - SPI slave controller FSM
        - Data-path / acquisition controller FSM
        - Full register bus (CTRL, STATUS, VERSION, IRQ, CONFIG)
        - Proper clock domain, reset, and interrupt logic
        - LVDS / ADC / SPI / UART / GPIO ports inferred from GLR
        """
        module = re.sub(r"[^a-z0-9_]", "_", safe_name.lower())
        glr_l = (glr or "").lower()

        # ── Detect interfaces from GLR text ─────────────────────────
        has_spi   = "spi" in glr_l
        has_adc   = "adc" in glr_l or "lvds" in glr_l or "digitiz" in glr_l
        has_uart  = "uart" in glr_l or "serial" in glr_l
        has_gpio  = "gpio" in glr_l
        has_dac   = "dac" in glr_l
        has_pwm   = "pwm" in glr_l
        has_i2c   = "i2c" in glr_l

        # Detect data width
        data_w = 16
        for w in [32, 24, 14, 12, 10, 8]:
            if f"{w}-bit" in glr_l or f"{w}bit" in glr_l:
                data_w = w
                break

        # Detect clock
        clk_mhz = 100
        import re as _re
        clk_m = _re.search(r"(\d+)\s*mhz", glr_l)
        if clk_m:
            clk_mhz = int(clk_m.group(1))
        clk_period = round(1000.0 / clk_mhz, 3)

        # ── Build port list ─────────────────────────────────────────
        ports = [
            "    input  wire              clk,           // System clock",
            "    input  wire              rst_n,         // Active-low synchronous reset",
            "",
            "    // Register bus interface",
            "    input  wire [15:0]       reg_addr,      // Address",
            "    input  wire [15:0]       reg_wdata,     // Write data",
            "    output reg  [15:0]       reg_rdata,     // Read data",
            "    input  wire              reg_wr,        // Write strobe",
            "    input  wire              reg_rd,        // Read strobe",
            "",
            "    // Interrupt",
            "    output wire              irq_out,       // Active-high interrupt",
        ]
        if has_spi:
            ports += [
                "",
                "    // SPI master (to ADC / PLL / DAC)",
                "    output reg              spi_clk,",
                "    output reg              spi_mosi,",
                "    input  wire             spi_miso,",
                "    output reg  [3:0]       spi_cs_n,      // Up to 4 slaves",
            ]
        if has_adc:
            ports += [
                "",
                f"    // ADC data interface (LVDS deserialized)",
                f"    input  wire [{data_w-1}:0]     adc_data,",
                "    input  wire             adc_data_valid,",
                "    output wire             adc_sync,",
            ]
        if has_uart:
            ports += [
                "",
                "    // UART debug port",
                "    input  wire             uart_rxd,",
                "    output wire             uart_txd,",
            ]
        if has_gpio:
            ports += [
                "",
                "    // GPIO",
                "    output reg  [7:0]       gpio_out,",
                "    input  wire [7:0]       gpio_in,",
            ]
        if has_dac:
            ports += [
                "",
                f"    // DAC output",
                f"    output reg  [{data_w-1}:0]     dac_data,",
                "    output reg              dac_wr,",
            ]
        if has_pwm:
            ports += [
                "",
                "    // PWM outputs",
                "    output reg  [3:0]       pwm_out,",
            ]
        ports += [
            "",
            "    // Status",
            "    output wire             busy,",
            "    output wire             error_flag",
        ]

        # ── Register definitions ────────────────────────────────────
        regs = [
            ("CTRL",       "12'h000", "RW", "16'h0000", "Control: [0] enable, [1] start, [2] continuous, [3] irq_en"),
            ("STATUS",     "12'h001", "RO", None,        "Status: [0] busy, [1] done, [2] overflow, [3] error"),
            ("VERSION",    "12'h002", "RO", None,        "Firmware version (read-only 0x0100)"),
            ("SCRATCH",    "12'h003", "RW", "16'h0000",  "Scratch register for diagnostics"),
            ("CONFIG0",    "12'h004", "RW", "16'h0001",  "Configuration 0: sample count / mode"),
            ("CONFIG1",    "12'h005", "RW", "16'h0000",  "Configuration 1: threshold / gain"),
            ("ADC_DATA_L", "12'h010", "RO", None,        "ADC captured data [15:0]"),
            ("ADC_DATA_H", "12'h011", "RO", None,        "ADC captured data [31:16]"),
            ("IRQ_MASK",   "12'hF00", "RW", "16'hFFFF",  "Interrupt mask (1=enabled)"),
            ("IRQ_STATUS", "12'hF01", "W1C", "16'h0000", "Interrupt status (write-1-to-clear)"),
        ]
        if has_spi:
            regs += [
                ("SPI_CTRL",  "12'h020", "RW", "16'h0000", "SPI control: [2:0] slave_sel, [3] start, [7:4] clk_div"),
                ("SPI_TXDATA","12'h021", "RW", "16'h0000", "SPI TX data"),
                ("SPI_RXDATA","12'h022", "RO", None,       "SPI RX data (last received)"),
                ("SPI_STATUS","12'h023", "RO", None,       "SPI status: [0] busy, [1] done"),
            ]

        # ── Verilog source ──────────────────────────────────────────
        v = []
        v.append(f"// {'='*60}")
        v.append(f"// Module  : {module}_top")
        v.append(f"// Project : {project_name}")
        v.append(f"// Clock   : {clk_mhz} MHz ({clk_period} ns period)")
        v.append(f"// Source  : Silicon to Software (S2S) v2 (auto-generated from GLR)")
        v.append(f"// {'='*60}")
        v.append("`timescale 1ns / 1ps")
        v.append("")
        v.append(f"module {module}_top (")
        v.append("\n".join(ports))
        v.append(");")
        v.append("")

        # Parameters
        v.append("    // Parameters")
        v.append("    localparam VERSION_VAL  = 16'h0100;")
        v.append(f"    localparam DATA_WIDTH   = {data_w};")
        v.append(f"    localparam CLK_FREQ_MHZ = {clk_mhz};")
        v.append("")

        # Register declarations
        v.append("    // ---- Register file ----")
        for rname, _, rw, rst_val, desc in regs:
            if rw in ("RW", "W1C"):
                v.append(f"    reg [15:0] {rname.lower()}_r;  // {desc}")
        v.append("    reg [15:0] status_r;")
        if has_adc:
            v.append(f"    reg [{data_w-1}:0] adc_capture_r;")
            v.append("    reg        adc_done_r;")
        v.append("")

        # FSM 1: Main acquisition controller
        v.append("    // ---- FSM: Acquisition Controller ----")
        v.append("    localparam S_IDLE    = 3'd0,")
        v.append("               S_ARM     = 3'd1,")
        v.append("               S_ACQUIRE = 3'd2,")
        v.append("               S_PROCESS = 3'd3,")
        v.append("               S_DONE    = 3'd4,")
        v.append("               S_ERROR   = 3'd5;")
        v.append("    reg [2:0] acq_state_r, acq_next;")
        v.append("    reg [15:0] sample_cnt_r;")
        v.append("")

        # FSM 2: SPI controller (if applicable)
        if has_spi:
            v.append("    // ---- FSM: SPI Master Controller ----")
            v.append("    localparam SPI_IDLE  = 2'd0,")
            v.append("               SPI_SHIFT = 2'd1,")
            v.append("               SPI_DONE  = 2'd2;")
            v.append("    reg [1:0]  spi_state_r;")
            v.append("    reg [4:0]  spi_bit_cnt_r;")
            v.append("    reg [15:0] spi_shift_r;")
            v.append("    reg [15:0] spi_rxdata_r;")
            v.append("    reg        spi_busy_r;")
            v.append("    reg [7:0]  spi_clk_div_r;")
            v.append("")

        # Interrupt logic
        v.append("    // ---- Interrupt logic ----")
        v.append("    wire [15:0] irq_pending = irq_status_r & irq_mask_r;")
        v.append("    assign irq_out = |irq_pending;")
        v.append("")

        # Status assigns
        v.append("    assign busy       = (acq_state_r != S_IDLE);")
        v.append("    assign error_flag = (acq_state_r == S_ERROR);")
        if has_adc:
            v.append("    assign adc_sync   = ctrl_r[1];  // START bit triggers sync")
        v.append("")

        # Register write
        v.append("    // ---- Register Write ----")
        v.append("    always @(posedge clk) begin")
        v.append("        if (!rst_n) begin")
        for rname, _, rw, rst_val, _ in regs:
            if rw == "RW" and rst_val:
                v.append(f"            {rname.lower()}_r <= {rst_val};")
            elif rw == "W1C" and rst_val:
                v.append(f"            {rname.lower()}_r <= {rst_val};")
        v.append("        end else if (reg_wr) begin")
        v.append("            case (reg_addr[11:0])")
        for rname, addr, rw, _, _ in regs:
            if rw == "RW":
                v.append(f"                {addr}: {rname.lower()}_r <= reg_wdata;")
            elif rw == "W1C":
                v.append(f"                {addr}: {rname.lower()}_r <= {rname.lower()}_r & ~reg_wdata; // W1C")
        v.append("                default: ;")
        v.append("            endcase")
        v.append("        end")
        v.append("    end")
        v.append("")

        # Register read
        v.append("    // ---- Register Read ----")
        v.append("    always @(posedge clk) begin")
        v.append("        if (!rst_n)")
        v.append("            reg_rdata <= 16'h0000;")
        v.append("        else if (reg_rd) begin")
        v.append("            case (reg_addr[11:0])")
        for rname, addr, rw, _, _ in regs:
            if rname == "VERSION":
                v.append(f"                {addr}: reg_rdata <= VERSION_VAL;")
            elif rname == "STATUS":
                v.append(f"                {addr}: reg_rdata <= status_r;")
            elif rname == "ADC_DATA_L" and has_adc:
                v.append(f"                {addr}: reg_rdata <= adc_capture_r[15:0];")
            elif rname == "ADC_DATA_H" and has_adc:
                val = f"adc_capture_r[{data_w-1}:16]" if data_w > 16 else "16'h0000"
                v.append(f"                {addr}: reg_rdata <= {val};")
            elif rw == "RO" and has_spi and rname == "SPI_RXDATA":
                v.append(f"                {addr}: reg_rdata <= spi_rxdata_r;")
            elif rw == "RO" and has_spi and rname == "SPI_STATUS":
                v.append(f"                {addr}: reg_rdata <= {{14'b0, ~spi_busy_r, spi_busy_r}};")
            elif rw != "RO":
                v.append(f"                {addr}: reg_rdata <= {rname.lower()}_r;")
        v.append("                default: reg_rdata <= 16'h0000;  // Unmapped address: read-as-zero")
        v.append("            endcase")
        v.append("        end")
        v.append("    end")
        v.append("")

        # Status register update
        v.append("    // ---- Status register ----")
        v.append("    always @(posedge clk) begin")
        v.append("        if (!rst_n)")
        v.append("            status_r <= 16'h0000;")
        v.append("        else")
        v.append("            status_r <= {12'b0, error_flag, adc_done_r, (acq_state_r == S_DONE), busy};" if has_adc else "            status_r <= {14'b0, error_flag, busy};")
        v.append("    end")
        v.append("")

        # Acquisition FSM
        v.append("    // ---- Acquisition Controller FSM ----")
        v.append("    always @(posedge clk) begin")
        v.append("        if (!rst_n) begin")
        v.append("            acq_state_r  <= S_IDLE;")
        v.append("            sample_cnt_r <= 16'd0;")
        if has_adc:
            v.append("            adc_capture_r <= 0;")
            v.append("            adc_done_r    <= 1'b0;")
        v.append("        end else begin")
        v.append("            case (acq_state_r)")
        v.append("                S_IDLE: begin")
        v.append("                    sample_cnt_r <= 16'd0;")
        if has_adc:
            v.append("                    adc_done_r   <= 1'b0;")
        v.append("                    if (ctrl_r[1])  // START bit")
        v.append("                        acq_state_r <= S_ARM;")
        v.append("                end")
        v.append("                S_ARM: begin")
        v.append("                    acq_state_r <= S_ACQUIRE;")
        v.append("                end")
        v.append("                S_ACQUIRE: begin")
        if has_adc:
            v.append("                    if (adc_data_valid) begin")
            v.append("                        adc_capture_r <= adc_data;")
            v.append("                        sample_cnt_r  <= sample_cnt_r + 1;")
            v.append("                    end")
            v.append("                    if (sample_cnt_r >= config0_r)")
        else:
            v.append("                    sample_cnt_r <= sample_cnt_r + 1;")
            v.append("                    if (sample_cnt_r >= config0_r)")
        v.append("                        acq_state_r <= S_PROCESS;")
        v.append("                end")
        v.append("                S_PROCESS: begin")
        if has_adc:
            v.append("                    adc_done_r  <= 1'b1;")
        v.append("                    irq_status_r[0] <= 1'b1;  // Acquisition complete IRQ")
        v.append("                    acq_state_r <= S_DONE;")
        v.append("                end")
        v.append("                S_DONE: begin")
        v.append("                    if (!ctrl_r[1])  // START deasserted")
        v.append("                        acq_state_r <= ctrl_r[2] ? S_ARM : S_IDLE;  // continuous mode")
        v.append("                end")
        v.append("                S_ERROR: begin")
        v.append("                    if (!ctrl_r[0])  // ENABLE deasserted to clear error")
        v.append("                        acq_state_r <= S_IDLE;")
        v.append("                end")
        v.append("                default: acq_state_r <= S_IDLE;")
        v.append("            endcase")
        v.append("        end")
        v.append("    end")
        v.append("")

        # SPI FSM
        if has_spi:
            v.append("    // ---- SPI Master FSM ----")
            v.append("    always @(posedge clk) begin")
            v.append("        if (!rst_n) begin")
            v.append("            spi_state_r   <= SPI_IDLE;")
            v.append("            spi_bit_cnt_r <= 5'd0;")
            v.append("            spi_shift_r   <= 16'd0;")
            v.append("            spi_rxdata_r  <= 16'd0;")
            v.append("            spi_busy_r    <= 1'b0;")
            v.append("            spi_clk       <= 1'b0;")
            v.append("            spi_mosi      <= 1'b0;")
            v.append("            spi_cs_n      <= 4'hF;")
            v.append("        end else begin")
            v.append("            case (spi_state_r)")
            v.append("                SPI_IDLE: begin")
            v.append("                    spi_busy_r <= 1'b0;")
            v.append("                    spi_cs_n   <= 4'hF;")
            v.append("                    spi_clk    <= 1'b0;")
            v.append("                    if (spi_ctrl_r[3]) begin  // SPI start")
            v.append("                        spi_state_r   <= SPI_SHIFT;")
            v.append("                        spi_shift_r   <= spi_txdata_r;")
            v.append("                        spi_bit_cnt_r <= 5'd15;")
            v.append("                        spi_busy_r    <= 1'b1;")
            v.append("                        spi_cs_n[spi_ctrl_r[2:0]] <= 1'b0;")
            v.append("                    end")
            v.append("                end")
            v.append("                SPI_SHIFT: begin")
            v.append("                    spi_clk  <= ~spi_clk;")
            v.append("                    if (spi_clk) begin  // falling edge: shift")
            v.append("                        spi_mosi    <= spi_shift_r[15];")
            v.append("                        spi_shift_r <= {spi_shift_r[14:0], spi_miso};")
            v.append("                        if (spi_bit_cnt_r == 0)")
            v.append("                            spi_state_r <= SPI_DONE;")
            v.append("                        else")
            v.append("                            spi_bit_cnt_r <= spi_bit_cnt_r - 1;")
            v.append("                    end")
            v.append("                end")
            v.append("                SPI_DONE: begin")
            v.append("                    spi_rxdata_r     <= spi_shift_r;")
            v.append("                    spi_cs_n         <= 4'hF;")
            v.append("                    spi_clk          <= 1'b0;")
            v.append("                    irq_status_r[1]  <= 1'b1;  // SPI done IRQ")
            v.append("                    spi_state_r      <= SPI_IDLE;")
            v.append("                end")
            v.append("                default: spi_state_r <= SPI_IDLE;")
            v.append("            endcase")
            v.append("        end")
            v.append("    end")
            v.append("")

        # GPIO
        if has_gpio:
            v.append("    // ---- GPIO ----")
            v.append("    always @(posedge clk)")
            v.append("        if (!rst_n) gpio_out <= 8'h00;")
            v.append("        else        gpio_out <= config1_r[7:0];")
            v.append("")

        # PWM
        if has_pwm:
            v.append("    // ---- PWM Generator ----")
            v.append("    reg [15:0] pwm_cnt_r;")
            v.append("    always @(posedge clk) begin")
            v.append("        if (!rst_n) pwm_cnt_r <= 0;")
            v.append("        else        pwm_cnt_r <= pwm_cnt_r + 1;")
            v.append("    end")
            v.append("    assign pwm_out = {4{pwm_cnt_r < config1_r}};")
            v.append("")

        # UART stub
        if has_uart:
            v.append("    // ---- UART stub (active low TX idle) ----")
            v.append("    assign uart_txd = 1'b1;  // Idle high — implement TX FIFO in next iteration")
            v.append("")

        v.append("endmodule")
        verilog = "\n".join(v)

        # ── Testbench ───────────────────────────────────────────────
        tb = []
        tb.append(f"// Testbench : {module}_top_tb")
        tb.append(f"// Project   : {project_name}")
        tb.append("`timescale 1ns / 1ps")
        tb.append("")
        tb.append(f"module {module}_top_tb;")
        tb.append("    reg         clk = 0;")
        tb.append("    reg         rst_n = 0;")
        tb.append("    reg  [15:0] reg_addr = 0, reg_wdata = 0;")
        tb.append("    wire [15:0] reg_rdata;")
        tb.append("    reg         reg_wr = 0, reg_rd = 0;")
        tb.append("    wire        irq_out, busy, error_flag;")
        if has_spi:
            tb.append("    wire        spi_clk_w, spi_mosi_w;")
            tb.append("    wire [3:0]  spi_cs_n_w;")
            tb.append("    reg         spi_miso = 0;")
        if has_adc:
            tb.append(f"    reg  [{data_w-1}:0] adc_data = 0;")
            tb.append("    reg         adc_data_valid = 0;")
            tb.append("    wire        adc_sync;")
        if has_gpio:
            tb.append("    wire [7:0]  gpio_out;")
            tb.append("    reg  [7:0]  gpio_in = 0;")
        if has_uart:
            tb.append("    reg         uart_rxd = 1;")
            tb.append("    wire        uart_txd;")
        tb.append("")
        tb.append(f"    {module}_top dut (.*);")
        tb.append(f"    always #{round(clk_period/2, 1)} clk = ~clk;")
        tb.append("")
        tb.append("    task write_reg(input [15:0] a, input [15:0] d);")
        tb.append("        begin @(posedge clk); reg_addr=a; reg_wdata=d; reg_wr=1;")
        tb.append("              @(posedge clk); reg_wr=0; end")
        tb.append("    endtask")
        tb.append("    task read_reg(input [15:0] a, output [15:0] d);")
        tb.append("        begin @(posedge clk); reg_addr=a; reg_rd=1;")
        tb.append("              @(posedge clk); d=reg_rdata; reg_rd=0; end")
        tb.append("    endtask")
        tb.append("")
        tb.append("    reg [15:0] rd; integer pass_c=0, fail_c=0;")
        tb.append("    task check(input [15:0] exp, input [8*32-1:0] label);")
        tb.append("        if (rd===exp) begin $display(\"PASS: %0s = 0x%04X\",label,rd); pass_c=pass_c+1; end")
        tb.append("        else          begin $display(\"FAIL: %0s got 0x%04X exp 0x%04X\",label,rd,exp); fail_c=fail_c+1; end")
        tb.append("    endtask")
        tb.append("")
        tb.append("    initial begin")
        tb.append(f"        $dumpfile(\"{module}_tb.vcd\"); $dumpvars(0, {module}_top_tb);")
        tb.append("        rst_n=0; repeat(5) @(posedge clk); rst_n=1; repeat(2) @(posedge clk);")
        tb.append("")
        tb.append("        // T1: Version register")
        tb.append("        read_reg(16'h0002, rd); check(16'h0100, \"VERSION\");")
        tb.append("")
        tb.append("        // T2: Scratch R/W")
        tb.append("        write_reg(16'h0003, 16'hCAFE);")
        tb.append("        read_reg(16'h0003, rd); check(16'hCAFE, \"SCRATCH\");")
        tb.append("")
        tb.append("        // T3: CTRL write + busy assert")
        tb.append("        write_reg(16'h0000, 16'h0003);  // enable + start")
        tb.append("        repeat(3) @(posedge clk);")
        tb.append("        read_reg(16'h0001, rd);")
        tb.append("        if (rd[0]) begin $display(\"PASS: busy asserted\"); pass_c=pass_c+1; end")
        tb.append("        else       begin $display(\"FAIL: busy not asserted\"); fail_c=fail_c+1; end")
        if has_adc:
            tb.append("")
            tb.append("        // T4: ADC capture")
            tb.append(f"        adc_data = {data_w}'hABCD; adc_data_valid = 1;")
            tb.append("        repeat(5) @(posedge clk); adc_data_valid = 0;")
            tb.append("        read_reg(16'h0010, rd); check(16'hABCD, \"ADC_DATA_L\");")
        if has_spi:
            tb.append("")
            tb.append("        // T5: SPI transfer")
            tb.append("        write_reg(16'h0021, 16'h55AA);  // TX data")
            tb.append("        write_reg(16'h0020, 16'h0008);  // slave 0, start")
            tb.append("        repeat(40) @(posedge clk);")
            tb.append("        read_reg(16'h0023, rd);")
            tb.append("        $display(\"INFO: SPI status = 0x%04X\", rd);")
        tb.append("")
        tb.append("        // T6: IRQ mask/status")
        tb.append("        write_reg(16'hF00, 16'h0001);  // enable IRQ[0]")
        tb.append("        read_reg(16'hF01, rd);")
        tb.append("        $display(\"INFO: IRQ status = 0x%04X\", rd);")
        tb.append("")
        tb.append("        // T7: Unmapped register reads as 0x0000")
        tb.append("        read_reg(16'hFFF, rd); check(16'h0000, \"UNKNOWN_REG\");")
        tb.append("")
        tb.append("        repeat(10) @(posedge clk);")
        tb.append("        if (fail_c==0) $display(\"\\nALL %0d TESTS PASSED\", pass_c);")
        tb.append("        else           $display(\"\\n%0d FAILURES of %0d tests\", fail_c, pass_c+fail_c);")
        tb.append("        $finish;")
        tb.append("    end")
        tb.append("endmodule")
        testbench = "\n".join(tb)

        # ── XDC ─────────────────────────────────────────────────────
        xdc_lines = [
            f"# Constraints : {project_name}",
            f"# Target      : xc7a35tcpg236-1 (Artix-7)",
            f"# Clock       : {clk_mhz} MHz",
            "",
            f"create_clock -period {clk_period} -name clk [get_ports clk]",
            "",
            "set_input_delay  -clock clk -max 4.0 [get_ports {reg_addr reg_wdata reg_wr reg_rd}]",
            "set_input_delay  -clock clk -min 0.5 [get_ports {reg_addr reg_wdata reg_wr reg_rd}]",
            "set_output_delay -clock clk -max 4.0 [get_ports {reg_rdata busy error_flag irq_out}]",
            "set_output_delay -clock clk -min 0.5 [get_ports {reg_rdata busy error_flag irq_out}]",
            "set_false_path -from [get_ports rst_n]",
            "",
            "set_property PACKAGE_PIN W5  [get_ports clk]",
            "set_property IOSTANDARD  LVCMOS33 [get_ports clk]",
            "set_property PACKAGE_PIN V17 [get_ports rst_n]",
            "set_property IOSTANDARD  LVCMOS33 [get_ports rst_n]",
        ]
        if has_spi:
            xdc_lines += [
                "",
                "# SPI pins",
                "set_output_delay -clock clk -max 3.0 [get_ports {spi_clk spi_mosi spi_cs_n}]",
                "set_input_delay  -clock clk -max 4.0 [get_ports spi_miso]",
            ]
        if has_adc:
            xdc_lines += [
                "",
                "# ADC LVDS data — dedicated sample clock from front-end",
                f"create_clock -period 10.0 -name adc_sample_clk [get_ports adc_data_valid]",
                f"set_input_delay  -clock adc_sample_clk -max 2.0 [get_ports {{adc_data adc_data_valid}}]",
                # P2.7 — declare the CDC boundary explicitly. Without
                # these constraints Vivado would apply normal setup/hold
                # checks across the async ADC↔FPGA boundary and either
                # flag false timing violations or, worse, silently route
                # metastable paths. 2FF synchronisers must still exist
                # in the RTL — these constraints only TELL the router
                # not to bother chasing a false path.
                "set_clock_groups -asynchronous -group clk -group adc_sample_clk",
                "set_false_path -from [get_clocks adc_sample_clk] -to [get_clocks clk]",
                "set_false_path -from [get_clocks clk] -to [get_clocks adc_sample_clk]",
            ]
        if has_spi:
            xdc_lines += [
                "",
                "# SPI is a slow interface but its MISO is async relative to clk —",
                "# declare the false path so Vivado doesn't chase setup/hold across it.",
                "set_false_path -from [get_ports spi_miso] -to [get_clocks clk]",
            ]
        xdc = "\n".join(xdc_lines)

        # ── Interface count for report ──────────────────────────────
        iface_list = ["Register Bus (16-bit)"]
        if has_spi:  iface_list.append("SPI Master (4 CS)")
        if has_adc:  iface_list.append(f"ADC Data ({data_w}-bit LVDS)")
        if has_uart: iface_list.append("UART Debug")
        if has_gpio: iface_list.append("GPIO (8-bit)")
        if has_dac:  iface_list.append(f"DAC ({data_w}-bit)")
        if has_pwm:  iface_list.append("PWM (4-ch)")

        n_ports = 11 + (4 if has_spi else 0) + (3 if has_adc else 0) + \
                  (2 if has_uart else 0) + (2 if has_gpio else 0) + \
                  (2 if has_dac else 0) + (1 if has_pwm else 0)
        n_regs = len(regs)
        n_fsms = 1 + (1 if has_spi else 0)

        report = (
            f"# FPGA Design Report\n\n"
            f"## {project_name}\n\n"
            f"## Architecture Overview\n\n"
            f"- **Module**: `{module}_top`\n"
            f"- **Clock**: {clk_mhz} MHz ({clk_period} ns period)\n"
            f"- **Data Width**: {data_w}-bit\n"
            f"- **Ports**: {n_ports}\n"
            f"- **Registers**: {n_regs}\n"
            f"- **FSMs**: {n_fsms} (Acquisition Controller"
            + (", SPI Master" if has_spi else "") + ")\n"
            f"- **Interfaces**: {', '.join(iface_list)}\n\n"
            f"## FSM: Acquisition Controller\n\n"
            f"```mermaid\nstateDiagram-v2\n"
            f"    IDLE --> ARM : ctrl.START\n"
            f"    ARM --> ACQUIRE : armed\n"
            f"    ACQUIRE --> PROCESS : sample_cnt >= config0\n"
            f"    PROCESS --> DONE : irq asserted\n"
            f"    DONE --> IDLE : START deasserted\n"
            f"    DONE --> ARM : continuous mode\n"
            f"    * --> ERROR : fault\n"
            f"    ERROR --> IDLE : ENABLE deasserted\n"
            f"```\n\n"
        )
        if has_spi:
            report += (
                f"## FSM: SPI Master\n\n"
                f"```mermaid\nstateDiagram-v2\n"
                f"    IDLE --> SHIFT : spi_ctrl.START\n"
                f"    SHIFT --> DONE : bit_cnt == 0\n"
                f"    DONE --> IDLE : auto\n"
                f"```\n\n"
            )
        report += (
            f"## Register Map\n\n"
            f"| Address | Name | Access | Description |\n"
            f"|---------|------|--------|-------------|\n"
        )
        for rname, addr, rw, _, desc in regs:
            report += f"| `{addr}` | {rname} | {rw} | {desc} |\n"
        report += (
            f"\n## Generated Files\n\n"
            f"| File | Description |\n|------|-------------|\n"
            f"| `rtl/fpga_top.v` | Top module with {n_fsms} FSMs, {n_regs} registers, {n_ports} ports |\n"
            f"| `rtl/fpga_testbench.v` | Functional testbench with register R/W and FSM tests |\n"
            f"| `rtl/constraints.xdc` | Vivado timing constraints for {clk_mhz} MHz |\n"
            f"\n## Resource Estimate\n\n"
            f"| Resource | Estimate |\n|----------|----------|\n"
            f"| LUTs | ~{150 + n_regs * 20 + (200 if has_spi else 0)} |\n"
            f"| FFs | ~{n_regs * 16 + 50 + (60 if has_spi else 0)} |\n"
            f"| BRAM | 0 |\n"
            f"| DSP | 0 |\n"
        )

        return {
            "rtl/fpga_top.v": verilog,
            "rtl/fpga_testbench.v": testbench,
            "rtl/constraints.xdc": xdc,
            "fpga_design_report.md": report,
        }

    # ------------------------------------------------------------------ #
    # Helper
    # ------------------------------------------------------------------ #


    def _build_skeleton_vhdl(self, project_name: str, safe_name: str, glr: str) -> Dict[str, str]:
        """Deterministic VHDL skeleton mirror of the Verilog one.

        Emits an entity + architecture for the top, a tb wrapping it, and
        a Vivado XDC. Designed so that switching hdl_language between
        'verilog' and 'vhdl' produces functionally equivalent designs -
        same register addresses, same default values, same testbench
        scenarios.
        """
        module = re.sub(r"[^a-z0-9_]", "_", safe_name.lower()) or "fpga_top"
        glr_l  = (glr or "").lower()
        clk_mhz = 100
        m = re.search(r"(\d+)\s*mhz", glr_l)
        if m:
            clk_mhz = int(m.group(1))
        clk_period = round(1000.0 / clk_mhz, 3)

        has_spi  = "spi"  in glr_l
        has_adc  = "adc"  in glr_l or "lvds" in glr_l
        has_uart = "uart" in glr_l or "serial" in glr_l

        # Register defaults - kept in sync with _build_skeleton_verilog.
        regs = [
            ("BOARD_ID",     "x\"000\"", "RO", "x\"0001\"", "Board identification code"),
            ("BOARD_VERSION","x\"001\"", "RO", "x\"0010\"", "Hardware version"),
            ("CTRL",         "x\"002\"", "RW", "x\"0000\"", "Master control"),
            ("STATUS",       "x\"003\"", "RO", None,          "Status flags"),
            ("VERSION",      "x\"004\"", "RO", "x\"0100\"", "Firmware version"),
            ("SCRATCHPAD",   "x\"005\"", "RW", "x\"0000\"", "R/W test register"),
        ]

        v = []
        v.append(f"-- ============================================================")
        v.append(f"-- Entity   : {module}_top")
        v.append(f"-- Project  : {project_name}")
        v.append(f"-- Clock    : {clk_mhz} MHz ({clk_period} ns period)")
        v.append(f"-- Source   : Silicon to Software (S2S) v2 (auto-generated, VHDL)")
        v.append(f"-- ============================================================")
        v.append("library ieee;")
        v.append("use ieee.std_logic_1164.all;")
        v.append("use ieee.numeric_std.all;")
        v.append("")
        v.append(f"entity {module}_top is")
        v.append("    port (")
        v.append("        clk        : in  std_logic;")
        v.append("        rst_n      : in  std_logic;")
        v.append("        reg_addr   : in  std_logic_vector(15 downto 0);")
        v.append("        reg_wdata  : in  std_logic_vector(15 downto 0);")
        v.append("        reg_rdata  : out std_logic_vector(15 downto 0);")
        v.append("        reg_wr     : in  std_logic;")
        v.append("        reg_rd     : in  std_logic;")
        v.append("        irq_out    : out std_logic;")
        v.append("        busy       : out std_logic;")
        v.append("        error_flag : out std_logic" + (";" if has_spi or has_adc or has_uart else ""))
        if has_spi:
            v.append("        ; spi_clk    : out std_logic")
            v.append("        ; spi_mosi   : out std_logic")
            v.append("        ; spi_miso   : in  std_logic")
            v.append("        ; spi_cs_n   : out std_logic_vector(3 downto 0)")
        if has_adc:
            v.append("        ; adc_data   : in  std_logic_vector(15 downto 0)")
            v.append("        ; adc_data_v : in  std_logic")
            v.append("        ; adc_sync   : out std_logic")
        if has_uart:
            v.append("        ; uart_rxd   : in  std_logic")
            v.append("        ; uart_txd   : out std_logic")
        v.append("    );")
        v.append(f"end entity {module}_top;")
        v.append("")
        v.append(f"architecture rtl of {module}_top is")
        v.append("    -- Register address constants")
        for name, addr, _rw, _reset, _desc in regs:
            v.append(f"    constant ADDR_{name:<14}: std_logic_vector(11 downto 0) := {addr};")
        v.append("")
        v.append("    -- Register storage")
        v.append("    signal ctrl_r       : std_logic_vector(15 downto 0) := (others => '0');")
        v.append("    signal status_r     : std_logic_vector(15 downto 0) := (others => '0');")
        v.append("    signal scratchpad_r : std_logic_vector(15 downto 0) := (others => '0');")
        v.append("    signal busy_r       : std_logic := '0';")
        v.append("    signal irq_r        : std_logic := '0';")
        v.append("begin")
        v.append("    -- Register write")
        v.append("    process (clk)")
        v.append("    begin")
        v.append("        if rising_edge(clk) then")
        v.append("            if rst_n = '0' then")
        v.append("                ctrl_r       <= (others => '0');")
        v.append("                scratchpad_r <= (others => '0');")
        v.append("            elsif reg_wr = '1' then")
        v.append("                case reg_addr(11 downto 0) is")
        v.append("                    when ADDR_CTRL       => ctrl_r       <= reg_wdata;")
        v.append("                    when ADDR_SCRATCHPAD => scratchpad_r <= reg_wdata;")
        v.append("                    when others => null;")
        v.append("                end case;")
        v.append("            end if;")
        v.append("        end if;")
        v.append("    end process;")
        v.append("")
        v.append("    -- Register read")
        v.append("    process (clk)")
        v.append("    begin")
        v.append("        if rising_edge(clk) then")
        v.append("            if rst_n = '0' then")
        v.append("                reg_rdata <= (others => '0');  -- Idle / no read in flight")
        v.append("            elsif reg_rd = '1' then")
        v.append("                case reg_addr(11 downto 0) is")
        v.append("                    when ADDR_BOARD_ID      => reg_rdata <= x\"0001\";")
        v.append("                    when ADDR_BOARD_VERSION => reg_rdata <= x\"0010\";")
        v.append("                    when ADDR_CTRL          => reg_rdata <= ctrl_r;")
        v.append("                    when ADDR_STATUS        => reg_rdata <= status_r;")
        v.append("                    when ADDR_VERSION       => reg_rdata <= x\"0100\";")
        v.append("                    when ADDR_SCRATCHPAD    => reg_rdata <= scratchpad_r;")
        v.append("                    when others             => reg_rdata <= (others => '0');  -- Unmapped: read-as-zero")
        v.append("                end case;")
        v.append("            end if;")
        v.append("        end if;")
        v.append("    end process;")
        v.append("")
        v.append("    -- Status / control wiring")
        v.append("    busy       <= busy_r;")
        v.append("    irq_out    <= irq_r;")
        v.append("    error_flag <= '0';")
        v.append("    status_r   <= x\"00\" & x\"0\" & \"000\" & busy_r;  -- bit0 = busy")
        v.append("end architecture rtl;")
        verilog = chr(10).join(v)

        # Testbench
        tb = []
        tb.append(f"-- Testbench : {module}_top_tb (VHDL)")
        tb.append(f"-- Project   : {project_name}")
        tb.append("library ieee;")
        tb.append("use ieee.std_logic_1164.all;")
        tb.append("use ieee.numeric_std.all;")
        tb.append("")
        tb.append(f"entity {module}_top_tb is end entity;")
        tb.append("")
        tb.append(f"architecture sim of {module}_top_tb is")
        tb.append("    signal clk        : std_logic := '0';")
        tb.append("    signal rst_n      : std_logic := '0';")
        tb.append("    signal reg_addr   : std_logic_vector(15 downto 0) := (others => '0');")
        tb.append("    signal reg_wdata  : std_logic_vector(15 downto 0) := (others => '0');")
        tb.append("    signal reg_rdata  : std_logic_vector(15 downto 0);")
        tb.append("    signal reg_wr     : std_logic := '0';")
        tb.append("    signal reg_rd     : std_logic := '0';")
        tb.append("    signal irq_out    : std_logic;")
        tb.append("    signal busy       : std_logic;")
        tb.append("    signal error_flag : std_logic;")
        tb.append(f"    constant CLK_PERIOD : time := {clk_period} ns;")
        tb.append("begin")
        tb.append(f"    dut: entity work.{module}_top port map (")
        tb.append("        clk=>clk, rst_n=>rst_n,")
        tb.append("        reg_addr=>reg_addr, reg_wdata=>reg_wdata,")
        tb.append("        reg_rdata=>reg_rdata, reg_wr=>reg_wr, reg_rd=>reg_rd,")
        tb.append("        irq_out=>irq_out, busy=>busy, error_flag=>error_flag")
        tb.append("    );")
        tb.append("    clk <= not clk after CLK_PERIOD/2;")
        tb.append("    process")
        tb.append("    begin")
        tb.append("        wait for 5 * CLK_PERIOD;")
        tb.append("        rst_n <= '1';")
        tb.append("        wait for 2 * CLK_PERIOD;")
        tb.append("        -- T1: VERSION register read")
        tb.append("        reg_addr <= x\"0004\"; reg_rd <= '1'; wait for CLK_PERIOD; reg_rd <= '0';")
        tb.append("        wait for CLK_PERIOD;")
        tb.append("        assert reg_rdata = x\"0100\" report \"VERSION read mismatch\" severity error;")
        tb.append("        -- T2: SCRATCHPAD R/W")
        tb.append("        reg_addr <= x\"0005\"; reg_wdata <= x\"CAFE\"; reg_wr <= '1';")
        tb.append("        wait for CLK_PERIOD; reg_wr <= '0'; wait for CLK_PERIOD;")
        tb.append("        reg_rd <= '1'; wait for CLK_PERIOD; reg_rd <= '0'; wait for CLK_PERIOD;")
        tb.append("        assert reg_rdata = x\"CAFE\" report \"SCRATCH read mismatch\" severity error;")
        tb.append("        report \"VHDL skeleton testbench complete\";")
        tb.append("        wait;")
        tb.append("    end process;")
        tb.append("end architecture;")
        testbench = chr(10).join(tb)

        # XDC - identical shape to the Verilog skeleton's
        xdc_lines = [
            f"# Constraints : {project_name} (VHDL)",
            f"# Target      : xc7a35tcpg236-1 (Artix-7)",
            f"create_clock -period {clk_period:.3f} -name clk -waveform {{0 {clk_period/2:.3f}}} [get_ports clk]",
        ]
        xdc = chr(10).join(xdc_lines)

        return {
            "rtl/fpga_top.vhd":       verilog,
            "rtl/fpga_testbench.vhd": testbench,
            "rtl/constraints.xdc":    xdc,
            "fpga_design_report.md":  f"# FPGA Design Report (VHDL skeleton)\n## {project_name}\n\n"
                                      f"Module `{module}_top` emitted as VHDL-2008. Clock {clk_mhz} MHz.\n",
        }

    def _load_file(self, path: Path) -> str:
        if path.exists():
            try:
                return path.read_text(encoding="utf-8")
            except Exception:
                pass
        return ""
