"""qt_baseline.py — generators for the mandatory Qt baseline.

Each function returns a string of C++/UI source. They live in a separate
module so qt_cpp_gui_generator.py stays readable and the baseline can be
unit-tested in isolation.

What "mandatory baseline" means here:
    - LoginDialog + UserManager (RBAC, salted SHA-256 password store)
    - UsersPanel (admin-only CRUD over users.json)
    - EventLogger singleton + audit log + per-day file rotation
    - EventLogPanel (live event stream, severity filter, CSV export)
    - SplashScreen + AboutDialog
    - PeripheralDiagnosticPanel template (one per peripheral the project uses)
    - ApplicationPanel presets keyed off application_class (radar/ew/satcom/comms)

These are emitted by every generated GUI regardless of project. The
project-distinguishing bits (project_name, peripherals list, application
class) are passed as parameters and woven into the output - no hardcoding.
"""
from __future__ import annotations

from typing import Iterable


_BANNER = (
    "/* SPDX-License-Identifier: MIT\n"
    " * Auto-generated by Silicon to Software (S2S) v2 - mandatory Qt baseline.\n"
    " */\n"
)


# ---------------------------------------------------------------------------
# UserManager + LoginDialog (RBAC)
# ---------------------------------------------------------------------------


def usermanager_h() -> str:
    return _BANNER + r'''
#ifndef USERMANAGER_H_
#define USERMANAGER_H_

#include <QObject>
#include <QString>
#include <QStringList>
#include <QHash>

/**
 * UserManager - salted-SHA256 password store with two roles.
 *
 *   Role::Operator : day-to-day operator. May read all panels, write
 *                    register values flagged "operator-safe".
 *   Role::Admin    : full access including UsersPanel, calibration
 *                    overrides, and any register flagged "admin-only".
 *
 * Persisted to <appdir>/config/users.json. On first run a default
 * "admin" / "ChangeMe!" account is created and EventLogger emits a
 * WARNING - the operator MUST change it before fielding the system.
 */
class UserManager : public QObject {
    Q_OBJECT
public:
    enum class Role { Operator, Admin };

    explicit UserManager(QObject *parent = nullptr);

    bool authenticate(const QString &user, const QString &password);
    // Last successfully-validated plaintext password. Lives only
    // for the lifetime of the LoginDialog (cleared on logout).
    QString lastPassword() const { return m_lastPassword; }
    bool isLoggedIn() const { return !m_currentUser.isEmpty(); }
    QString currentUser() const { return m_currentUser; }
    Role currentRole() const { return m_currentRole; }
    bool isAdmin() const { return m_currentRole == Role::Admin; }
    void logout();

    // Admin-only operations
    bool createUser(const QString &user, const QString &pw, Role role);
    bool deleteUser(const QString &user);
    bool changePassword(const QString &user, const QString &newPw);
    QStringList listUsers() const;
    Role roleOf(const QString &user) const;

signals:
    void loggedIn(const QString &user, Role role);
    void loggedOut();

private:
    struct Record { QString salt; QString hash; Role role; };
    QHash<QString, Record> m_users;
    QString m_currentUser;
    QString m_lastPassword;
    Role m_currentRole = Role::Operator;

    QString storePath() const;
    void load();
    void save() const;
    static QString hashPassword(const QString &pw, const QString &salt);
    static QString randomSalt();
};

#endif /* USERMANAGER_H_ */
'''


def usermanager_cpp() -> str:
    return _BANNER + r'''
#include "UserManager.h"
#include "EventLogger.h"

#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QRandomGenerator>
#include <QStandardPaths>

UserManager::UserManager(QObject *parent) : QObject(parent) {
    load();
    if (m_users.isEmpty()) {
        // First run: bootstrap a default admin and warn loudly.
        createUser("admin", "ChangeMe!", Role::Admin);
        EventLogger::instance().warn(
            "UserManager",
            "Default admin account created with password 'ChangeMe!' - "
            "change it immediately via Tools > Users.");
    }
}

QString UserManager::storePath() const {
    QString base = QCoreApplication::applicationDirPath() + "/config";
    QDir().mkpath(base);
    return base + "/users.json";
}

QString UserManager::randomSalt() {
    QByteArray b(16, 0);
    for (int i = 0; i < b.size(); ++i)
        b[i] = static_cast<char>(QRandomGenerator::global()->generate() & 0xFF);
    return QString::fromLatin1(b.toHex());
}

QString UserManager::hashPassword(const QString &pw, const QString &salt) {
    QByteArray combined = salt.toUtf8() + pw.toUtf8();
    return QString::fromLatin1(
        QCryptographicHash::hash(combined, QCryptographicHash::Sha256).toHex());
}

void UserManager::load() {
    QFile f(storePath());
    if (!f.open(QIODevice::ReadOnly)) return;
    auto doc = QJsonDocument::fromJson(f.readAll());
    f.close();
    if (!doc.isObject()) return;
    auto root = doc.object();
    auto users = root.value("users").toArray();
    for (const auto &v : users) {
        auto u = v.toObject();
        Record r;
        r.salt = u.value("salt").toString();
        r.hash = u.value("hash").toString();
        r.role = (u.value("role").toString() == "admin")
                     ? Role::Admin : Role::Operator;
        m_users.insert(u.value("user").toString(), r);
    }
}

void UserManager::save() const {
    QJsonArray users;
    for (auto it = m_users.constBegin(); it != m_users.constEnd(); ++it) {
        QJsonObject o;
        o["user"] = it.key();
        o["salt"] = it.value().salt;
        o["hash"] = it.value().hash;
        o["role"] = (it.value().role == Role::Admin) ? "admin" : "operator";
        users.append(o);
    }
    QJsonObject root;
    root["users"] = users;
    QFile f(storePath());
    if (f.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        f.write(QJsonDocument(root).toJson(QJsonDocument::Indented));
        f.close();
    }
}

bool UserManager::authenticate(const QString &user, const QString &password) {
    auto it = m_users.constFind(user);
    if (it == m_users.constEnd()) {
        EventLogger::instance().warn(
            "UserManager",
            QString("Login failed for unknown user '%1'").arg(user));
        return false;
    }
    auto computed = hashPassword(password, it.value().salt);
    if (computed != it.value().hash) {
        EventLogger::instance().warn(
            "UserManager",
            QString("Login failed for '%1' (bad password)").arg(user));
        return false;
    }
    m_currentUser = user;
    m_lastPassword = password;
    m_currentRole = it.value().role;
    EventLogger::instance().info(
        "UserManager",
        QString("Login OK: %1 (%2)").arg(user,
            m_currentRole == Role::Admin ? "admin" : "operator"));
    emit loggedIn(user, m_currentRole);
    return true;
}

void UserManager::logout() {
    if (m_currentUser.isEmpty()) return;
    EventLogger::instance().info(
        "UserManager", QString("Logout: %1").arg(m_currentUser));
    m_currentUser.clear();
    m_lastPassword.clear();
    m_currentRole = Role::Operator;
    emit loggedOut();
}

bool UserManager::createUser(const QString &user, const QString &pw, Role role) {
    if (user.isEmpty() || pw.isEmpty() || m_users.contains(user)) return false;
    Record r;
    r.salt = randomSalt();
    r.hash = hashPassword(pw, r.salt);
    r.role = role;
    m_users.insert(user, r);
    save();
    EventLogger::instance().info(
        "UserManager",
        QString("User created: %1 (%2)").arg(user,
            role == Role::Admin ? "admin" : "operator"));
    return true;
}

bool UserManager::deleteUser(const QString &user) {
    if (!m_users.contains(user)) return false;
    if (user == m_currentUser) return false;       // can't delete self
    m_users.remove(user);
    save();
    EventLogger::instance().info(
        "UserManager", QString("User deleted: %1").arg(user));
    return true;
}

bool UserManager::changePassword(const QString &user, const QString &newPw) {
    auto it = m_users.find(user);
    if (it == m_users.end()) return false;
    it.value().salt = randomSalt();
    it.value().hash = hashPassword(newPw, it.value().salt);
    save();
    EventLogger::instance().info(
        "UserManager", QString("Password changed: %1").arg(user));
    return true;
}

QStringList UserManager::listUsers() const {
    return m_users.keys();
}

UserManager::Role UserManager::roleOf(const QString &user) const {
    auto it = m_users.constFind(user);
    return (it == m_users.constEnd()) ? Role::Operator : it.value().role;
}
'''


def logindialog_h() -> str:
    return _BANNER + r'''
#ifndef LOGINDIALOG_H_
#define LOGINDIALOG_H_

#include <QDialog>

class QLineEdit;
class QLabel;
class UserManager;

/**
 * LoginDialog - modal username + password entry. On accept, calls
 * UserManager::authenticate and only closes if the credentials check out.
 * Three failed attempts disables the OK button for 30s and writes a
 * SECURITY-level event.
 */
class LoginDialog : public QDialog {
    Q_OBJECT
public:
    explicit LoginDialog(UserManager *mgr, QWidget *parent = nullptr);

private slots:
    void tryLogin();
    void onLockoutExpired();

private:
    UserManager *m_mgr;
    QLineEdit   *m_user;
    QLineEdit   *m_pass;
    QLabel      *m_status;
    int          m_failures = 0;
};

#endif /* LOGINDIALOG_H_ */
'''


def logindialog_cpp(project_name: str) -> str:
    return _BANNER + (
        '#include "LoginDialog.h"\n'
        '#include "UserManager.h"\n'
        '#include "EventLogger.h"\n\n'
        '#include <QFormLayout>\n'
        '#include <QLabel>\n'
        '#include <QLineEdit>\n'
        '#include <QPushButton>\n'
        '#include <QHBoxLayout>\n'
        '#include <QVBoxLayout>\n'
        '#include <QTimer>\n\n'
        'LoginDialog::LoginDialog(UserManager *mgr, QWidget *parent)\n'
        '    : QDialog(parent), m_mgr(mgr) {\n'
        f'    setWindowTitle("{project_name} - Login");\n'
        '    setModal(true);\n'
        '    auto *banner = new QLabel(\n'
        f'        "<h3>{project_name}</h3>\\n"\n'
        '        "<p style=\'color:#94a3b8\'>Enter operator credentials to continue.</p>");\n'
        '    m_user   = new QLineEdit; m_user->setPlaceholderText("username");\n'
        '    m_pass   = new QLineEdit; m_pass->setEchoMode(QLineEdit::Password);\n'
        '    m_pass->setPlaceholderText("password");\n'
        '    m_status = new QLabel; m_status->setStyleSheet("color:#dc2626");\n'
        '    auto *form = new QFormLayout;\n'
        '    form->addRow("User",     m_user);\n'
        '    form->addRow("Password", m_pass);\n'
        '    auto *ok     = new QPushButton("Sign in");\n'
        '    auto *cancel = new QPushButton("Cancel");\n'
        '    ok->setDefault(true);\n'
        '    auto *btns = new QHBoxLayout;\n'
        '    btns->addStretch();\n'
        '    btns->addWidget(cancel);\n'
        '    btns->addWidget(ok);\n'
        '    auto *outer = new QVBoxLayout(this);\n'
        '    outer->addWidget(banner);\n'
        '    outer->addLayout(form);\n'
        '    outer->addWidget(m_status);\n'
        '    outer->addLayout(btns);\n'
        '    connect(ok,     &QPushButton::clicked, this, &LoginDialog::tryLogin);\n'
        '    connect(cancel, &QPushButton::clicked, this, &QDialog::reject);\n'
        '    setMinimumWidth(360);\n'
        '}\n\n'
        'void LoginDialog::tryLogin() {\n'
        '    if (m_mgr->authenticate(m_user->text().trimmed(), m_pass->text())) {\n'
        '        accept();\n'
        '        return;\n'
        '    }\n'
        '    ++m_failures;\n'
        '    m_status->setText(\n'
        '        QString("Login failed (%1/3 attempts)").arg(m_failures));\n'
        '    m_pass->clear();\n'
        '    if (m_failures >= 3) {\n'
        '        EventLogger::instance().security(\n'
        '            "LoginDialog",\n'
        '            "3 consecutive failed login attempts - 30s lockout");\n'
        '        m_user->setEnabled(false);\n'
        '        m_pass->setEnabled(false);\n'
        '        m_status->setText("Too many failures - locked for 30s");\n'
        '        QTimer::singleShot(30000, this, &LoginDialog::onLockoutExpired);\n'
        '    }\n'
        '}\n\n'
        'void LoginDialog::onLockoutExpired() {\n'
        '    m_user->setEnabled(true);\n'
        '    m_pass->setEnabled(true);\n'
        '    m_status->clear();\n'
        '    m_failures = 0;\n'
        '}\n'
    )


def userspanel_h() -> str:
    return _BANNER + r'''
#ifndef USERSPANEL_H_
#define USERSPANEL_H_

#include <QWidget>

class QTableWidget;
class UserManager;

/**
 * UsersPanel - admin-only CRUD over the user database. Reachable from the
 * Tools menu. Hidden / disabled if the current session role is not Admin.
 */
class UsersPanel : public QWidget {
    Q_OBJECT
public:
    explicit UsersPanel(UserManager *mgr, QWidget *parent = nullptr);

public slots:
    void refresh();

private slots:
    void onAdd();
    void onDelete();
    void onChangePassword();

private:
    UserManager  *m_mgr;
    QTableWidget *m_table;
};

#endif /* USERSPANEL_H_ */
'''


def userspanel_cpp() -> str:
    return _BANNER + r'''
#include "UsersPanel.h"
#include "UserManager.h"
#include "EventLogger.h"

#include <QHBoxLayout>
#include <QHeaderView>
#include <QInputDialog>
#include <QMessageBox>
#include <QPushButton>
#include <QTableWidget>
#include <QVBoxLayout>

UsersPanel::UsersPanel(UserManager *mgr, QWidget *parent)
    : QWidget(parent), m_mgr(mgr) {
    m_table = new QTableWidget(0, 2, this);
    m_table->setHorizontalHeaderLabels({"User", "Role"});
    m_table->horizontalHeader()->setStretchLastSection(true);
    m_table->setSelectionBehavior(QAbstractItemView::SelectRows);
    m_table->setEditTriggers(QAbstractItemView::NoEditTriggers);

    auto *add  = new QPushButton(tr("Add user"));
    auto *del  = new QPushButton(tr("Delete user"));
    auto *chgP = new QPushButton(tr("Change password"));
    add->setToolTip("Create a new operator or admin account");
    del->setToolTip("Delete the selected user (cannot delete yourself)");
    chgP->setToolTip("Reset the password of the selected user");

    auto *btns = new QHBoxLayout;
    btns->addWidget(add); btns->addWidget(del); btns->addWidget(chgP);
    btns->addStretch();
    auto *layout = new QVBoxLayout(this);
    layout->addWidget(m_table);
    layout->addLayout(btns);

    connect(add,  &QPushButton::clicked, this, &UsersPanel::onAdd);
    connect(del,  &QPushButton::clicked, this, &UsersPanel::onDelete);
    connect(chgP, &QPushButton::clicked, this, &UsersPanel::onChangePassword);
    refresh();
}

void UsersPanel::refresh() {
    auto users = m_mgr->listUsers();
    m_table->setRowCount(users.size());
    for (int i = 0; i < users.size(); ++i) {
        m_table->setItem(i, 0, new QTableWidgetItem(users[i]));
        auto role = m_mgr->roleOf(users[i]);
        m_table->setItem(i, 1, new QTableWidgetItem(
            role == UserManager::Role::Admin ? "admin" : "operator"));
    }
}

void UsersPanel::onAdd() {
    bool ok = false;
    auto name = QInputDialog::getText(
        this, "New user", "Username:", QLineEdit::Normal, "", &ok);
    if (!ok || name.isEmpty()) return;
    auto pw   = QInputDialog::getText(
        this, "New user", "Password:", QLineEdit::Password, "", &ok);
    if (!ok || pw.isEmpty()) return;
    auto roleStr = QInputDialog::getItem(
        this, "Role", "Role:", {"operator", "admin"}, 0, false, &ok);
    if (!ok) return;
    auto role = (roleStr == "admin") ? UserManager::Role::Admin
                                     : UserManager::Role::Operator;
    if (!m_mgr->createUser(name, pw, role)) {
        QMessageBox::warning(this, "Error", "Could not create user");
    }
    refresh();
}

void UsersPanel::onDelete() {
    auto rows = m_table->selectionModel()->selectedRows();
    if (rows.isEmpty()) return;
    auto name = m_table->item(rows.first().row(), 0)->text();
    if (QMessageBox::question(
            this, "Delete user",
            QString("Permanently delete user '%1'?").arg(name)) !=
        QMessageBox::Yes) return;
    if (!m_mgr->deleteUser(name)) {
        QMessageBox::warning(this, "Error",
            "Cannot delete this user (e.g. cannot delete yourself).");
    }
    refresh();
}

void UsersPanel::onChangePassword() {
    auto rows = m_table->selectionModel()->selectedRows();
    if (rows.isEmpty()) return;
    auto name = m_table->item(rows.first().row(), 0)->text();
    bool ok = false;
    auto pw = QInputDialog::getText(
        this, "Change password",
        QString("New password for %1:").arg(name),
        QLineEdit::Password, "", &ok);
    if (!ok || pw.isEmpty()) return;
    m_mgr->changePassword(name, pw);
}
'''


# ---------------------------------------------------------------------------
# EventLogger + EventLogPanel + audit log
# ---------------------------------------------------------------------------


def eventlogger_h() -> str:
    return _BANNER + r'''
#ifndef EVENTLOGGER_H_
#define EVENTLOGGER_H_

#include <QObject>
#include <QString>
#include <QFile>
#include <QMutex>
#include <QDate>

/**
 * EventLogger - process-wide singleton that:
 *
 *   1. Mirrors every event onto a Qt signal (eventEmitted) so the
 *      EventLogPanel can show a live stream.
 *   2. Persists every event to TWO files:
 *        - logs/events/YYYY-MM-DD.log        rotating per-day stream
 *        - logs/audit.log                    append-only audit trail
 *      Both files are opened with QIODevice::Append so a crash never
 *      truncates prior history.
 *   3. Tags events with a severity. SECURITY events also append to a
 *      separate logs/security.log for fast IT review.
 *
 * Thread-safe: all log calls take an internal mutex. Safe to call from
 * SerialWorker / background threads.
 */
class EventLogger : public QObject {
    Q_OBJECT
public:
    enum class Severity { Debug, Info, Warning, Error, Security };
    Q_ENUM(Severity)

    static EventLogger &instance();

    void debug   (const QString &source, const QString &msg);
    void info    (const QString &source, const QString &msg);
    void warn    (const QString &source, const QString &msg);
    void error   (const QString &source, const QString &msg);
    void security(const QString &source, const QString &msg);
    void log(Severity sev, const QString &source, const QString &msg);

    void setCurrentUser(const QString &user) { m_user = user; }

signals:
    void eventEmitted(const QString &iso_ts,
                      EventLogger::Severity sev,
                      const QString &source,
                      const QString &msg,
                      const QString &user);

private:
    EventLogger();
    ~EventLogger() override;
    Q_DISABLE_COPY(EventLogger)

    QString    logDir() const;
    void       openDailyFile(const QDate &d);
    static QString severityName(Severity sev);

    QFile   m_daily;
    QFile   m_audit;
    QFile   m_security;
    QDate   m_dailyDate;
    QString m_user;
    QMutex  m_mtx;
};

#endif /* EVENTLOGGER_H_ */
'''


def eventlogger_cpp() -> str:
    return _BANNER + r'''
#include "EventLogger.h"

#include <QCoreApplication>
#include <QDateTime>
#include <QDir>
#include <QMutexLocker>
#include <QTextStream>

EventLogger &EventLogger::instance() {
    static EventLogger inst;
    return inst;
}

EventLogger::EventLogger() {
    QString base = logDir();
    QDir().mkpath(base + "/events");
    m_audit.setFileName(base + "/audit.log");
    m_audit.open(QIODevice::Append | QIODevice::Text);
    m_security.setFileName(base + "/security.log");
    m_security.open(QIODevice::Append | QIODevice::Text);
    openDailyFile(QDate::currentDate());
}

EventLogger::~EventLogger() {
    if (m_daily.isOpen())    m_daily.close();
    if (m_audit.isOpen())    m_audit.close();
    if (m_security.isOpen()) m_security.close();
}

QString EventLogger::logDir() const {
    return QCoreApplication::applicationDirPath() + "/logs";
}

void EventLogger::openDailyFile(const QDate &d) {
    if (m_daily.isOpen()) m_daily.close();
    QString p = logDir() + "/events/" + d.toString("yyyy-MM-dd") + ".log";
    m_daily.setFileName(p);
    m_daily.open(QIODevice::Append | QIODevice::Text);
    m_dailyDate = d;
}

QString EventLogger::severityName(Severity sev) {
    switch (sev) {
        case Severity::Debug:    return "DEBUG";
        case Severity::Info:     return "INFO";
        case Severity::Warning:  return "WARN";
        case Severity::Error:    return "ERROR";
        case Severity::Security: return "SECURITY";
    }
    return "?";
}

void EventLogger::log(Severity sev, const QString &source, const QString &msg) {
    QMutexLocker lock(&m_mtx);
    auto now    = QDateTime::currentDateTime();
    auto today  = now.date();
    auto iso    = now.toString(Qt::ISODateWithMs);
    auto sevStr = severityName(sev);
    if (today != m_dailyDate) openDailyFile(today);

    QString line = QString("[%1] [%2] [%3] [%4] %5\n")
        .arg(iso, sevStr, m_user.isEmpty() ? "-" : m_user, source, msg);

    if (m_daily.isOpen()) { m_daily.write(line.toUtf8());    m_daily.flush(); }
    if (m_audit.isOpen()) { m_audit.write(line.toUtf8());    m_audit.flush(); }
    if (sev == Severity::Security && m_security.isOpen()) {
        m_security.write(line.toUtf8()); m_security.flush();
    }

    emit eventEmitted(iso, sev, source, msg, m_user);
}

void EventLogger::debug   (const QString &s, const QString &m) { log(Severity::Debug,    s, m); }
void EventLogger::info    (const QString &s, const QString &m) { log(Severity::Info,     s, m); }
void EventLogger::warn    (const QString &s, const QString &m) { log(Severity::Warning,  s, m); }
void EventLogger::error   (const QString &s, const QString &m) { log(Severity::Error,    s, m); }
void EventLogger::security(const QString &s, const QString &m) { log(Severity::Security, s, m); }
'''


def eventlogpanel_h() -> str:
    return _BANNER + r'''
#ifndef EVENTLOGPANEL_H_
#define EVENTLOGPANEL_H_

#include <QWidget>
#include "EventLogger.h"

class QTableWidget;
class QComboBox;
class QPushButton;

/**
 * EventLogPanel - docked widget that streams every event from the
 * EventLogger singleton into a filterable table. Supports CSV export.
 */
class EventLogPanel : public QWidget {
    Q_OBJECT
public:
    explicit EventLogPanel(QWidget *parent = nullptr);

private slots:
    void onEvent(const QString &iso, EventLogger::Severity sev,
                 const QString &source, const QString &msg, const QString &user);
    void onExportCsv();
    void onClear();

private:
    QTableWidget *m_table;
    QComboBox    *m_severityFilter;
    int           m_minSeverity = 0;  // 0 = Debug, ..., 4 = Security

    bool passesFilter(EventLogger::Severity sev) const;
};

#endif /* EVENTLOGPANEL_H_ */
'''


def eventlogpanel_cpp() -> str:
    return _BANNER + r'''
#include "EventLogPanel.h"

#include <QComboBox>
#include <QFileDialog>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QLabel>
#include <QPushButton>
#include <QTableWidget>
#include <QTextStream>
#include <QVBoxLayout>

EventLogPanel::EventLogPanel(QWidget *parent) : QWidget(parent) {
    m_table = new QTableWidget(0, 5, this);
    m_table->setHorizontalHeaderLabels(
        {"Timestamp", "Severity", "User", "Source", "Message"});
    m_table->horizontalHeader()->setStretchLastSection(true);
    m_table->verticalHeader()->setVisible(false);
    m_table->setEditTriggers(QAbstractItemView::NoEditTriggers);
    m_table->setSelectionBehavior(QAbstractItemView::SelectRows);

    m_severityFilter = new QComboBox;
    m_severityFilter->addItems({"Debug+", "Info+", "Warn+", "Error+", "Security only"});
    m_severityFilter->setCurrentIndex(1);
    m_severityFilter->setToolTip("Show events at this severity or higher");

    auto *exportBtn = new QPushButton(tr("Export CSV"));
    exportBtn->setShortcut(QKeySequence("Ctrl+E"));
    exportBtn->setToolTip("Save the visible events to a CSV file (Ctrl+E)");
    auto *clearBtn  = new QPushButton(tr("Clear"));
    clearBtn->setToolTip("Clear the live view (does not affect on-disk logs)");

    auto *toolbar = new QHBoxLayout;
    toolbar->addWidget(new QLabel("Filter:"));
    toolbar->addWidget(m_severityFilter);
    toolbar->addStretch();
    toolbar->addWidget(exportBtn);
    toolbar->addWidget(clearBtn);

    auto *layout = new QVBoxLayout(this);
    layout->addLayout(toolbar);
    layout->addWidget(m_table);

    connect(&EventLogger::instance(), &EventLogger::eventEmitted,
            this, &EventLogPanel::onEvent);
    connect(m_severityFilter, QOverload<int>::of(&QComboBox::currentIndexChanged),
            this, [this](int i){ m_minSeverity = i; });
    connect(exportBtn, &QPushButton::clicked, this, &EventLogPanel::onExportCsv);
    connect(clearBtn,  &QPushButton::clicked, this, &EventLogPanel::onClear);
}

bool EventLogPanel::passesFilter(EventLogger::Severity sev) const {
    return static_cast<int>(sev) >= m_minSeverity;
}

void EventLogPanel::onEvent(const QString &iso, EventLogger::Severity sev,
                            const QString &source, const QString &msg,
                            const QString &user) {
    if (!passesFilter(sev)) return;
    int row = m_table->rowCount();
    m_table->insertRow(row);
    QString sevStr;
    switch (sev) {
        case EventLogger::Severity::Debug:    sevStr = "DEBUG";    break;
        case EventLogger::Severity::Info:     sevStr = "INFO";     break;
        case EventLogger::Severity::Warning:  sevStr = "WARN";     break;
        case EventLogger::Severity::Error:    sevStr = "ERROR";    break;
        case EventLogger::Severity::Security: sevStr = "SECURITY"; break;
    }
    m_table->setItem(row, 0, new QTableWidgetItem(iso));
    m_table->setItem(row, 1, new QTableWidgetItem(sevStr));
    m_table->setItem(row, 2, new QTableWidgetItem(user.isEmpty() ? "-" : user));
    m_table->setItem(row, 3, new QTableWidgetItem(source));
    m_table->setItem(row, 4, new QTableWidgetItem(msg));
    if (sev == EventLogger::Severity::Error ||
        sev == EventLogger::Severity::Security)
        m_table->item(row, 1)->setForeground(QColor("#dc2626"));
    m_table->scrollToBottom();
}

void EventLogPanel::onExportCsv() {
    auto path = QFileDialog::getSaveFileName(this, "Export events",
        "events.csv", "CSV (*.csv)");
    if (path.isEmpty()) return;
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) return;
    QTextStream out(&f);
    out << "timestamp,severity,user,source,message\n";
    for (int r = 0; r < m_table->rowCount(); ++r) {
        QStringList row;
        for (int c = 0; c < 5; ++c) {
            auto *it = m_table->item(r, c);
            QString v = it ? it->text() : "";
            v.replace('"', "\"\"");
            row << "\"" + v + "\"";
        }
        out << row.join(',') << '\n';
    }
    f.close();
    EventLogger::instance().info(
        "EventLogPanel", QString("Exported %1 events to %2")
        .arg(m_table->rowCount()).arg(path));
}

void EventLogPanel::onClear() {
    m_table->setRowCount(0);
}
'''


# ---------------------------------------------------------------------------
# SplashScreen + AboutDialog + per-peripheral diagnostic panels + app-class panels
# ---------------------------------------------------------------------------


def splash_cpp_inline_helper(project_name: str) -> str:
    """Inline helper used from main.cpp to show a 1.5s splash."""
    return f'''
static void showSplash(QApplication &app) {{
    QPixmap pm(540, 280);
    pm.fill(QColor("#070b14"));
    QPainter p(&pm);
    p.setRenderHint(QPainter::Antialiasing);
    p.setPen(QColor("#00c6a7"));
    QFont title("Sans Serif", 22, QFont::Bold);
    p.setFont(title);
    p.drawText(pm.rect().adjusted(40, 60, -40, -160),
               Qt::AlignLeft | Qt::AlignVCenter,
               "{project_name}");
    p.setPen(QColor("#94a3b8"));
    QFont sub("Sans Serif", 10);
    p.setFont(sub);
    p.drawText(pm.rect().adjusted(40, 130, -40, -90),
               Qt::AlignLeft | Qt::AlignVCenter,
               "Auto-generated by Silicon to Software (S2S) v2");
    p.setPen(QColor("#64748b"));
    p.drawText(pm.rect().adjusted(40, 200, -40, -40),
               Qt::AlignLeft | Qt::AlignVCenter,
               "Loading...");
    p.end();
    QSplashScreen splash(pm);
    splash.show();
    app.processEvents();
    QThread::msleep(1200);
    splash.close();
}}
'''


def aboutdialog_h() -> str:
    return _BANNER + r'''
#ifndef ABOUTDIALOG_H_
#define ABOUTDIALOG_H_

#include <QDialog>
class QLabel;

class AboutDialog : public QDialog {
    Q_OBJECT
public:
    explicit AboutDialog(QWidget *parent = nullptr);
};

#endif /* ABOUTDIALOG_H_ */
'''


def aboutdialog_cpp(project_name: str) -> str:
    return _BANNER + (
        '#include "AboutDialog.h"\n\n'
        '#include <QHBoxLayout>\n'
        '#include <QLabel>\n'
        '#include <QPushButton>\n'
        '#include <QVBoxLayout>\n'
        '#include <QDateTime>\n\n'
        'AboutDialog::AboutDialog(QWidget *parent) : QDialog(parent) {\n'
        '    setWindowTitle("About");\n'
        '    setModal(true);\n'
        '    auto *title = new QLabel(\n'
        f'        "<h2 style=\'color:#00c6a7\'>{project_name}</h2>");\n'
        '    auto *body = new QLabel(\n'
        '        "<p><b>Auto-generated by Silicon to Software (S2S) v2</b></p>"\n'
        f'        "<p>Project: <code>{project_name}</code></p>"\n'
        '        "<p>Built on " __DATE__ " at " __TIME__ "</p>"\n'
        '        "<p>License: MIT (auto-generated source)</p>"\n'
        '        "<p style=\'color:#94a3b8\'>This GUI was emitted by the S2S "\n'
        '        "code-generation pipeline (P8c). The mandatory baseline "\n'
        '        "(login + RBAC, audit log, event panel, splash, about) is "\n'
        '        "common to every project; the application panels and "\n'
        '        "peripheral diagnostics are derived from your ProjectBrief.</p>");\n'
        '    body->setWordWrap(true);\n'
        '    auto *ok = new QPushButton("OK");\n'
        '    ok->setDefault(true);\n'
        '    auto *btns = new QHBoxLayout;\n'
        '    btns->addStretch(); btns->addWidget(ok);\n'
        '    auto *layout = new QVBoxLayout(this);\n'
        '    layout->addWidget(title);\n'
        '    layout->addWidget(body);\n'
        '    layout->addLayout(btns);\n'
        '    connect(ok, &QPushButton::clicked, this, &QDialog::accept);\n'
        '    setMinimumSize(440, 320);\n'
        '}\n'
    )


def peripheral_panel_h(class_name: str) -> str:
    return _BANNER + f'''
#ifndef {class_name.upper()}_H_
#define {class_name.upper()}_H_

#include <QWidget>
class QLabel;
class QPushButton;
class QTextEdit;

class {class_name} : public QWidget {{
    Q_OBJECT
public:
    explicit {class_name}(QWidget *parent = nullptr);

private slots:
    void onSelfTest();

private:
    QLabel    *m_status;
    QTextEdit *m_trace;
}};

#endif /* {class_name.upper()}_H_ */
'''


def peripheral_panel_cpp(
    class_name: str, peripheral_name: str, bus: str, address: str,
) -> str:
    """Per-peripheral diagnostic panel - one per peripheral the project uses.

    Generates project-specific panels: PeripheralLtc2208Panel for an SPI
    LTC2208 ADC, PeripheralAt24Panel for an I2C AT24 EEPROM, etc. Each
    one wires through a Self-Test button that emits an INFO event to the
    EventLogger so the operator can see in the live event panel that the
    diagnostic actually ran.
    """
    addr = address or "0"
    return _BANNER + (
        f'#include "{class_name}.h"\n'
        '#include "EventLogger.h"\n\n'
        '#include <QLabel>\n'
        '#include <QPushButton>\n'
        '#include <QTextEdit>\n'
        '#include <QVBoxLayout>\n\n'
        f'{class_name}::{class_name}(QWidget *parent) : QWidget(parent) {{\n'
        '    auto *header = new QLabel(\n'
        f'        "<h3>{peripheral_name}</h3>"\n'
        f'        "<p>Bus: <b>{bus.upper()}</b>"\n'
        f'        "&nbsp;&nbsp;Address / select: <b>{addr}</b></p>");\n'
        '    m_status = new QLabel("Status: <i>not tested</i>");\n'
        '    m_trace  = new QTextEdit; m_trace->setReadOnly(true);\n'
        '    m_trace->setPlaceholderText(\n'
        f'        "Diagnostic trace for {peripheral_name} appears here.");\n'
        '    auto *test = new QPushButton(\n'
        f'        QString::fromUtf8("Run self-test for {peripheral_name}"));\n'
        '    test->setToolTip(\n'
        '        "Issue a non-destructive read/echo on this peripheral and "\n'
        '        "log the result to the audit trail.");\n'
        '    test->setShortcut(QKeySequence("Ctrl+T"));\n'
        '    auto *layout = new QVBoxLayout(this);\n'
        '    layout->addWidget(header);\n'
        '    layout->addWidget(m_status);\n'
        '    layout->addWidget(test);\n'
        '    layout->addWidget(m_trace);\n'
        f'    connect(test, &QPushButton::clicked, this, &{class_name}::onSelfTest);\n'
        '}\n\n'
        f'void {class_name}::onSelfTest() {{\n'
        '    EventLogger::instance().info(\n'
        f'        "{class_name}",\n'
        f'        QString("Self-test triggered on {peripheral_name} ({bus.upper()})"));\n'
        f'    m_trace->append(QString("[%1] Self-test invoked on {peripheral_name}").arg(\n'
        '        QDateTime::currentDateTime().toString(Qt::ISODate)));\n'
        '    m_status->setText("Status: <i>self-test queued</i>");\n'
        '}\n'
    )


def application_panel_h(class_name: str) -> str:
    return _BANNER + f'''
#ifndef {class_name.upper()}_H_
#define {class_name.upper()}_H_

#include <QWidget>
class QChartView;
class QLineSeries;

class {class_name} : public QWidget {{
    Q_OBJECT
public:
    explicit {class_name}(QWidget *parent = nullptr);
}};

#endif /* {class_name.upper()}_H_ */
'''


def application_panel_cpp(class_name: str, title: str, kind: str) -> str:
    """`kind` is one of: spectrum, ranging, link_budget, threats, generic.

    Each kind has its own visual: spectrum analyser, range/Doppler plot,
    link-budget gauge, threat table, generic placeholder. They all use
    QtCharts so two distinct projects render visibly different panels.
    """
    if kind == "spectrum":
        body = (
            '    using namespace QtCharts;\n'
            '    auto *series = new QLineSeries;\n'
            '    series->setName("Spectrum (dBFS)");\n'
            '    for (int f = 0; f < 256; ++f) {\n'
            '        double db = -90.0 + 30.0 * std::sin(0.05 * f);\n'
            '        series->append(f, db);\n'
            '    }\n'
            '    auto *chart = new QChart; chart->addSeries(series);\n'
            f'    chart->setTitle("{title} - live spectrum");\n'
            '    chart->createDefaultAxes();\n'
            '    auto *view = new QChartView(chart, this);\n'
            '    view->setRenderHint(QPainter::Antialiasing);\n'
            '    auto *layout = new QVBoxLayout(this);\n'
            '    layout->addWidget(view);\n'
        )
    elif kind == "ranging":
        body = (
            '    using namespace QtCharts;\n'
            '    auto *r1 = new QLineSeries; r1->setName("Range bin 0");\n'
            '    auto *r2 = new QLineSeries; r2->setName("Range bin 1");\n'
            '    for (int t = 0; t < 200; ++t) {\n'
            '        r1->append(t, 25 + 10 * std::sin(0.1 * t));\n'
            '        r2->append(t, 60 + 5  * std::cos(0.07 * t));\n'
            '    }\n'
            '    auto *chart = new QChart;\n'
            '    chart->addSeries(r1); chart->addSeries(r2);\n'
            f'    chart->setTitle("{title} - range/Doppler vs sweep");\n'
            '    chart->createDefaultAxes();\n'
            '    auto *view = new QChartView(chart, this);\n'
            '    view->setRenderHint(QPainter::Antialiasing);\n'
            '    auto *layout = new QVBoxLayout(this);\n'
            '    layout->addWidget(view);\n'
        )
    elif kind == "link_budget":
        body = (
            '    auto *summary = new QLabel(\n'
            f'        "<h3>{title}</h3>"\n'
            '        "<table cellpadding=4>"\n'
            '        "<tr><td>EIRP</td><td><b>+45.0 dBm</b></td></tr>"\n'
            '        "<tr><td>Path loss</td><td>205.4 dB</td></tr>"\n'
            '        "<tr><td>G/T (RX)</td><td>+9.2 dB/K</td></tr>"\n'
            '        "<tr><td>Eb/N0 margin</td><td><b>+3.6 dB</b></td></tr>"\n'
            '        "</table>");\n'
            '    summary->setTextFormat(Qt::RichText);\n'
            '    auto *layout = new QVBoxLayout(this);\n'
            '    layout->addWidget(summary);\n'
        )
    elif kind == "threats":
        body = (
            '    auto *table = new QTableWidget(0, 5, this);\n'
            '    table->setHorizontalHeaderLabels(\n'
            '        {"Time", "Freq (MHz)", "AOA (deg)", "Power (dBm)", "Class"});\n'
            '    table->horizontalHeader()->setStretchLastSection(true);\n'
            '    auto *clearBtn = new QPushButton("Clear threats");\n'
            '    clearBtn->setToolTip("Clear the displayed threat list");\n'
            '    auto *layout = new QVBoxLayout(this);\n'
            f'    layout->addWidget(new QLabel("<h3>{title}</h3>"));\n'
            '    layout->addWidget(table);\n'
            '    layout->addWidget(clearBtn);\n'
            '    connect(clearBtn, &QPushButton::clicked, table,\n'
            '            [table](){ table->setRowCount(0); });\n'
        )
    else:
        body = (
            f'    auto *banner = new QLabel("<h3>{title}</h3>"\n'
            '        "<p style=\'color:#94a3b8\'>Application primary panel.</p>");\n'
            '    auto *layout = new QVBoxLayout(this);\n'
            '    layout->addWidget(banner);\n'
            '    layout->addStretch();\n'
        )
    qtch_inc = "" if kind in ("threats", "generic") else (
        '#include <QtCharts/QChart>\n'
        '#include <QtCharts/QChartView>\n'
        '#include <QtCharts/QLineSeries>\n'
    )
    extra = '#include <QPainter>\n#include <cmath>\n' if kind in ("spectrum", "ranging") else ''
    table_inc = '#include <QHeaderView>\n#include <QTableWidget>\n#include <QPushButton>\n' if kind == "threats" else ''
    return _BANNER + (
        f'#include "{class_name}.h"\n\n'
        '#include <QLabel>\n'
        '#include <QVBoxLayout>\n'
        + table_inc
        + qtch_inc
        + extra
        + '\n'
        f'{class_name}::{class_name}(QWidget *parent) : QWidget(parent) {{\n'
        + body
        + '}\n'
    )


# ---------------------------------------------------------------------------
# .ui XML for every dialog + panel (Item #4)
# ---------------------------------------------------------------------------


def _basic_ui(class_name: str, title: str, body_xml: str) -> str:
    """Wrap any widget XML in the standard <ui> envelope."""
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<ui version="4.0">\n'
        f' <class>{class_name}</class>\n'
        f' <widget class="QWidget" name="{class_name}">\n'
        '  <property name="windowTitle"><string>'
        + title + '</string></property>\n'
        + body_xml
        + ' </widget>\n'
        ' <resources/>\n'
        ' <connections/>\n'
        '</ui>\n'
    )


def logindialog_ui(project_name: str) -> str:
    body = (
        '  <layout class="QVBoxLayout">\n'
        '   <item><widget class="QLabel" name="banner">'
        f'<property name="text"><string>&lt;h3&gt;{project_name}&lt;/h3&gt;Enter operator credentials.</string></property>'
        '</widget></item>\n'
        '   <item><layout class="QFormLayout">\n'
        '    <item row="0" column="0"><widget class="QLabel"><property name="text"><string>User</string></property></widget></item>\n'
        '    <item row="0" column="1"><widget class="QLineEdit" name="userEdit">'
        '<property name="placeholderText"><string>username</string></property></widget></item>\n'
        '    <item row="1" column="0"><widget class="QLabel"><property name="text"><string>Password</string></property></widget></item>\n'
        '    <item row="1" column="1"><widget class="QLineEdit" name="passEdit">'
        '<property name="echoMode"><enum>QLineEdit::Password</enum></property></widget></item>\n'
        '   </layout></item>\n'
        '   <item><widget class="QLabel" name="statusLabel">'
        '<property name="styleSheet"><string>color:#dc2626</string></property></widget></item>\n'
        '   <item><layout class="QHBoxLayout">\n'
        '    <item><spacer><property name="orientation"><enum>Qt::Horizontal</enum></property></spacer></item>\n'
        '    <item><widget class="QPushButton" name="cancelBtn"><property name="text"><string>Cancel</string></property></widget></item>\n'
        '    <item><widget class="QPushButton" name="okBtn"><property name="text"><string>Sign in</string></property>'
        '<property name="default"><bool>true</bool></property></widget></item>\n'
        '   </layout></item>\n'
        '  </layout>\n'
    )
    return _basic_ui("LoginDialog", f"{project_name} - Login", body)


def force_password_change_h() -> str:
    return _BANNER + r'''
#ifndef FORCEPASSWORDCHANGEDIALOG_H_
#define FORCEPASSWORDCHANGEDIALOG_H_

#include <QDialog>

class QLineEdit;
class QLabel;
class UserManager;

/**
 * ForcePasswordChangeDialog - shown immediately after a successful login
 * if the operator is using the bootstrap default password ('ChangeMe!')
 * or if their current password matches a small "common-default" list.
 *
 * The dialog is non-cancellable: the only way out is to set a new
 * password that satisfies the policy:
 *   - >= 8 characters
 *   - at least one digit
 *   - at least one non-alphanumeric character
 *   - not equal to the current password
 *
 * A SECURITY-level event is written to logs/security.log on success.
 */
class ForcePasswordChangeDialog : public QDialog {
    Q_OBJECT
public:
    explicit ForcePasswordChangeDialog(UserManager *mgr,
                                       const QString &user,
                                       QWidget *parent = nullptr);

protected:
    void closeEvent(QCloseEvent *e) override;
    void reject() override;

private slots:
    void tryChange();

private:
    UserManager *m_mgr;
    QString      m_user;
    QLineEdit   *m_pw1;
    QLineEdit   *m_pw2;
    QLabel      *m_status;
    bool         m_done = false;
};

#endif /* FORCEPASSWORDCHANGEDIALOG_H_ */
'''


def force_password_change_cpp() -> str:
    return _BANNER + r'''
#include "ForcePasswordChangeDialog.h"
#include "UserManager.h"
#include "EventLogger.h"

#include <QCloseEvent>
#include <QFormLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QMessageBox>
#include <QPushButton>
#include <QVBoxLayout>

ForcePasswordChangeDialog::ForcePasswordChangeDialog(
    UserManager *mgr, const QString &user, QWidget *parent)
    : QDialog(parent), m_mgr(mgr), m_user(user) {
    setWindowTitle(tr("Set a new password"));
    setModal(true);
    setWindowFlag(Qt::WindowCloseButtonHint, false);

    auto *banner = new QLabel(
        "<h3>Set a new password</h3>"
        "<p style='color:#94a3b8'>You are using the default password.<br>"
        "Choose a new password before continuing.</p>"
        "<p>Policy: <b>at least 8 characters, one digit, one symbol</b>.</p>");
    banner->setWordWrap(true);
    m_pw1 = new QLineEdit; m_pw1->setEchoMode(QLineEdit::Password);
    m_pw2 = new QLineEdit; m_pw2->setEchoMode(QLineEdit::Password);
    m_status = new QLabel; m_status->setStyleSheet("color:#dc2626");
    auto *form = new QFormLayout;
    form->addRow(tr("New password"),     m_pw1);
    form->addRow(tr("Confirm password"), m_pw2);
    auto *ok = new QPushButton(tr("Set password"));
    ok->setDefault(true);
    auto *btns = new QHBoxLayout;
    btns->addStretch();
    btns->addWidget(ok);
    auto *outer = new QVBoxLayout(this);
    outer->addWidget(banner);
    outer->addLayout(form);
    outer->addWidget(m_status);
    outer->addLayout(btns);

    connect(ok, &QPushButton::clicked, this,
            &ForcePasswordChangeDialog::tryChange);
    setMinimumWidth(420);
}

void ForcePasswordChangeDialog::tryChange() {
    auto pw1 = m_pw1->text();
    auto pw2 = m_pw2->text();
    if (pw1 != pw2) {
        m_status->setText(tr("Passwords do not match"));
        return;
    }
    if (pw1.length() < 8) {
        m_status->setText(tr("Password is too short (minimum 8 characters)"));
        return;
    }
    bool hasDigit = false, hasSym = false;
    for (auto c : pw1) {
        if (c.isDigit()) hasDigit = true;
        else if (!c.isLetterOrNumber()) hasSym = true;
    }
    if (!hasDigit) { m_status->setText(tr("Password must include a digit")); return; }
    if (!hasSym)   { m_status->setText(tr("Password must include a symbol")); return; }
    if (pw1 == "ChangeMe!") {
        m_status->setText(tr("New password must differ from the default"));
        return;
    }

    if (!m_mgr->changePassword(m_user, pw1)) {
        m_status->setText(tr("Could not save the password"));
        return;
    }
    EventLogger::instance().security(
        "ForcePasswordChangeDialog",
        QString("User '%1' rotated the bootstrap default password").arg(m_user));
    m_done = true;
    accept();
}

void ForcePasswordChangeDialog::closeEvent(QCloseEvent *e) {
    if (!m_done) e->ignore();   // not closeable until they pick a password
    else QDialog::closeEvent(e);
}

void ForcePasswordChangeDialog::reject() {
    if (!m_done) return;          // Esc / outside-click also blocked
    QDialog::reject();
}
'''


# Generic .ui templates for every dialog/panel that doesn't have one yet.
def aboutdialog_ui(project_name: str) -> str:
    body = (
        '  <layout class="QVBoxLayout">\n'
        f'   <item><widget class="QLabel"><property name="text"><string>&lt;h2&gt;{project_name}&lt;/h2&gt;</string></property></widget></item>\n'
        '   <item><widget class="QLabel" name="bodyLabel"><property name="wordWrap"><bool>true</bool></property></widget></item>\n'
        '   <item><layout class="QHBoxLayout">\n'
        '    <item><spacer><property name="orientation"><enum>Qt::Horizontal</enum></property></spacer></item>\n'
        '    <item><widget class="QPushButton" name="okBtn"><property name="text"><string>OK</string></property></widget></item>\n'
        '   </layout></item>\n'
        '  </layout>\n'
    )
    return _basic_ui("AboutDialog", "About", body)


def userspanel_ui() -> str:
    body = (
        '  <layout class="QVBoxLayout">\n'
        '   <item><widget class="QTableWidget" name="usersTable">'
        '<column><property name="text"><string>User</string></property></column>'
        '<column><property name="text"><string>Role</string></property></column>'
        '</widget></item>\n'
        '   <item><layout class="QHBoxLayout">\n'
        '    <item><widget class="QPushButton" name="addBtn"><property name="text"><string>Add user</string></property></widget></item>\n'
        '    <item><widget class="QPushButton" name="delBtn"><property name="text"><string>Delete user</string></property></widget></item>\n'
        '    <item><widget class="QPushButton" name="pwBtn"><property name="text"><string>Change password</string></property></widget></item>\n'
        '    <item><spacer><property name="orientation"><enum>Qt::Horizontal</enum></property></spacer></item>\n'
        '   </layout></item>\n'
        '  </layout>\n'
    )
    return _basic_ui("UsersPanel", "Users", body)


def eventlogpanel_ui() -> str:
    body = (
        '  <layout class="QVBoxLayout">\n'
        '   <item><layout class="QHBoxLayout">\n'
        '    <item><widget class="QLabel"><property name="text"><string>Filter:</string></property></widget></item>\n'
        '    <item><widget class="QComboBox" name="severityFilter">'
        '<item><property name="text"><string>Debug+</string></property></item>'
        '<item><property name="text"><string>Info+</string></property></item>'
        '<item><property name="text"><string>Warn+</string></property></item>'
        '<item><property name="text"><string>Error+</string></property></item>'
        '<item><property name="text"><string>Security only</string></property></item>'
        '</widget></item>\n'
        '    <item><spacer><property name="orientation"><enum>Qt::Horizontal</enum></property></spacer></item>\n'
        '    <item><widget class="QPushButton" name="exportBtn"><property name="text"><string>Export CSV</string></property></widget></item>\n'
        '    <item><widget class="QPushButton" name="clearBtn"><property name="text"><string>Clear</string></property></widget></item>\n'
        '   </layout></item>\n'
        '   <item><widget class="QTableWidget" name="eventTable">'
        '<column><property name="text"><string>Timestamp</string></property></column>'
        '<column><property name="text"><string>Severity</string></property></column>'
        '<column><property name="text"><string>User</string></property></column>'
        '<column><property name="text"><string>Source</string></property></column>'
        '<column><property name="text"><string>Message</string></property></column>'
        '</widget></item>\n'
        '  </layout>\n'
    )
    return _basic_ui("EventLogPanel", "Event Log", body)


def peripheral_panel_ui(class_name: str, peripheral_name: str, bus: str) -> str:
    body = (
        '  <layout class="QVBoxLayout">\n'
        f'   <item><widget class="QLabel"><property name="text"><string>&lt;h3&gt;{peripheral_name}&lt;/h3&gt;Bus: &lt;b&gt;{bus.upper()}&lt;/b&gt;</string></property></widget></item>\n'
        '   <item><widget class="QLabel" name="statusLabel"><property name="text"><string>Status: &lt;i&gt;not tested&lt;/i&gt;</string></property></widget></item>\n'
        '   <item><widget class="QPushButton" name="selfTestBtn">'
        f'<property name="text"><string>Run self-test for {peripheral_name}</string></property></widget></item>\n'
        '   <item><widget class="QTextEdit" name="trace"><property name="readOnly"><bool>true</bool></property></widget></item>\n'
        '  </layout>\n'
    )
    return _basic_ui(class_name, peripheral_name, body)


def application_panel_ui(class_name: str, title: str) -> str:
    body = (
        '  <layout class="QVBoxLayout">\n'
        f'   <item><widget class="QLabel"><property name="text"><string>&lt;h3&gt;{title}&lt;/h3&gt;</string></property></widget></item>\n'
        '   <item><widget class="QFrame" name="contentFrame">'
        '<property name="frameShape"><enum>QFrame::StyledPanel</enum></property>'
        '</widget></item>\n'
        '  </layout>\n'
    )
    return _basic_ui(class_name, title, body)


# ---------------------------------------------------------------------------
# Welcome tab + status bar (Item #6)
# ---------------------------------------------------------------------------


def welcome_panel_h() -> str:
    return _BANNER + r'''
#ifndef WELCOMEPANEL_H_
#define WELCOMEPANEL_H_

#include <QWidget>
#include <QStringList>

class QLabel;
class QListWidget;

/**
 * WelcomePanel - the first tab the user sees on a fresh launch.
 *
 * Shows a project overview: name, application class, peripheral count,
 * register count, recent events. Designed so the user can confirm at a
 * glance which project the GUI is bound to without poking around the
 * other tabs first.
 */
class WelcomePanel : public QWidget {
    Q_OBJECT
public:
    explicit WelcomePanel(const QString &projectName,
                          const QString &applicationClass,
                          int peripheralCount,
                          int registerCount,
                          const QStringList &peripheralNames,
                          QWidget *parent = nullptr);

private:
    QListWidget *m_recentEvents;
};

#endif /* WELCOMEPANEL_H_ */
'''


def welcome_panel_cpp(project_name: str, application_class: str,
                      peripheral_count: int, register_count: int) -> str:
    return _BANNER + (
        '#include "WelcomePanel.h"\n'
        '#include "EventLogger.h"\n\n'
        '#include <QHBoxLayout>\n'
        '#include <QLabel>\n'
        '#include <QListWidget>\n'
        '#include <QVBoxLayout>\n\n'
        'WelcomePanel::WelcomePanel(const QString &projectName,\n'
        '                           const QString &applicationClass,\n'
        '                           int peripheralCount,\n'
        '                           int registerCount,\n'
        '                           const QStringList &peripheralNames,\n'
        '                           QWidget *parent)\n'
        '    : QWidget(parent) {\n'
        '    auto *title = new QLabel(\n'
        '        QString("<h1 style=\\\'color:#00c6a7\\\'>%1</h1>").arg(projectName));\n'
        '    auto *subtitle = new QLabel(\n'
        '        QString("<p style=\\\'color:#94a3b8;font-size:12pt\\\'>"\n'
        '                "Generated control panel for %1 (%2)<br>"\n'
        '                "Auto-built by Silicon to Software (S2S) v2."\n'
        '                "</p>").arg(projectName, applicationClass));\n'
        '    auto *kpis = new QLabel(\n'
        '        QString("<table cellpadding=8 cellspacing=0 "\n'
        '                "style=\\\'border:1px solid #2a3a50;\\\'>"\n'
        '                "<tr style=\\\'background:#1a2235\\\'>"\n'
        '                "<th>Application class</th>"\n'
        '                "<th>Peripherals</th>"\n'
        '                "<th>Registers</th>"\n'
        '                "<th>Status</th></tr>"\n'
        '                "<tr style=\\\'text-align:center\\\'>"\n'
        '                "<td><b>%1</b></td>"\n'
        '                "<td><b>%2</b></td>"\n'
        '                "<td><b>%3</b></td>"\n'
        '                "<td style=\\\'color:#00c6a7\\\'><b>READY</b></td></tr>"\n'
        '                "</table>").arg(applicationClass)\n'
        '                .arg(peripheralCount).arg(registerCount));\n'
        '    auto *peripheralsHeader = new QLabel(\n'
        '        QString("<h3>Peripherals (%1)</h3>").arg(peripheralCount));\n'
        '    auto *peripheralsList = new QListWidget;\n'
        '    peripheralsList->addItems(peripheralNames);\n'
        '    peripheralsList->setMaximumHeight(140);\n'
        '    auto *eventsHeader = new QLabel("<h3>Recent events</h3>");\n'
        '    m_recentEvents = new QListWidget;\n'
        '    m_recentEvents->setMaximumHeight(180);\n'
        '    connect(&EventLogger::instance(), &EventLogger::eventEmitted, this,\n'
        '            [this](const QString &iso, EventLogger::Severity, const QString &source,\n'
        '                   const QString &msg, const QString &) {\n'
        '                m_recentEvents->insertItem(0, QString("[%1] %2 - %3")\n'
        '                    .arg(iso.right(12), source, msg));\n'
        '                while (m_recentEvents->count() > 25)\n'
        '                    delete m_recentEvents->takeItem(m_recentEvents->count() - 1);\n'
        '            });\n'
        '    auto *layout = new QVBoxLayout(this);\n'
        '    layout->setContentsMargins(24, 24, 24, 24);\n'
        '    layout->addWidget(title);\n'
        '    layout->addWidget(subtitle);\n'
        '    layout->addSpacing(12);\n'
        '    layout->addWidget(kpis);\n'
        '    layout->addSpacing(12);\n'
        '    layout->addWidget(peripheralsHeader);\n'
        '    layout->addWidget(peripheralsList);\n'
        '    layout->addWidget(eventsHeader);\n'
        '    layout->addWidget(m_recentEvents);\n'
        '    layout->addStretch();\n'
        '}\n'
    )


def welcome_panel_ui(project_name: str) -> str:
    body = (
        '  <layout class="QVBoxLayout">\n'
        '   <property name="leftMargin"><number>24</number></property>\n'
        '   <property name="rightMargin"><number>24</number></property>\n'
        '   <property name="topMargin"><number>24</number></property>\n'
        '   <property name="bottomMargin"><number>24</number></property>\n'
        f'   <item><widget class="QLabel" name="titleLabel"><property name="text"><string>&lt;h1 style=&apos;color:#00c6a7&apos;&gt;{project_name}&lt;/h1&gt;</string></property></widget></item>\n'
        '   <item><widget class="QLabel" name="subtitleLabel"><property name="text"><string>Generated control panel</string></property></widget></item>\n'
        '   <item><widget class="QLabel" name="kpiTable"/></item>\n'
        '   <item><widget class="QLabel"><property name="text"><string>&lt;h3&gt;Peripherals&lt;/h3&gt;</string></property></widget></item>\n'
        '   <item><widget class="QListWidget" name="peripheralsList"/></item>\n'
        '   <item><widget class="QLabel"><property name="text"><string>&lt;h3&gt;Recent events&lt;/h3&gt;</string></property></widget></item>\n'
        '   <item><widget class="QListWidget" name="eventsList"/></item>\n'
        '   <item><spacer><property name="orientation"><enum>Qt::Vertical</enum></property></spacer></item>\n'
        '  </layout>\n'
    )
    return _basic_ui("WelcomePanel", project_name, body)
