"""
PySide6 Qt GUI Skeleton Generator.

Called from P8c (CodeAgent) after device drivers are generated.
Uses LLM to produce a runnable PySide6 application that:
  - Connects to the hardware over serial / USB
  - Displays real-time register values
  - Provides control panels matching SDD interfaces
  - Follows the design from SDD section 2.5 (Interface Viewpoint)
"""

import logging

from config import settings

logger = logging.getLogger(__name__)

QT_SYSTEM_PROMPT = """You are an expert PySide6/Qt6 developer generating a complete, runnable GUI application for embedded hardware control.

## OUTPUT REQUIREMENTS:
Generate a single Python file named `gui_application.py` that:

1. Uses PySide6 (NOT PyQt5/PyQt6/tkinter)
2. Has a QMainWindow with:
   - MenuBar (File, View, Help)
   - StatusBar showing connection state
   - Central widget with QTabWidget

3. Tabs:
   - "Dashboard" — live device status, register values in QTableWidget
   - "Control" — buttons and sliders matching the hardware interfaces from SDD
   - "Log" — QTextEdit showing serial/communication log
   - "Settings" — port selector (QComboBox), baud rate, connect/disconnect

4. Serial/USB Communication:
   - Use QThread for non-blocking serial reads (pyserial)
   - QTimer for periodic register polling (500ms)
   - Signals/slots for thread-safe GUI updates

5. Code standards:
   - Type hints throughout
   - Docstrings on all classes/methods
   - Error handling with QMessageBox for connection failures
   - QSettings for saving last-used port/baud
   - Dark theme using QPalette or qdarkstyle

## IMPORTANT:
- Generate COMPLETE runnable code — no placeholders or "TODO" stubs
- The register names and hardware interfaces MUST match what is described in the SDD
- Include `if __name__ == "__main__":` block
- The file must run standalone: `python gui_application.py`
"""


async def generate_qt_gui(
    project_name: str,
    sdd_content: str,
    srs_content: str,
    call_llm_fn,
) -> str:
    """
    Generate a PySide6 GUI application from SDD/SRS context.

    Args:
        project_name: Human-readable project name
        sdd_content:  Content of the Software Design Document
        srs_content:  Content of the Software Requirements Specification
        call_llm_fn:  Coroutine: async (messages, system, model) -> {content: str}

    Returns:
        Python source code string for the GUI application
    """

    prompt = f"""Generate a complete PySide6 Qt GUI application for the following hardware project.

**Project Name:** {project_name}

## Software Design Document (SDD) — Interface & Architecture
{sdd_content[:4000] if sdd_content else "No SDD available — use generic hardware control layout."}

## Software Requirements Specification (SRS) — Functional Requirements
{srs_content[:2000] if srs_content else "No SRS available."}

---

Generate `gui_application.py`:
- Use the exact register names, interface names, and module names from the SDD above
- The Dashboard tab must show the registers defined in the SDD Interface Viewpoint
- The Control tab buttons must match the driver API functions listed in the SDD
- Include serial port selection for the hardware described in the SRS

Output ONLY the Python code — no explanations, no markdown fences, just the file content.
Start with: # gui_application.py — {project_name} Hardware Control GUI
"""

    try:
        response = await call_llm_fn(
            messages=[{"role": "user", "content": prompt}],
            system=QT_SYSTEM_PROMPT,
            model=settings.primary_model,
        )
        code = response.get("content", "")

        # Strip markdown fences if LLM wrapped in ```python
        if code.startswith("```"):
            import re
            code = re.sub(r"^```(?:python)?\n?", "", code)
            code = re.sub(r"\n?```$", "", code.rstrip())

        if not code or len(code) < 200:
            logger.warning("Qt GUI generation returned empty/short response — using fallback template")
            return _fallback_gui_template(project_name)

        return code

    except Exception as e:
        logger.error(f"Qt GUI generation failed: {e}")
        return _fallback_gui_template(project_name)


def _fallback_gui_template(project_name: str) -> str:
    """Minimal but runnable PySide6 skeleton when LLM generation fails."""
    safe_name = project_name.replace(" ", "")
    _TEMPLATE = '''# gui_application.py — __PROJECT_NAME__ Hardware Control GUI
# Generated by Silicon to Software (S2S) v2
# Run: python gui_application.py
# Install: pip install PySide6 pyserial

from __future__ import annotations
import sys
import json
from datetime import datetime
from typing import Optional

from PySide6.QtCore import Qt, QTimer, QThread, Signal, QSettings
from PySide6.QtGui import QPalette, QColor, QFont
from PySide6.QtWidgets import (
    QApplication, QMainWindow, QTabWidget, QWidget, QVBoxLayout,
    QHBoxLayout, QLabel, QPushButton, QComboBox, QSpinBox,
    QTableWidget, QTableWidgetItem, QTextEdit, QGroupBox,
    QStatusBar, QMessageBox, QGridLayout, QSlider,
)

try:
    import serial
    import serial.tools.list_ports
    SERIAL_AVAILABLE = True
except ImportError:
    SERIAL_AVAILABLE = False


# --------------------------------------------------------------------------- #
# Serial worker thread
# --------------------------------------------------------------------------- #

class SerialWorker(QThread):
    """Non-blocking serial read thread."""
    data_received = Signal(str)
    connection_changed = Signal(bool)
    error_occurred = Signal(str)

    def __init__(self, port: str, baud: int, parent=None):
        super().__init__(parent)
        self.port = port
        self.baud = baud
        self._running = False
        self._serial: Optional[object] = None

    def run(self) -> None:
        if not SERIAL_AVAILABLE:
            self.error_occurred.emit("pyserial not installed. Run: pip install pyserial")
            return
        try:
            self._serial = serial.Serial(self.port, self.baud, timeout=0.1)
            self._running = True
            self.connection_changed.emit(True)
            while self._running:
                if self._serial.in_waiting:
                    raw = self._serial.readline().decode("utf-8", errors="replace").strip()
                    if raw:
                        self.data_received.emit(raw)
                self.msleep(10)
        except Exception as e:
            self.error_occurred.emit(str(e))
        finally:
            if self._serial and self._serial.is_open:
                self._serial.close()
            self.connection_changed.emit(False)

    def send(self, data: bytes) -> None:
        if self._serial and self._serial.is_open:
            self._serial.write(data)

    def stop(self) -> None:
        self._running = False
        self.wait(2000)


# --------------------------------------------------------------------------- #
# Dashboard tab
# --------------------------------------------------------------------------- #

class DashboardTab(QWidget):
    """Live device status and register values."""

    REGISTERS = [
        ("CTRL_REG",   "0x00", "RW", "Control register"),
        ("STATUS_REG", "0x01", "RO", "Device status"),
        ("DATA_REG",   "0x02", "RW", "Data register"),
        ("INT_REG",    "0x03", "RW", "Interrupt enable"),
        ("ERR_REG",    "0x04", "RO", "Error flags"),
    ]

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)

        # Status cards row
        card_row = QHBoxLayout()
        self.status_card = self._make_card("Device Status", "DISCONNECTED", "#dc2626")
        self.fw_card     = self._make_card("Firmware",      "v1.0.0",       "#3b82f6")
        self.uptime_card = self._make_card("Uptime",        "—",             "#00c6a7")
        card_row.addWidget(self.status_card)
        card_row.addWidget(self.fw_card)
        card_row.addWidget(self.uptime_card)
        layout.addLayout(card_row)

        # Register table
        grp = QGroupBox("Register Map")
        grp_layout = QVBoxLayout(grp)
        self.reg_table = QTableWidget(len(self.REGISTERS), 4)
        self.reg_table.setHorizontalHeaderLabels(["Register", "Address", "Value", "Description"])
        self.reg_table.horizontalHeader().setStretchLastSection(True)
        for row, (name, addr, acc, desc) in enumerate(self.REGISTERS):
            self.reg_table.setItem(row, 0, QTableWidgetItem(name))
            self.reg_table.setItem(row, 1, QTableWidgetItem(addr))
            self.reg_table.setItem(row, 2, QTableWidgetItem("0x--"))
            self.reg_table.setItem(row, 3, QTableWidgetItem(desc))
        grp_layout.addWidget(self.reg_table)
        layout.addWidget(grp)

    def _make_card(self, title: str, value: str, color: str) -> QGroupBox:
        card = QGroupBox(title)
        v = QVBoxLayout(card)
        lbl = QLabel(value)
        lbl.setAlignment(Qt.AlignCenter)
        lbl.setStyleSheet(f"font-size: 18px; font-weight: bold; color: {color};")
        lbl.setObjectName(f"card_{title.replace(' ','_')}")
        v.addWidget(lbl)
        return card

    def update_register(self, row: int, value: str) -> None:
        if 0 <= row < self.reg_table.rowCount():
            self.reg_table.setItem(row, 2, QTableWidgetItem(value))

    def set_status(self, connected: bool) -> None:
        lbl = self.status_card.findChild(QLabel, "card_Device_Status")
        if lbl:
            if connected:
                lbl.setText("CONNECTED")
                lbl.setStyleSheet("font-size:18px;font-weight:bold;color:#00c6a7;")
            else:
                lbl.setText("DISCONNECTED")
                lbl.setStyleSheet("font-size:18px;font-weight:bold;color:#dc2626;")


# --------------------------------------------------------------------------- #
# Control tab
# --------------------------------------------------------------------------- #

class ControlTab(QWidget):
    """Hardware control panel."""

    command_requested = Signal(bytes)

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)

        # Device control
        ctrl_grp = QGroupBox("Device Control")
        ctrl_layout = QGridLayout(ctrl_grp)

        self.init_btn = QPushButton("Initialize Device")
        self.reset_btn = QPushButton("Reset Device")
        self.read_btn  = QPushButton("Read All Registers")
        self.stop_btn  = QPushButton("Emergency Stop")
        self.stop_btn.setStyleSheet("background-color: #dc2626; color: white; font-weight: bold;")

        ctrl_layout.addWidget(self.init_btn,  0, 0)
        ctrl_layout.addWidget(self.reset_btn, 0, 1)
        ctrl_layout.addWidget(self.read_btn,  1, 0)
        ctrl_layout.addWidget(self.stop_btn,  1, 1)
        layout.addWidget(ctrl_grp)

        # Parameter control
        param_grp = QGroupBox("Parameters")
        param_layout = QGridLayout(param_grp)

        param_layout.addWidget(QLabel("Output Level:"), 0, 0)
        self.level_slider = QSlider(Qt.Horizontal)
        self.level_slider.setRange(0, 255)
        self.level_label  = QLabel("0")
        self.level_slider.valueChanged.connect(lambda v: self.level_label.setText(str(v)))
        param_layout.addWidget(self.level_slider, 0, 1)
        param_layout.addWidget(self.level_label, 0, 2)

        param_layout.addWidget(QLabel("Sample Rate (Hz):"), 1, 0)
        self.rate_spin = QSpinBox()
        self.rate_spin.setRange(1, 10000)
        self.rate_spin.setValue(100)
        param_layout.addWidget(self.rate_spin, 1, 1)

        send_btn = QPushButton("Apply Settings")
        send_btn.clicked.connect(self._apply_settings)
        param_layout.addWidget(send_btn, 2, 0, 1, 3)
        layout.addWidget(param_grp)

        layout.addStretch()

        # Wire up buttons
        self.init_btn.clicked.connect(lambda: self.command_requested.emit(b"CMD:INIT\\n"))
        self.reset_btn.clicked.connect(lambda: self.command_requested.emit(b"CMD:RESET\\n"))
        self.read_btn.clicked.connect(lambda: self.command_requested.emit(b"CMD:READ_ALL\\n"))
        self.stop_btn.clicked.connect(lambda: self.command_requested.emit(b"CMD:STOP\\n"))

    def _apply_settings(self) -> None:
        level = self.level_slider.value()
        rate  = self.rate_spin.value()
        cmd   = f"CMD:SET_LEVEL={{level}}:RATE={{rate}}\\n".encode()
        self.command_requested.emit(cmd)


# --------------------------------------------------------------------------- #
# Settings tab
# --------------------------------------------------------------------------- #

class SettingsTab(QWidget):
    """Serial port configuration."""

    connect_requested    = Signal(str, int)
    disconnect_requested = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._settings = QSettings("HardwarePipeline", "__PROJECT_NAME__")
        layout = QVBoxLayout(self)

        grp = QGroupBox("Serial Connection")
        form = QGridLayout(grp)

        form.addWidget(QLabel("Port:"), 0, 0)
        self.port_combo = QComboBox()
        self._refresh_ports()
        form.addWidget(self.port_combo, 0, 1)

        refresh_btn = QPushButton("Refresh")
        refresh_btn.clicked.connect(self._refresh_ports)
        form.addWidget(refresh_btn, 0, 2)

        form.addWidget(QLabel("Baud Rate:"), 1, 0)
        self.baud_combo = QComboBox()
        for b in [9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600]:
            self.baud_combo.addItem(str(b), b)
        self.baud_combo.setCurrentText(
            self._settings.value("baud", "115200")
        )
        form.addWidget(self.baud_combo, 1, 1)

        self.connect_btn    = QPushButton("Connect")
        self.disconnect_btn = QPushButton("Disconnect")
        self.disconnect_btn.setEnabled(False)
        form.addWidget(self.connect_btn, 2, 0)
        form.addWidget(self.disconnect_btn, 2, 1)
        layout.addWidget(grp)
        layout.addStretch()

        self.connect_btn.clicked.connect(self._on_connect)
        self.disconnect_btn.clicked.connect(self.disconnect_requested.emit)

    def _refresh_ports(self) -> None:
        self.port_combo.clear()
        if SERIAL_AVAILABLE:
            ports = serial.tools.list_ports.comports()
            for p in ports:
                self.port_combo.addItem(f"{{p.device}} — {{p.description}}", p.device)
        if self.port_combo.count() == 0:
            self.port_combo.addItem("No ports found", "")

    def _on_connect(self) -> None:
        port = self.port_combo.currentData() or self.port_combo.currentText().split(" ")[0]
        baud = int(self.baud_combo.currentData())
        self._settings.setValue("baud", str(baud))
        self.connect_requested.emit(port, baud)

    def set_connected(self, connected: bool) -> None:
        self.connect_btn.setEnabled(not connected)
        self.disconnect_btn.setEnabled(connected)


# --------------------------------------------------------------------------- #
# Main Window
# --------------------------------------------------------------------------- #

class MainWindow(QMainWindow):
    """Main application window — __PROJECT_NAME__ Hardware Control GUI."""

    def __init__(self):
        super().__init__()
        self.setWindowTitle("__PROJECT_NAME__ — Hardware Control GUI")
        self.resize(1000, 700)
        self._worker: Optional[SerialWorker] = None
        self._poll_timer = QTimer(self)
        self._poll_timer.setInterval(500)
        self._poll_timer.timeout.connect(self._poll_registers)

        self._setup_ui()
        self._apply_dark_theme()

    def _setup_ui(self) -> None:
        tabs = QTabWidget()
        self.dashboard = DashboardTab()
        self.control   = ControlTab()
        self.log_tab   = QTextEdit()
        self.log_tab.setReadOnly(True)
        self.log_tab.setFont(QFont("Courier New", 10))
        self.settings_tab = SettingsTab()

        tabs.addTab(self.dashboard,    "Dashboard")
        tabs.addTab(self.control,      "Control")
        tabs.addTab(self.log_tab,      "Log")
        tabs.addTab(self.settings_tab, "Settings")
        self.setCentralWidget(tabs)

        self.statusBar().showMessage("Disconnected")

        # Wire signals
        self.settings_tab.connect_requested.connect(self._on_connect)
        self.settings_tab.disconnect_requested.connect(self._on_disconnect)
        self.control.command_requested.connect(self._send_command)

    def _on_connect(self, port: str, baud: int) -> None:
        if self._worker:
            self._on_disconnect()
        self._worker = SerialWorker(port, baud, self)
        self._worker.data_received.connect(self._on_data)
        self._worker.connection_changed.connect(self._on_connection_changed)
        self._worker.error_occurred.connect(self._on_error)
        self._worker.start()
        self._log(f"Connecting to {{port}} @ {{baud}} baud...")

    def _on_disconnect(self) -> None:
        if self._worker:
            self._poll_timer.stop()
            self._worker.stop()
            self._worker = None
        self._on_connection_changed(False)
        self._log("Disconnected.")

    def _on_connection_changed(self, connected: bool) -> None:
        self.dashboard.set_status(connected)
        self.settings_tab.set_connected(connected)
        self.statusBar().showMessage("Connected" if connected else "Disconnected")
        if connected:
            self._poll_timer.start()
        else:
            self._poll_timer.stop()

    def _on_data(self, data: str) -> None:
        self._log(f"RX: {{data}}")
        # Parse simple "REG:0=0x42" format
        if data.startswith("REG:"):
            try:
                parts = data[4:].split("=")
                reg_idx = int(parts[0])
                reg_val = parts[1].strip()
                self.dashboard.update_register(reg_idx, reg_val)
            except (IndexError, ValueError):
                pass

    def _on_error(self, msg: str) -> None:
        self._log(f"ERROR: {{msg}}")
        QMessageBox.critical(self, "Connection Error", msg)
        self._on_connection_changed(False)

    def _send_command(self, data: bytes) -> None:
        if self._worker:
            self._worker.send(data)
            self._log(f"TX: {{data.decode('utf-8', errors='replace').strip()}}")
        else:
            self._log("Not connected — command not sent.")

    def _poll_registers(self) -> None:
        self._send_command(b"CMD:READ_ALL\\n")

    def _log(self, msg: str) -> None:
        ts = datetime.now().strftime("%H:%M:%S.%f")[:-3]
        self.log_tab.append(f"[{{ts}}] {{msg}}")

    def _apply_dark_theme(self) -> None:
        palette = QPalette()
        palette.setColor(QPalette.Window,          QColor("#070b14"))
        palette.setColor(QPalette.WindowText,      QColor("#e2e8f0"))
        palette.setColor(QPalette.Base,            QColor("#1a2235"))
        palette.setColor(QPalette.AlternateBase,   QColor("#2a3a50"))
        palette.setColor(QPalette.ToolTipBase,     QColor("#1a2235"))
        palette.setColor(QPalette.ToolTipText,     QColor("#e2e8f0"))
        palette.setColor(QPalette.Text,            QColor("#e2e8f0"))
        palette.setColor(QPalette.Button,          QColor("#2a3a50"))
        palette.setColor(QPalette.ButtonText,      QColor("#e2e8f0"))
        palette.setColor(QPalette.Highlight,       QColor("#00c6a7"))
        palette.setColor(QPalette.HighlightedText, QColor("#070b14"))
        QApplication.setPalette(palette)

    def closeEvent(self, event) -> None:
        self._on_disconnect()
        event.accept()


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #

if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setApplicationName("__PROJECT_NAME__ Hardware Control")
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
'''
    return _TEMPLATE.replace('__PROJECT_NAME__', project_name).replace('__SAFE_NAME__', safe_name)
