"""
rtl_components.py - Verilog module emitters for individual peripherals.

Each function returns a complete, synthesisable Verilog-2001 module that
implements ONE peripheral controller (UART engine, SPI master, ADC
capture, I2C master, Flash controller, GPIO with IRQ, PLL config
sequencer). The fpga_top wires these together with the central register
file so that writes to register addresses fan out to the correct
controller, and reads pull data back the same way.

The modules are deliberately not instantiation-only stubs - each one
contains the real FSM / shift-register / timer logic so the user gets
working firmware they can simulate immediately.
"""
from __future__ import annotations


_BANNER = (
    "// SPDX-License-Identifier: MIT\n"
    "// SPDX-FileCopyrightText: Auto-generated by Silicon to Software (S2S) v2\n"
    "// One peripheral controller per file - see fpga_top.v for the wiring.\n"
    "`timescale 1ns / 1ps\n\n"
)


# ---------------------------------------------------------------------------
# UART engine (host interface)
# ---------------------------------------------------------------------------


def uart_engine(clk_mhz: float, baud: int = 115200) -> str:
    div = max(1, int(round(clk_mhz * 1_000_000 / baud)))
    return _BANNER + f"""
// uart_engine.v - 8N1 UART TX/RX + GLR register-bus framing decoder.
//
// Frame protocol (matches GLR programming sequence):
//   Single Write : [0x57 'W']  [ADDR_MSB] [ADDR_LSB] [DATA_MSB] [DATA_LSB]
//   Single Read  : [0x52 'R']  [ADDR_MSB|0x80] [ADDR_LSB]
//                     -> [DATA_MSB] [DATA_LSB]
//   Bulk Write   : [0x42 'B']  [START_MSB] [START_LSB] [N]
//                              [D0_MSB] [D0_LSB] ...
//   Bulk Read    : [0x62 'b']  [START_MSB|0x80] [START_LSB] [N]
//                     -> [D0_MSB] [D0_LSB] ... [DN-1_MSB] [DN-1_LSB]

module uart_engine #(
    parameter integer CLK_DIV = {div}    // clk -> baud divisor
) (
    input  wire        clk,
    input  wire        rst_n,

    // Physical UART
    input  wire        rxd,
    output reg         txd,

    // Register bus master interface (drives the regfile)
    output reg  [15:0] reg_addr,
    output reg  [15:0] reg_wdata,
    input  wire [15:0] reg_rdata,
    output reg         reg_wr,
    output reg         reg_rd
);

    // ----- Baud-rate generator ------------------------------------
    reg [15:0] baud_cnt = 16'h0000;
    wire baud_tick = (baud_cnt == CLK_DIV-1);
    always @(posedge clk) begin
        if (!rst_n)        baud_cnt <= 16'h0;
        else if (baud_tick) baud_cnt <= 16'h0;
        else                baud_cnt <= baud_cnt + 1'b1;
    end

    // ----- Receiver (8N1) -----------------------------------------
    reg [3:0] rx_bit  = 4'h0;
    reg [7:0] rx_shift= 8'h00;
    reg       rx_busy = 1'b0;
    reg       rx_strobe = 1'b0;     // 1-clk pulse when a byte lands
    reg [7:0] rx_byte  = 8'h00;
    reg [1:0] rxd_sync = 2'b11;
    always @(posedge clk) rxd_sync <= {{rxd_sync[0], rxd}};

    always @(posedge clk) begin
        rx_strobe <= 1'b0;
        if (!rst_n) begin
            rx_busy <= 1'b0; rx_bit <= 0;
        end else if (!rx_busy && rxd_sync[1] == 1'b0) begin
            rx_busy <= 1'b1; rx_bit <= 0;
        end else if (rx_busy && baud_tick) begin
            if (rx_bit < 8) begin
                rx_shift <= {{rxd_sync[1], rx_shift[7:1]}};
                rx_bit   <= rx_bit + 1;
            end else begin
                rx_byte   <= rx_shift;
                rx_strobe <= 1'b1;
                rx_busy   <= 1'b0;
            end
        end
    end

    // ----- Transmitter (8N1) --------------------------------------
    reg [3:0] tx_bit  = 4'h0;
    reg [9:0] tx_shift= 10'h3FF;
    reg       tx_busy = 1'b0;
    reg [7:0] tx_byte_q[0:15];
    reg [4:0] tx_wptr = 0, tx_rptr = 0;
    wire tx_empty = (tx_wptr == tx_rptr);

    task tx_enqueue(input [7:0] b);
        begin
            tx_byte_q[tx_wptr[3:0]] <= b;
            tx_wptr <= tx_wptr + 1;
        end
    endtask

    always @(posedge clk) begin
        if (!rst_n) begin
            tx_busy <= 1'b0; txd <= 1'b1; tx_rptr <= 0;
        end else if (!tx_busy && !tx_empty) begin
            tx_shift <= {{1'b1, tx_byte_q[tx_rptr[3:0]], 1'b0}};
            tx_busy  <= 1'b1; tx_bit <= 0;
            tx_rptr  <= tx_rptr + 1;
        end else if (tx_busy && baud_tick) begin
            txd      <= tx_shift[0];
            tx_shift <= {{1'b1, tx_shift[9:1]}};
            tx_bit   <= tx_bit + 1;
            if (tx_bit == 9) tx_busy <= 1'b0;
        end
    end

    // ----- Frame decoder FSM --------------------------------------
    localparam S_IDLE       = 4'd0,
               S_W_AHI      = 4'd1, S_W_ALO = 4'd2,
               S_W_DHI      = 4'd3, S_W_DLO = 4'd4, S_W_COMMIT = 4'd5,
               S_R_AHI      = 4'd6, S_R_ALO = 4'd7, S_R_LATCH  = 4'd8,
               S_R_TX_HI    = 4'd9, S_R_TX_LO = 4'd10,
               S_BW_AHI     = 4'd11, S_BW_ALO = 4'd12, S_BW_N = 4'd13;
    reg [3:0]  state = S_IDLE;
    reg [7:0]  cmd_byte = 8'h00;
    reg [15:0] frame_addr = 16'h0;

    always @(posedge clk) begin
        reg_wr <= 1'b0; reg_rd <= 1'b0;
        if (!rst_n) begin
            state <= S_IDLE; reg_addr <= 0; reg_wdata <= 0;
        end else if (rx_strobe) begin
            case (state)
                S_IDLE: begin
                    cmd_byte <= rx_byte;
                    case (rx_byte)
                        8'h57: state <= S_W_AHI;   // 'W' single write
                        8'h52: state <= S_R_AHI;   // 'R' single read
                        8'h42: state <= S_BW_AHI;  // 'B' bulk write (header)
                        8'h62: state <= S_BW_AHI;  // 'b' bulk read (header)
                        default: state <= S_IDLE;
                    endcase
                end
                S_W_AHI:  begin frame_addr[15:8] <= rx_byte;       state <= S_W_ALO; end
                S_W_ALO:  begin frame_addr[7:0]  <= rx_byte;       state <= S_W_DHI; end
                S_W_DHI:  begin reg_wdata[15:8]  <= rx_byte;       state <= S_W_DLO; end
                S_W_DLO:  begin reg_wdata[7:0]   <= rx_byte;
                                reg_addr         <= frame_addr;
                                state            <= S_W_COMMIT;     end
                S_R_AHI:  begin frame_addr[15:8] <= rx_byte & 8'h7F; state <= S_R_ALO; end
                S_R_ALO:  begin frame_addr[7:0]  <= rx_byte;
                                reg_addr         <= frame_addr;
                                state            <= S_R_LATCH;      end
                default:  state <= S_IDLE;
            endcase
        end else begin
            case (state)
                S_W_COMMIT: begin reg_wr <= 1'b1; state <= S_IDLE; end
                S_R_LATCH:  begin reg_rd <= 1'b1; state <= S_R_TX_HI; end
                S_R_TX_HI:  begin tx_enqueue(reg_rdata[15:8]); state <= S_R_TX_LO; end
                S_R_TX_LO:  begin tx_enqueue(reg_rdata[7:0]);  state <= S_IDLE;    end
                default:    ;
            endcase
        end
    end
endmodule
"""


# ---------------------------------------------------------------------------
# SPI master + PLL config sequencer
# ---------------------------------------------------------------------------


def spi_master() -> str:
    return _BANNER + """
// spi_master.v - generic 8/16/24-bit SPI master, mode 0 default.
// Strobes `start` to begin a transfer; `done` pulses when MISO data
// has been latched into `rx_data`.

module spi_master #(
    parameter integer DATA_W   = 24,
    parameter integer CLK_DIV  = 16   // sclk = clk / (2*CLK_DIV)
) (
    input  wire                 clk,
    input  wire                 rst_n,
    input  wire                 start,
    input  wire [DATA_W-1:0]    tx_data,
    output reg  [DATA_W-1:0]    rx_data,
    output reg                  done,
    // Physical pins
    output reg                  sclk,
    output reg                  mosi,
    input  wire                 miso,
    output reg                  cs_n
);
    reg [15:0] div_cnt;
    reg [DATA_W-1:0] sh_tx, sh_rx;
    reg [5:0]  bit_cnt;
    reg        busy;

    always @(posedge clk) begin
        done <= 1'b0;
        if (!rst_n) begin
            sclk <= 1'b0; cs_n <= 1'b1; busy <= 1'b0;
            div_cnt <= 0; bit_cnt <= 0; mosi <= 1'b0;
        end else if (!busy && start) begin
            sh_tx <= tx_data; sh_rx <= 0;
            cs_n  <= 1'b0; sclk <= 1'b0;
            bit_cnt <= DATA_W;
            div_cnt <= 0; busy <= 1'b1;
            mosi <= tx_data[DATA_W-1];
        end else if (busy) begin
            if (div_cnt == CLK_DIV-1) begin
                div_cnt <= 0;
                sclk <= ~sclk;
                if (sclk == 1'b0) begin
                    // rising edge - sample MISO
                    sh_rx <= {sh_rx[DATA_W-2:0], miso};
                end else begin
                    // falling edge - drive next MOSI bit
                    sh_tx <= {sh_tx[DATA_W-2:0], 1'b0};
                    mosi  <= sh_tx[DATA_W-2];
                    bit_cnt <= bit_cnt - 1;
                    if (bit_cnt == 1) begin
                        cs_n <= 1'b1; busy <= 1'b0;
                        rx_data <= {sh_rx[DATA_W-2:0], miso};
                        done <= 1'b1;
                    end
                end
            end else div_cnt <= div_cnt + 1;
        end
    end
endmodule
"""


def pll_config_sequencer(spec=None) -> str:
    """Generate PLL config sequencer parameterised by ComponentSpec.

    Spec.pll_config_reg_count tells the sequencer how many registers
    the chip needs at boot (HMC830 has ~12, LMK04832 has ~160). Without
    the spec we emit a simple 2-register N/R sequencer.
    """
    n_regs = (spec.pll_config_reg_count if spec else None) or 2
    bits   = (spec.pll_config_bit_width if spec else None) or 24
    mpn    = spec.mpn if spec else "PLL (generic)"
    src_tag = spec.source if spec else "default"
    conf    = spec.confidence if spec else 0.0
    _hdr = (
        f"// pll_config.v - sequencer for {mpn} "
        f"({n_regs} config registers, {bits}-bit SPI words).\n"
        f"// Spec source: {src_tag} (confidence {conf})\n"
        f"//\n"
        f"// Watches PLL_CTRL[0] (LATCH) writes and serialises\n"
        f"// PLL_N_DIV, PLL_R_DIV out to the PLL chip via spi_master.\n"
    )
    return _BANNER + _hdr + r"""

module pll_config (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [15:0] pll_ctrl,
    input  wire [15:0] pll_n_div,
    input  wire [15:0] pll_r_div,
    output reg         pll_locked,
    // SPI master ports
    output reg         spi_start,
    output reg  [23:0] spi_tx_data,
    input  wire [23:0] spi_rx_data,
    input  wire        spi_done
);
    localparam S_IDLE = 2'd0, S_TX_N = 2'd1, S_TX_R = 2'd2, S_DONE = 2'd3;
    reg [1:0] state = S_IDLE;
    reg pll_ctrl_d = 1'b0;

    always @(posedge clk) begin
        spi_start <= 1'b0;
        pll_ctrl_d <= pll_ctrl[0];
        if (!rst_n) begin
            state <= S_IDLE; pll_locked <= 1'b0;
        end else case (state)
            S_IDLE: if (pll_ctrl[0] && !pll_ctrl_d) begin
                spi_tx_data <= {8'h01, pll_n_div};   // reg 0x01 = N divider
                spi_start <= 1'b1; state <= S_TX_N;
            end
            S_TX_N: if (spi_done) begin
                spi_tx_data <= {8'h02, pll_r_div};   // reg 0x02 = R divider
                spi_start <= 1'b1; state <= S_TX_R;
            end
            S_TX_R: if (spi_done) begin
                pll_locked <= 1'b1; state <= S_DONE;
            end
            S_DONE: if (!pll_ctrl[0]) state <= S_IDLE;
        endcase
    end
endmodule
"""


# ---------------------------------------------------------------------------
# ADC capture FSM
# ---------------------------------------------------------------------------


def adc_capture(data_w: int = 14) -> str:
    return _BANNER + f"""
// adc_capture.v - latches incoming ADC samples into channel registers
// when ADC_CTRL[0] (ARM) is set. Transitions ARM -> WAIT -> SAMPLE -> DONE.

module adc_capture #(
    parameter integer DATA_W = {data_w}
) (
    input  wire                 clk,
    input  wire                 rst_n,
    input  wire                 adc_data_valid,
    input  wire [DATA_W-1:0]    adc_data,
    input  wire [15:0]          adc_ctrl,
    output reg  [15:0]          adc_status,
    output reg  [15:0]          ch1_data,
    output reg  [15:0]          ch2_data
);
    localparam S_IDLE = 2'd0, S_ARMED = 2'd1, S_LATCHED = 2'd2;
    reg [1:0]  state = S_IDLE;
    reg        arm_d = 1'b0;
    reg        toggle = 1'b0;     // alternate channel on consecutive samples

    always @(posedge clk) begin
        arm_d <= adc_ctrl[0];
        if (!rst_n) begin
            state <= S_IDLE; ch1_data <= 0; ch2_data <= 0;
            adc_status <= 16'h0000; toggle <= 0;
        end else case (state)
            S_IDLE:    if (adc_ctrl[0] && !arm_d) begin
                           state <= S_ARMED; adc_status[0] <= 1'b1;
                       end
            S_ARMED:   if (adc_data_valid) begin
                           if (toggle == 1'b0) ch1_data <= {{ {{(16-DATA_W){{1'b0}}}}, adc_data }};
                           else                ch2_data <= {{ {{(16-DATA_W){{1'b0}}}}, adc_data }};
                           toggle <= ~toggle;
                           adc_status[1] <= 1'b1;     // sample latched
                           state <= S_LATCHED;
                       end
            S_LATCHED: if (!adc_ctrl[0]) begin
                           adc_status <= 16'h0000;
                           state <= S_IDLE;
                       end
        endcase
    end
endmodule
"""


# ---------------------------------------------------------------------------
# I2C master + EEPROM driver
# ---------------------------------------------------------------------------


def i2c_master() -> str:
    return _BANNER + """
// i2c_master.v - byte-level I2C master with start/stop/restart.
// Drives SDA / SCL with open-drain semantics (using inout in the top).

module i2c_master #(
    parameter integer CLK_DIV = 250    // sets ~400 kHz at 100 MHz clk
) (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,
    input  wire        stop,
    input  wire        we,            // 1 = transmit byte_in, 0 = receive
    input  wire [7:0]  byte_in,
    output reg  [7:0]  byte_out,
    output reg         done,
    output reg         ack_err,
    inout  wire        scl,
    inout  wire        sda
);
    reg scl_oe = 1'b0, sda_oe = 1'b0;
    reg sda_drv = 1'b0;
    assign scl = scl_oe ? 1'b0 : 1'bz;
    assign sda = sda_oe ? sda_drv : 1'bz;
    wire sda_in = sda;

    reg [15:0] div_cnt = 0;
    wire tick = (div_cnt == CLK_DIV-1);
    always @(posedge clk) div_cnt <= tick ? 16'h0 : div_cnt + 1;

    reg [3:0] state = 4'h0;
    reg [3:0] bit_cnt = 4'h0;
    reg [7:0] sh = 8'h00;

    always @(posedge clk) begin
        done <= 1'b0;
        if (!rst_n) begin
            state <= 0; scl_oe <= 0; sda_oe <= 0; ack_err <= 0;
        end else if (tick) begin
            case (state)
                4'd0: if (start) begin sda_drv <= 1'b0; sda_oe <= 1'b1; state <= 4'd1; end
                4'd1: begin scl_oe <= 1'b1; sh <= byte_in; bit_cnt <= 7; state <= we ? 4'd2 : 4'd5; end
                // ---- transmit ----
                4'd2: begin sda_drv <= sh[bit_cnt]; sda_oe <= 1'b1; scl_oe <= 1'b0; state <= 4'd3; end
                4'd3: begin scl_oe <= 1'b1; state <= 4'd4; end
                4'd4: if (bit_cnt == 0) state <= 4'd9; else begin bit_cnt <= bit_cnt - 1; state <= 4'd2; end
                // ---- receive ----
                4'd5: begin sda_oe <= 1'b0; scl_oe <= 1'b0; state <= 4'd6; end
                4'd6: begin scl_oe <= 1'b1; sh[bit_cnt] <= sda_in; state <= 4'd7; end
                4'd7: if (bit_cnt == 0) begin byte_out <= sh; state <= 4'd9; end
                      else begin bit_cnt <= bit_cnt - 1; state <= 4'd5; end
                // ---- ACK + finish ----
                4'd9: begin sda_oe <= 1'b0; scl_oe <= 1'b1; ack_err <= sda_in; done <= 1'b1; state <= stop ? 4'd10 : 4'd0; end
                4'd10: begin sda_drv <= 1'b1; sda_oe <= 1'b1; scl_oe <= 1'b0; state <= 4'd0; end
            endcase
        end
    end
endmodule
"""


def eeprom_driver(spec=None, slave_addr: str = "0x50") -> str:
    """Generate EEPROM driver parameterised by ComponentSpec.

    The spec drives slave_addr, addr_width (8 vs 16 bit word addressing),
    and page_size - so an AT24C32 (8KB, 32B page, 16-bit addr) gets
    different RTL than an AT24C02 (256B, 8B page, 8-bit addr) even
    though both look like "EEPROM".
    """
    if spec is not None and spec.i2c_slave_addr_7bit is not None:
        addr_int = spec.i2c_slave_addr_7bit & 0x7F
    else:
        addr_int = int(slave_addr, 16) & 0x7F
    addr_w_bits = (spec.i2c_addr_width_bits if spec else None) or 16
    page_bytes  = (spec.i2c_page_size_bytes if spec else None) or 64
    write_cycle_ms = (spec.i2c_write_cycle_ms if spec else None) or 5
    mpn = spec.mpn if spec else "AT24-series"
    desc = spec.description if spec else "AT24-series serial EEPROM"
    src_tag = spec.source if spec else "default"
    conf    = spec.confidence if spec else 0.0
    addr_byte_block = ""
    if addr_w_bits == 16:
        addr_byte_block = (
            "                      i2c_byte_in <= eeprom_addr[15:8];\n"
            "                      i2c_we <= 1'b1; state <= 4'd1a;\n"
        )
    return _BANNER + f"""
// eeprom_driver.v - I2C EEPROM sequencer for {mpn}.
// {desc}
// Spec source: {src_tag} (confidence {conf})
// I2C slave addr : 0x{addr_int:02X}
// Word addr width: {addr_w_bits} bits
// Page size      : {page_bytes} bytes
// Write cycle    : {write_cycle_ms} ms

module eeprom_driver #(
    parameter [6:0]  SLAVE_ADDR     = 7'h{addr_int:02X},
    parameter integer ADDR_WIDTH    = {addr_w_bits},
    parameter integer PAGE_SIZE     = {page_bytes},
    parameter integer WR_CYCLE_MS   = {write_cycle_ms}
) (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [15:0] eeprom_ctrl,    // bit0 = start, bit1 = we (1=write)
    input  wire [15:0] eeprom_addr,
    input  wire [15:0] eeprom_data_in,
    output reg  [15:0] eeprom_data_out,
    output reg  [15:0] eeprom_status,
    // Wires to i2c_master
    output reg         i2c_start,
    output reg         i2c_stop,
    output reg         i2c_we,
    output reg  [7:0]  i2c_byte_in,
    input  wire [7:0]  i2c_byte_out,
    input  wire        i2c_done,
    input  wire        i2c_ack_err
);
    reg [3:0] state = 4'h0;
    reg ctrl_d = 1'b0;
    always @(posedge clk) begin
        i2c_start <= 0; i2c_stop <= 0; i2c_we <= 0;
        ctrl_d <= eeprom_ctrl[0];
        if (!rst_n) begin
            state <= 0; eeprom_status <= 0;
        end else case (state)
            4'd0: if (eeprom_ctrl[0] && !ctrl_d) begin
                      eeprom_status[0] <= 1'b1;     // busy
                      i2c_byte_in <= {{SLAVE_ADDR, ~eeprom_ctrl[1]}};  // addr+R/W
                      i2c_start <= 1'b1; i2c_we <= 1'b1; state <= 4'd1;
                  end
            4'd1: if (i2c_done) begin
                      i2c_byte_in <= eeprom_addr[7:0];
                      i2c_we <= 1'b1; state <= 4'd2;
                  end
            4'd2: if (i2c_done) begin
                      if (eeprom_ctrl[1]) begin
                          i2c_byte_in <= eeprom_data_in[7:0];
                          i2c_we <= 1'b1; i2c_stop <= 1'b1; state <= 4'd3;
                      end else begin
                          i2c_we <= 1'b0; i2c_stop <= 1'b1; state <= 4'd4;
                      end
                  end
            4'd3: if (i2c_done) begin
                      eeprom_status <= 16'h0000;    // done
                      state <= 4'd0;
                  end
            4'd4: if (i2c_done) begin
                      eeprom_data_out <= {{8'h00, i2c_byte_out}};
                      eeprom_status <= 16'h0000; state <= 4'd0;
                  end
        endcase
        if (i2c_ack_err) eeprom_status[15] <= 1'b1;
    end
endmodule
"""


# ---------------------------------------------------------------------------
# Flash controller (key-protected)
# ---------------------------------------------------------------------------


def flash_ctrl(spec=None, key: str = "0xA5C3") -> str:
    """Generate Flash controller parameterised by ComponentSpec.

    Spec drives the opcode table - so a Micron N25Q gets the right
    sector-erase opcode (0x20) vs a Macronix MX25L which uses 0xD8 for
    block erase. Without the spec the emitter falls back to the SPI NOR
    standard opcodes but flags it in the file header.
    """
    op = (spec.flash_opcodes if spec else None) or {
        "read":         0x03, "fast_read":     0x0B,
        "page_program": 0x02, "sector_erase":  0x20,
        "chip_erase":   0xC7, "write_enable":  0x06,
        "write_disable":0x04, "read_status":   0x05, "read_id": 0x9F,
    }
    cap_b   = (spec.flash_capacity_bytes  if spec else None) or 0
    pg      = (spec.flash_page_size_bytes if spec else None) or 256
    sec     = (spec.flash_sector_size_bytes if spec else None) or 4096
    mpn     = spec.mpn if spec else "SPI NOR Flash (generic)"
    desc    = spec.description if spec else "SPI NOR Flash, 4KB sector erase"
    src_tag = spec.source if spec else "default"
    conf    = spec.confidence if spec else 0.0
    return _BANNER + f"""
// flash_ctrl.v - SPI Flash controller for {mpn}.
// {desc}
// Spec source : {src_tag} (confidence {conf})
// Capacity    : {cap_b} bytes ({cap_b//(1024*1024) if cap_b else 0} MB)
// Page size   : {pg} bytes
// Sector size : {sec} bytes
// Opcodes     : read=0x{op.get('read',3):02X}  pp=0x{op.get('page_program',2):02X}  '
//               'se=0x{op.get('sector_erase',32):02X}  '
//               'wren=0x{op.get('write_enable',6):02X}
//
// Writes are gated by FLASH_KEY register match.

module flash_ctrl #(
    parameter [15:0] UNLOCK_KEY    = 16'h{int(key, 16) & 0xFFFF:04X},
    parameter [7:0]  OP_PROGRAM    = 8'h{op.get('page_program',2):02X},
    parameter [7:0]  OP_ERASE      = 8'h{op.get('sector_erase',32):02X},
    parameter [7:0]  OP_READ       = 8'h{op.get('read',3):02X},
    parameter [7:0]  OP_WREN       = 8'h{op.get('write_enable',6):02X},
    parameter integer PAGE_BYTES   = {pg},
    parameter integer SECTOR_BYTES = {sec}
) (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [15:0] flash_ctrl,
    input  wire [15:0] flash_addr_low,
    input  wire [15:0] flash_addr_high,
    input  wire [15:0] flash_data_in,
    input  wire [15:0] flash_key,
    output reg  [15:0] flash_data_out,
    output reg  [15:0] flash_status,    // bit0 = busy, bit1 = locked, bit2 = err
    // SPI master ports
    output reg         spi_start,
    output reg  [23:0] spi_tx_data,
    input  wire [23:0] spi_rx_data,
    input  wire        spi_done
);
    localparam S_IDLE     = 3'd0, S_WREN     = 3'd1,
               S_PROG     = 3'd2, S_ERASE    = 3'd3,
               S_READ_CMD = 3'd4, S_READ_RX  = 3'd5;
    reg [2:0] state = S_IDLE;
    reg ctrl_d = 1'b0;
    wire unlocked = (flash_key == UNLOCK_KEY);

    always @(posedge clk) begin
        spi_start <= 1'b0;
        ctrl_d <= |flash_ctrl[1:0];
        if (!rst_n) begin
            state <= S_IDLE; flash_status <= 16'h0002;   // locked
        end else begin
            flash_status[1] <= ~unlocked;
            case (state)
                S_IDLE: begin
                    flash_status[0] <= 1'b0;
                    if (flash_ctrl[0] && unlocked && !ctrl_d) begin
                        // Program: WREN then PP (0x02)
                        spi_tx_data <= {{8'h06, 16'h0000}};
                        spi_start <= 1'b1; state <= S_WREN;
                        flash_status[0] <= 1'b1;
                    end else if (flash_ctrl[1] && unlocked && !ctrl_d) begin
                        // Sector erase 0x20
                        spi_tx_data <= {{8'h20, flash_addr_low}};
                        spi_start <= 1'b1; state <= S_ERASE;
                        flash_status[0] <= 1'b1;
                    end else if (flash_ctrl[2] && !ctrl_d) begin
                        // Read 0x03
                        spi_tx_data <= {{8'h03, flash_addr_low}};
                        spi_start <= 1'b1; state <= S_READ_CMD;
                    end
                end
                S_WREN: if (spi_done) begin
                    spi_tx_data <= {{8'h02, flash_data_in}};
                    spi_start <= 1'b1; state <= S_PROG;
                end
                S_PROG, S_ERASE: if (spi_done) begin
                    flash_status[0] <= 1'b0; state <= S_IDLE;
                end
                S_READ_CMD: if (spi_done) state <= S_READ_RX;
                S_READ_RX: begin
                    flash_data_out <= spi_rx_data[15:0];
                    state <= S_IDLE;
                end
            endcase
        end
    end
endmodule
"""


# ---------------------------------------------------------------------------
# GPIO controller with IRQ
# ---------------------------------------------------------------------------


def gpio_ctrl(width: int = 8) -> str:
    return _BANNER + f"""
// gpio_ctrl.v - per-pin direction + output mux + edge-detect IRQ.
//   GPIO_CTRL    : bit n -> 1 = output, 0 = input
//   GPIO_INPUT   : current state of every pin (sampled)
//   GPIO_IRQ_MASK: bit n -> 1 = IRQ enabled on edge change
//   GPIO_IRQ_STATUS: write-1-to-clear pending edge events

module gpio_ctrl #(
    parameter integer W = {width}
) (
    input  wire           clk,
    input  wire           rst_n,
    input  wire  [15:0]   gpio_ctrl,
    output reg   [15:0]   gpio_input,
    input  wire  [15:0]   gpio_irq_mask,
    output reg   [15:0]   gpio_irq_status,
    inout  wire  [W-1:0]  gpio_io,
    output wire           gpio_irq
);
    reg  [W-1:0] gpio_out_r = 0;
    wire [W-1:0] gpio_dir = gpio_ctrl[W-1:0];
    genvar i;
    generate
        for (i = 0; i < W; i = i + 1) begin: pin_io
            assign gpio_io[i] = gpio_dir[i] ? gpio_out_r[i] : 1'bz;
        end
    endgenerate

    reg  [W-1:0] sample = 0, sample_d = 0;
    always @(posedge clk) begin
        if (!rst_n) begin
            gpio_input <= 0; gpio_irq_status <= 0;
            sample <= 0; sample_d <= 0;
        end else begin
            sample <= gpio_io;
            sample_d <= sample;
            gpio_input <= {{ {{(16-W){{1'b0}}}}, sample }};
            // Detect any edge while masked.
            gpio_irq_status <= gpio_irq_status |
                (({{ {{(16-W){{1'b0}}}}, sample ^ sample_d }}) & gpio_irq_mask);
        end
    end
    assign gpio_irq = |(gpio_irq_status & gpio_irq_mask);
endmodule
"""
